-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Block_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    input_stream_TVALID : IN STD_LOGIC;
    input_stream_TREADY : OUT STD_LOGIC;
    input_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    input_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    input_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    input_ping_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_ping_ce0 : OUT STD_LOGIC;
    input_ping_we0 : OUT STD_LOGIC;
    input_ping_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (6 downto 0) );
end;


architecture behav of Block_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal input_stream_V_data_V_0_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal input_stream_V_data_V_0_vld_in : STD_LOGIC;
    signal input_stream_V_data_V_0_vld_out : STD_LOGIC;
    signal input_stream_V_data_V_0_ack_in : STD_LOGIC;
    signal input_stream_V_data_V_0_ack_out : STD_LOGIC;
    signal input_stream_V_data_V_0_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal input_stream_V_data_V_0_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal input_stream_V_data_V_0_sel_rd : STD_LOGIC := '0';
    signal input_stream_V_data_V_0_sel_wr : STD_LOGIC := '0';
    signal input_stream_V_data_V_0_sel : STD_LOGIC;
    signal input_stream_V_data_V_0_load_A : STD_LOGIC;
    signal input_stream_V_data_V_0_load_B : STD_LOGIC;
    signal input_stream_V_data_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal input_stream_V_data_V_0_state_cmp_full : STD_LOGIC;
    signal input_stream_V_keep_V_0_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal input_stream_V_keep_V_0_vld_in : STD_LOGIC;
    signal input_stream_V_keep_V_0_vld_out : STD_LOGIC;
    signal input_stream_V_keep_V_0_ack_in : STD_LOGIC;
    signal input_stream_V_keep_V_0_ack_out : STD_LOGIC;
    signal input_stream_V_keep_V_0_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal input_stream_V_keep_V_0_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal input_stream_V_keep_V_0_sel_rd : STD_LOGIC := '0';
    signal input_stream_V_keep_V_0_sel_wr : STD_LOGIC := '0';
    signal input_stream_V_keep_V_0_sel : STD_LOGIC;
    signal input_stream_V_keep_V_0_load_A : STD_LOGIC;
    signal input_stream_V_keep_V_0_load_B : STD_LOGIC;
    signal input_stream_V_keep_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal input_stream_V_keep_V_0_state_cmp_full : STD_LOGIC;
    signal input_stream_V_strb_V_0_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal input_stream_V_strb_V_0_vld_in : STD_LOGIC;
    signal input_stream_V_strb_V_0_vld_out : STD_LOGIC;
    signal input_stream_V_strb_V_0_ack_in : STD_LOGIC;
    signal input_stream_V_strb_V_0_ack_out : STD_LOGIC;
    signal input_stream_V_strb_V_0_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal input_stream_V_strb_V_0_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal input_stream_V_strb_V_0_sel_rd : STD_LOGIC := '0';
    signal input_stream_V_strb_V_0_sel_wr : STD_LOGIC := '0';
    signal input_stream_V_strb_V_0_sel : STD_LOGIC;
    signal input_stream_V_strb_V_0_load_A : STD_LOGIC;
    signal input_stream_V_strb_V_0_load_B : STD_LOGIC;
    signal input_stream_V_strb_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal input_stream_V_strb_V_0_state_cmp_full : STD_LOGIC;
    signal input_stream_V_user_V_0_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal input_stream_V_user_V_0_vld_in : STD_LOGIC;
    signal input_stream_V_user_V_0_vld_out : STD_LOGIC;
    signal input_stream_V_user_V_0_ack_in : STD_LOGIC;
    signal input_stream_V_user_V_0_ack_out : STD_LOGIC;
    signal input_stream_V_user_V_0_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal input_stream_V_user_V_0_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal input_stream_V_user_V_0_sel_rd : STD_LOGIC := '0';
    signal input_stream_V_user_V_0_sel_wr : STD_LOGIC := '0';
    signal input_stream_V_user_V_0_sel : STD_LOGIC;
    signal input_stream_V_user_V_0_load_A : STD_LOGIC;
    signal input_stream_V_user_V_0_load_B : STD_LOGIC;
    signal input_stream_V_user_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal input_stream_V_user_V_0_state_cmp_full : STD_LOGIC;
    signal input_stream_V_last_V_0_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal input_stream_V_last_V_0_vld_in : STD_LOGIC;
    signal input_stream_V_last_V_0_vld_out : STD_LOGIC;
    signal input_stream_V_last_V_0_ack_in : STD_LOGIC;
    signal input_stream_V_last_V_0_ack_out : STD_LOGIC;
    signal input_stream_V_last_V_0_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal input_stream_V_last_V_0_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal input_stream_V_last_V_0_sel_rd : STD_LOGIC := '0';
    signal input_stream_V_last_V_0_sel_wr : STD_LOGIC := '0';
    signal input_stream_V_last_V_0_sel : STD_LOGIC;
    signal input_stream_V_last_V_0_load_A : STD_LOGIC;
    signal input_stream_V_last_V_0_load_B : STD_LOGIC;
    signal input_stream_V_last_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal input_stream_V_last_V_0_state_cmp_full : STD_LOGIC;
    signal input_stream_V_id_V_0_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal input_stream_V_id_V_0_vld_in : STD_LOGIC;
    signal input_stream_V_id_V_0_vld_out : STD_LOGIC;
    signal input_stream_V_id_V_0_ack_in : STD_LOGIC;
    signal input_stream_V_id_V_0_ack_out : STD_LOGIC;
    signal input_stream_V_id_V_0_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal input_stream_V_id_V_0_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal input_stream_V_id_V_0_sel_rd : STD_LOGIC := '0';
    signal input_stream_V_id_V_0_sel_wr : STD_LOGIC := '0';
    signal input_stream_V_id_V_0_sel : STD_LOGIC;
    signal input_stream_V_id_V_0_load_A : STD_LOGIC;
    signal input_stream_V_id_V_0_load_B : STD_LOGIC;
    signal input_stream_V_id_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal input_stream_V_id_V_0_state_cmp_full : STD_LOGIC;
    signal input_stream_V_dest_V_0_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal input_stream_V_dest_V_0_vld_in : STD_LOGIC;
    signal input_stream_V_dest_V_0_vld_out : STD_LOGIC;
    signal input_stream_V_dest_V_0_ack_in : STD_LOGIC;
    signal input_stream_V_dest_V_0_ack_out : STD_LOGIC;
    signal input_stream_V_dest_V_0_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal input_stream_V_dest_V_0_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal input_stream_V_dest_V_0_sel_rd : STD_LOGIC := '0';
    signal input_stream_V_dest_V_0_sel_wr : STD_LOGIC := '0';
    signal input_stream_V_dest_V_0_sel : STD_LOGIC;
    signal input_stream_V_dest_V_0_load_A : STD_LOGIC;
    signal input_stream_V_dest_V_0_load_B : STD_LOGIC;
    signal input_stream_V_dest_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal input_stream_V_dest_V_0_state_cmp_full : STD_LOGIC;
    signal seq : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal data_lens_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal data_lens_ce0 : STD_LOGIC;
    signal data_lens_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_read_input_fu_49_ap_start : STD_LOGIC;
    signal grp_read_input_fu_49_ap_done : STD_LOGIC;
    signal grp_read_input_fu_49_ap_idle : STD_LOGIC;
    signal grp_read_input_fu_49_ap_ready : STD_LOGIC;
    signal grp_read_input_fu_49_input_stream_TVALID : STD_LOGIC;
    signal grp_read_input_fu_49_input_stream_TREADY : STD_LOGIC;
    signal grp_read_input_fu_49_input_buf_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_read_input_fu_49_input_buf_ce0 : STD_LOGIC;
    signal grp_read_input_fu_49_input_buf_we0 : STD_LOGIC;
    signal grp_read_input_fu_49_input_buf_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_input_fu_49_seq_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_input_fu_49_seq_o_ap_vld : STD_LOGIC;
    signal grp_read_input_fu_49_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_fu_75_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal seq_assign_fu_80_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_75_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal seq_assign_fu_80_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_state1 : BOOLEAN;

    component read_input IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        input_stream_TVALID : IN STD_LOGIC;
        input_stream_TREADY : OUT STD_LOGIC;
        input_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        input_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        input_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        input_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        input_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        input_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        input_buf_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        input_buf_ce0 : OUT STD_LOGIC;
        input_buf_we0 : OUT STD_LOGIC;
        input_buf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        seq_i : IN STD_LOGIC_VECTOR (31 downto 0);
        seq_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        seq_o_ap_vld : OUT STD_LOGIC );
    end component;


    component Block_proc_data_lbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;



begin
    data_lens_U : component Block_proc_data_lbkb
    generic map (
        DataWidth => 7,
        AddressRange => 300,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => data_lens_address0,
        ce0 => data_lens_ce0,
        q0 => data_lens_q0);

    grp_read_input_fu_49 : component read_input
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_read_input_fu_49_ap_start,
        ap_done => grp_read_input_fu_49_ap_done,
        ap_idle => grp_read_input_fu_49_ap_idle,
        ap_ready => grp_read_input_fu_49_ap_ready,
        input_stream_TDATA => input_stream_V_data_V_0_data_out,
        input_stream_TVALID => grp_read_input_fu_49_input_stream_TVALID,
        input_stream_TREADY => grp_read_input_fu_49_input_stream_TREADY,
        input_stream_TKEEP => input_stream_V_keep_V_0_data_out,
        input_stream_TSTRB => input_stream_V_strb_V_0_data_out,
        input_stream_TUSER => input_stream_V_user_V_0_data_out,
        input_stream_TLAST => input_stream_V_last_V_0_data_out,
        input_stream_TID => input_stream_V_id_V_0_data_out,
        input_stream_TDEST => input_stream_V_dest_V_0_data_out,
        input_buf_address0 => grp_read_input_fu_49_input_buf_address0,
        input_buf_ce0 => grp_read_input_fu_49_input_buf_ce0,
        input_buf_we0 => grp_read_input_fu_49_input_buf_we0,
        input_buf_d0 => grp_read_input_fu_49_input_buf_d0,
        seq_i => seq,
        seq_o => grp_read_input_fu_49_seq_o,
        seq_o_ap_vld => grp_read_input_fu_49_seq_o_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_read_input_fu_49_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_read_input_fu_49_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_read_input_fu_49_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_read_input_fu_49_ap_ready = ap_const_logic_1)) then 
                    grp_read_input_fu_49_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_data_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_data_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((input_stream_V_data_V_0_ack_out = ap_const_logic_1) and (input_stream_V_data_V_0_vld_out = ap_const_logic_1))) then 
                                        input_stream_V_data_V_0_sel_rd <= not(input_stream_V_data_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_data_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_data_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((input_stream_V_data_V_0_ack_in = ap_const_logic_1) and (input_stream_V_data_V_0_vld_in = ap_const_logic_1))) then 
                                        input_stream_V_data_V_0_sel_wr <= not(input_stream_V_data_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_data_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_data_V_0_state <= ap_const_lv2_0;
            else
                if ((((input_stream_V_data_V_0_state = ap_const_lv2_2) and (input_stream_V_data_V_0_vld_in = ap_const_logic_0)) or ((input_stream_V_data_V_0_state = ap_const_lv2_3) and (input_stream_V_data_V_0_vld_in = ap_const_logic_0) and (input_stream_V_data_V_0_ack_out = ap_const_logic_1)))) then 
                    input_stream_V_data_V_0_state <= ap_const_lv2_2;
                elsif ((((input_stream_V_data_V_0_state = ap_const_lv2_1) and (input_stream_V_data_V_0_ack_out = ap_const_logic_0)) or ((input_stream_V_data_V_0_state = ap_const_lv2_3) and (input_stream_V_data_V_0_ack_out = ap_const_logic_0) and (input_stream_V_data_V_0_vld_in = ap_const_logic_1)))) then 
                    input_stream_V_data_V_0_state <= ap_const_lv2_1;
                elsif (((not(((input_stream_V_data_V_0_vld_in = ap_const_logic_0) and (input_stream_V_data_V_0_ack_out = ap_const_logic_1))) and not(((input_stream_V_data_V_0_ack_out = ap_const_logic_0) and (input_stream_V_data_V_0_vld_in = ap_const_logic_1))) and (input_stream_V_data_V_0_state = ap_const_lv2_3)) or ((input_stream_V_data_V_0_state = ap_const_lv2_1) and (input_stream_V_data_V_0_ack_out = ap_const_logic_1)) or ((input_stream_V_data_V_0_state = ap_const_lv2_2) and (input_stream_V_data_V_0_vld_in = ap_const_logic_1)))) then 
                    input_stream_V_data_V_0_state <= ap_const_lv2_3;
                else 
                    input_stream_V_data_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_dest_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_dest_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((input_stream_V_dest_V_0_ack_out = ap_const_logic_1) and (input_stream_V_dest_V_0_vld_out = ap_const_logic_1))) then 
                                        input_stream_V_dest_V_0_sel_rd <= not(input_stream_V_dest_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_dest_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_dest_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((input_stream_V_dest_V_0_ack_in = ap_const_logic_1) and (input_stream_V_dest_V_0_vld_in = ap_const_logic_1))) then 
                                        input_stream_V_dest_V_0_sel_wr <= not(input_stream_V_dest_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_dest_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_dest_V_0_state <= ap_const_lv2_0;
            else
                if ((((input_stream_V_dest_V_0_state = ap_const_lv2_2) and (input_stream_V_dest_V_0_vld_in = ap_const_logic_0)) or ((input_stream_V_dest_V_0_state = ap_const_lv2_3) and (input_stream_V_dest_V_0_vld_in = ap_const_logic_0) and (input_stream_V_dest_V_0_ack_out = ap_const_logic_1)))) then 
                    input_stream_V_dest_V_0_state <= ap_const_lv2_2;
                elsif ((((input_stream_V_dest_V_0_state = ap_const_lv2_1) and (input_stream_V_dest_V_0_ack_out = ap_const_logic_0)) or ((input_stream_V_dest_V_0_state = ap_const_lv2_3) and (input_stream_V_dest_V_0_ack_out = ap_const_logic_0) and (input_stream_V_dest_V_0_vld_in = ap_const_logic_1)))) then 
                    input_stream_V_dest_V_0_state <= ap_const_lv2_1;
                elsif (((not(((input_stream_V_dest_V_0_vld_in = ap_const_logic_0) and (input_stream_V_dest_V_0_ack_out = ap_const_logic_1))) and not(((input_stream_V_dest_V_0_ack_out = ap_const_logic_0) and (input_stream_V_dest_V_0_vld_in = ap_const_logic_1))) and (input_stream_V_dest_V_0_state = ap_const_lv2_3)) or ((input_stream_V_dest_V_0_state = ap_const_lv2_1) and (input_stream_V_dest_V_0_ack_out = ap_const_logic_1)) or ((input_stream_V_dest_V_0_state = ap_const_lv2_2) and (input_stream_V_dest_V_0_vld_in = ap_const_logic_1)))) then 
                    input_stream_V_dest_V_0_state <= ap_const_lv2_3;
                else 
                    input_stream_V_dest_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_id_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_id_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((input_stream_V_id_V_0_ack_out = ap_const_logic_1) and (input_stream_V_id_V_0_vld_out = ap_const_logic_1))) then 
                                        input_stream_V_id_V_0_sel_rd <= not(input_stream_V_id_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_id_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_id_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((input_stream_V_id_V_0_ack_in = ap_const_logic_1) and (input_stream_V_id_V_0_vld_in = ap_const_logic_1))) then 
                                        input_stream_V_id_V_0_sel_wr <= not(input_stream_V_id_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_id_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_id_V_0_state <= ap_const_lv2_0;
            else
                if ((((input_stream_V_id_V_0_state = ap_const_lv2_2) and (input_stream_V_id_V_0_vld_in = ap_const_logic_0)) or ((input_stream_V_id_V_0_state = ap_const_lv2_3) and (input_stream_V_id_V_0_vld_in = ap_const_logic_0) and (input_stream_V_id_V_0_ack_out = ap_const_logic_1)))) then 
                    input_stream_V_id_V_0_state <= ap_const_lv2_2;
                elsif ((((input_stream_V_id_V_0_state = ap_const_lv2_1) and (input_stream_V_id_V_0_ack_out = ap_const_logic_0)) or ((input_stream_V_id_V_0_state = ap_const_lv2_3) and (input_stream_V_id_V_0_ack_out = ap_const_logic_0) and (input_stream_V_id_V_0_vld_in = ap_const_logic_1)))) then 
                    input_stream_V_id_V_0_state <= ap_const_lv2_1;
                elsif (((not(((input_stream_V_id_V_0_vld_in = ap_const_logic_0) and (input_stream_V_id_V_0_ack_out = ap_const_logic_1))) and not(((input_stream_V_id_V_0_ack_out = ap_const_logic_0) and (input_stream_V_id_V_0_vld_in = ap_const_logic_1))) and (input_stream_V_id_V_0_state = ap_const_lv2_3)) or ((input_stream_V_id_V_0_state = ap_const_lv2_1) and (input_stream_V_id_V_0_ack_out = ap_const_logic_1)) or ((input_stream_V_id_V_0_state = ap_const_lv2_2) and (input_stream_V_id_V_0_vld_in = ap_const_logic_1)))) then 
                    input_stream_V_id_V_0_state <= ap_const_lv2_3;
                else 
                    input_stream_V_id_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_keep_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_keep_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((input_stream_V_keep_V_0_vld_out = ap_const_logic_1) and (input_stream_V_keep_V_0_ack_out = ap_const_logic_1))) then 
                                        input_stream_V_keep_V_0_sel_rd <= not(input_stream_V_keep_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_keep_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_keep_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((input_stream_V_keep_V_0_vld_in = ap_const_logic_1) and (input_stream_V_keep_V_0_ack_in = ap_const_logic_1))) then 
                                        input_stream_V_keep_V_0_sel_wr <= not(input_stream_V_keep_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_keep_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_keep_V_0_state <= ap_const_lv2_0;
            else
                if ((((input_stream_V_keep_V_0_state = ap_const_lv2_2) and (input_stream_V_keep_V_0_vld_in = ap_const_logic_0)) or ((input_stream_V_keep_V_0_state = ap_const_lv2_3) and (input_stream_V_keep_V_0_vld_in = ap_const_logic_0) and (input_stream_V_keep_V_0_ack_out = ap_const_logic_1)))) then 
                    input_stream_V_keep_V_0_state <= ap_const_lv2_2;
                elsif ((((input_stream_V_keep_V_0_state = ap_const_lv2_1) and (input_stream_V_keep_V_0_ack_out = ap_const_logic_0)) or ((input_stream_V_keep_V_0_state = ap_const_lv2_3) and (input_stream_V_keep_V_0_ack_out = ap_const_logic_0) and (input_stream_V_keep_V_0_vld_in = ap_const_logic_1)))) then 
                    input_stream_V_keep_V_0_state <= ap_const_lv2_1;
                elsif (((not(((input_stream_V_keep_V_0_vld_in = ap_const_logic_0) and (input_stream_V_keep_V_0_ack_out = ap_const_logic_1))) and not(((input_stream_V_keep_V_0_ack_out = ap_const_logic_0) and (input_stream_V_keep_V_0_vld_in = ap_const_logic_1))) and (input_stream_V_keep_V_0_state = ap_const_lv2_3)) or ((input_stream_V_keep_V_0_state = ap_const_lv2_1) and (input_stream_V_keep_V_0_ack_out = ap_const_logic_1)) or ((input_stream_V_keep_V_0_state = ap_const_lv2_2) and (input_stream_V_keep_V_0_vld_in = ap_const_logic_1)))) then 
                    input_stream_V_keep_V_0_state <= ap_const_lv2_3;
                else 
                    input_stream_V_keep_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_last_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_last_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((input_stream_V_last_V_0_ack_out = ap_const_logic_1) and (input_stream_V_last_V_0_vld_out = ap_const_logic_1))) then 
                                        input_stream_V_last_V_0_sel_rd <= not(input_stream_V_last_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_last_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_last_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((input_stream_V_last_V_0_ack_in = ap_const_logic_1) and (input_stream_V_last_V_0_vld_in = ap_const_logic_1))) then 
                                        input_stream_V_last_V_0_sel_wr <= not(input_stream_V_last_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_last_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_last_V_0_state <= ap_const_lv2_0;
            else
                if ((((input_stream_V_last_V_0_state = ap_const_lv2_2) and (input_stream_V_last_V_0_vld_in = ap_const_logic_0)) or ((input_stream_V_last_V_0_state = ap_const_lv2_3) and (input_stream_V_last_V_0_vld_in = ap_const_logic_0) and (input_stream_V_last_V_0_ack_out = ap_const_logic_1)))) then 
                    input_stream_V_last_V_0_state <= ap_const_lv2_2;
                elsif ((((input_stream_V_last_V_0_state = ap_const_lv2_1) and (input_stream_V_last_V_0_ack_out = ap_const_logic_0)) or ((input_stream_V_last_V_0_state = ap_const_lv2_3) and (input_stream_V_last_V_0_ack_out = ap_const_logic_0) and (input_stream_V_last_V_0_vld_in = ap_const_logic_1)))) then 
                    input_stream_V_last_V_0_state <= ap_const_lv2_1;
                elsif (((not(((input_stream_V_last_V_0_vld_in = ap_const_logic_0) and (input_stream_V_last_V_0_ack_out = ap_const_logic_1))) and not(((input_stream_V_last_V_0_ack_out = ap_const_logic_0) and (input_stream_V_last_V_0_vld_in = ap_const_logic_1))) and (input_stream_V_last_V_0_state = ap_const_lv2_3)) or ((input_stream_V_last_V_0_state = ap_const_lv2_1) and (input_stream_V_last_V_0_ack_out = ap_const_logic_1)) or ((input_stream_V_last_V_0_state = ap_const_lv2_2) and (input_stream_V_last_V_0_vld_in = ap_const_logic_1)))) then 
                    input_stream_V_last_V_0_state <= ap_const_lv2_3;
                else 
                    input_stream_V_last_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_strb_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_strb_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((input_stream_V_strb_V_0_ack_out = ap_const_logic_1) and (input_stream_V_strb_V_0_vld_out = ap_const_logic_1))) then 
                                        input_stream_V_strb_V_0_sel_rd <= not(input_stream_V_strb_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_strb_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_strb_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((input_stream_V_strb_V_0_ack_in = ap_const_logic_1) and (input_stream_V_strb_V_0_vld_in = ap_const_logic_1))) then 
                                        input_stream_V_strb_V_0_sel_wr <= not(input_stream_V_strb_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_strb_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_strb_V_0_state <= ap_const_lv2_0;
            else
                if ((((input_stream_V_strb_V_0_state = ap_const_lv2_2) and (input_stream_V_strb_V_0_vld_in = ap_const_logic_0)) or ((input_stream_V_strb_V_0_state = ap_const_lv2_3) and (input_stream_V_strb_V_0_vld_in = ap_const_logic_0) and (input_stream_V_strb_V_0_ack_out = ap_const_logic_1)))) then 
                    input_stream_V_strb_V_0_state <= ap_const_lv2_2;
                elsif ((((input_stream_V_strb_V_0_state = ap_const_lv2_1) and (input_stream_V_strb_V_0_ack_out = ap_const_logic_0)) or ((input_stream_V_strb_V_0_state = ap_const_lv2_3) and (input_stream_V_strb_V_0_ack_out = ap_const_logic_0) and (input_stream_V_strb_V_0_vld_in = ap_const_logic_1)))) then 
                    input_stream_V_strb_V_0_state <= ap_const_lv2_1;
                elsif (((not(((input_stream_V_strb_V_0_vld_in = ap_const_logic_0) and (input_stream_V_strb_V_0_ack_out = ap_const_logic_1))) and not(((input_stream_V_strb_V_0_ack_out = ap_const_logic_0) and (input_stream_V_strb_V_0_vld_in = ap_const_logic_1))) and (input_stream_V_strb_V_0_state = ap_const_lv2_3)) or ((input_stream_V_strb_V_0_state = ap_const_lv2_1) and (input_stream_V_strb_V_0_ack_out = ap_const_logic_1)) or ((input_stream_V_strb_V_0_state = ap_const_lv2_2) and (input_stream_V_strb_V_0_vld_in = ap_const_logic_1)))) then 
                    input_stream_V_strb_V_0_state <= ap_const_lv2_3;
                else 
                    input_stream_V_strb_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_user_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_user_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((input_stream_V_user_V_0_ack_out = ap_const_logic_1) and (input_stream_V_user_V_0_vld_out = ap_const_logic_1))) then 
                                        input_stream_V_user_V_0_sel_rd <= not(input_stream_V_user_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_user_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_user_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((input_stream_V_user_V_0_ack_in = ap_const_logic_1) and (input_stream_V_user_V_0_vld_in = ap_const_logic_1))) then 
                                        input_stream_V_user_V_0_sel_wr <= not(input_stream_V_user_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    input_stream_V_user_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_stream_V_user_V_0_state <= ap_const_lv2_0;
            else
                if ((((input_stream_V_user_V_0_state = ap_const_lv2_2) and (input_stream_V_user_V_0_vld_in = ap_const_logic_0)) or ((input_stream_V_user_V_0_state = ap_const_lv2_3) and (input_stream_V_user_V_0_vld_in = ap_const_logic_0) and (input_stream_V_user_V_0_ack_out = ap_const_logic_1)))) then 
                    input_stream_V_user_V_0_state <= ap_const_lv2_2;
                elsif ((((input_stream_V_user_V_0_state = ap_const_lv2_1) and (input_stream_V_user_V_0_ack_out = ap_const_logic_0)) or ((input_stream_V_user_V_0_state = ap_const_lv2_3) and (input_stream_V_user_V_0_ack_out = ap_const_logic_0) and (input_stream_V_user_V_0_vld_in = ap_const_logic_1)))) then 
                    input_stream_V_user_V_0_state <= ap_const_lv2_1;
                elsif (((not(((input_stream_V_user_V_0_vld_in = ap_const_logic_0) and (input_stream_V_user_V_0_ack_out = ap_const_logic_1))) and not(((input_stream_V_user_V_0_ack_out = ap_const_logic_0) and (input_stream_V_user_V_0_vld_in = ap_const_logic_1))) and (input_stream_V_user_V_0_state = ap_const_lv2_3)) or ((input_stream_V_user_V_0_state = ap_const_lv2_1) and (input_stream_V_user_V_0_ack_out = ap_const_logic_1)) or ((input_stream_V_user_V_0_state = ap_const_lv2_2) and (input_stream_V_user_V_0_vld_in = ap_const_logic_1)))) then 
                    input_stream_V_user_V_0_state <= ap_const_lv2_3;
                else 
                    input_stream_V_user_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    seq_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                seq <= seq_assign_fu_80_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_read_input_fu_49_seq_o_ap_vld = ap_const_logic_1))) then 
                seq <= grp_read_input_fu_49_seq_o;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((input_stream_V_data_V_0_load_A = ap_const_logic_1)) then
                input_stream_V_data_V_0_payload_A <= input_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((input_stream_V_data_V_0_load_B = ap_const_logic_1)) then
                input_stream_V_data_V_0_payload_B <= input_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((input_stream_V_dest_V_0_load_A = ap_const_logic_1)) then
                input_stream_V_dest_V_0_payload_A <= input_stream_TDEST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((input_stream_V_dest_V_0_load_B = ap_const_logic_1)) then
                input_stream_V_dest_V_0_payload_B <= input_stream_TDEST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((input_stream_V_id_V_0_load_A = ap_const_logic_1)) then
                input_stream_V_id_V_0_payload_A <= input_stream_TID;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((input_stream_V_id_V_0_load_B = ap_const_logic_1)) then
                input_stream_V_id_V_0_payload_B <= input_stream_TID;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((input_stream_V_keep_V_0_load_A = ap_const_logic_1)) then
                input_stream_V_keep_V_0_payload_A <= input_stream_TKEEP;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((input_stream_V_keep_V_0_load_B = ap_const_logic_1)) then
                input_stream_V_keep_V_0_payload_B <= input_stream_TKEEP;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((input_stream_V_last_V_0_load_A = ap_const_logic_1)) then
                input_stream_V_last_V_0_payload_A <= input_stream_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((input_stream_V_last_V_0_load_B = ap_const_logic_1)) then
                input_stream_V_last_V_0_payload_B <= input_stream_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((input_stream_V_strb_V_0_load_A = ap_const_logic_1)) then
                input_stream_V_strb_V_0_payload_A <= input_stream_TSTRB;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((input_stream_V_strb_V_0_load_B = ap_const_logic_1)) then
                input_stream_V_strb_V_0_payload_B <= input_stream_TSTRB;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((input_stream_V_user_V_0_load_A = ap_const_logic_1)) then
                input_stream_V_user_V_0_payload_A <= input_stream_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((input_stream_V_user_V_0_load_B = ap_const_logic_1)) then
                input_stream_V_user_V_0_payload_B <= input_stream_TUSER;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, grp_read_input_fu_49_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_read_input_fu_49_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= data_lens_q0;
    data_lens_address0 <= tmp_fu_75_p1(9 - 1 downto 0);

    data_lens_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            data_lens_ce0 <= ap_const_logic_1;
        else 
            data_lens_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_read_input_fu_49_ap_start <= grp_read_input_fu_49_ap_start_reg;
    grp_read_input_fu_49_input_stream_TVALID <= input_stream_V_dest_V_0_state(0);
    input_ping_address0 <= grp_read_input_fu_49_input_buf_address0;
    input_ping_ce0 <= grp_read_input_fu_49_input_buf_ce0;
    input_ping_d0 <= grp_read_input_fu_49_input_buf_d0;
    input_ping_we0 <= grp_read_input_fu_49_input_buf_we0;
    input_stream_TREADY <= input_stream_V_dest_V_0_state(1);
    input_stream_V_data_V_0_ack_in <= input_stream_V_data_V_0_state(1);

    input_stream_V_data_V_0_ack_out_assign_proc : process(grp_read_input_fu_49_input_stream_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_stream_V_data_V_0_ack_out <= grp_read_input_fu_49_input_stream_TREADY;
        else 
            input_stream_V_data_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    input_stream_V_data_V_0_data_out_assign_proc : process(input_stream_V_data_V_0_payload_A, input_stream_V_data_V_0_payload_B, input_stream_V_data_V_0_sel)
    begin
        if ((input_stream_V_data_V_0_sel = ap_const_logic_1)) then 
            input_stream_V_data_V_0_data_out <= input_stream_V_data_V_0_payload_B;
        else 
            input_stream_V_data_V_0_data_out <= input_stream_V_data_V_0_payload_A;
        end if; 
    end process;

    input_stream_V_data_V_0_load_A <= (input_stream_V_data_V_0_state_cmp_full and not(input_stream_V_data_V_0_sel_wr));
    input_stream_V_data_V_0_load_B <= (input_stream_V_data_V_0_state_cmp_full and input_stream_V_data_V_0_sel_wr);
    input_stream_V_data_V_0_sel <= input_stream_V_data_V_0_sel_rd;
    input_stream_V_data_V_0_state_cmp_full <= '0' when (input_stream_V_data_V_0_state = ap_const_lv2_1) else '1';
    input_stream_V_data_V_0_vld_in <= input_stream_TVALID;
    input_stream_V_data_V_0_vld_out <= input_stream_V_data_V_0_state(0);
    input_stream_V_dest_V_0_ack_in <= input_stream_V_dest_V_0_state(1);

    input_stream_V_dest_V_0_ack_out_assign_proc : process(grp_read_input_fu_49_input_stream_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_stream_V_dest_V_0_ack_out <= grp_read_input_fu_49_input_stream_TREADY;
        else 
            input_stream_V_dest_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    input_stream_V_dest_V_0_data_out_assign_proc : process(input_stream_V_dest_V_0_payload_A, input_stream_V_dest_V_0_payload_B, input_stream_V_dest_V_0_sel)
    begin
        if ((input_stream_V_dest_V_0_sel = ap_const_logic_1)) then 
            input_stream_V_dest_V_0_data_out <= input_stream_V_dest_V_0_payload_B;
        else 
            input_stream_V_dest_V_0_data_out <= input_stream_V_dest_V_0_payload_A;
        end if; 
    end process;

    input_stream_V_dest_V_0_load_A <= (input_stream_V_dest_V_0_state_cmp_full and not(input_stream_V_dest_V_0_sel_wr));
    input_stream_V_dest_V_0_load_B <= (input_stream_V_dest_V_0_state_cmp_full and input_stream_V_dest_V_0_sel_wr);
    input_stream_V_dest_V_0_sel <= input_stream_V_dest_V_0_sel_rd;
    input_stream_V_dest_V_0_state_cmp_full <= '0' when (input_stream_V_dest_V_0_state = ap_const_lv2_1) else '1';
    input_stream_V_dest_V_0_vld_in <= input_stream_TVALID;
    input_stream_V_dest_V_0_vld_out <= input_stream_V_dest_V_0_state(0);
    input_stream_V_id_V_0_ack_in <= input_stream_V_id_V_0_state(1);

    input_stream_V_id_V_0_ack_out_assign_proc : process(grp_read_input_fu_49_input_stream_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_stream_V_id_V_0_ack_out <= grp_read_input_fu_49_input_stream_TREADY;
        else 
            input_stream_V_id_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    input_stream_V_id_V_0_data_out_assign_proc : process(input_stream_V_id_V_0_payload_A, input_stream_V_id_V_0_payload_B, input_stream_V_id_V_0_sel)
    begin
        if ((input_stream_V_id_V_0_sel = ap_const_logic_1)) then 
            input_stream_V_id_V_0_data_out <= input_stream_V_id_V_0_payload_B;
        else 
            input_stream_V_id_V_0_data_out <= input_stream_V_id_V_0_payload_A;
        end if; 
    end process;

    input_stream_V_id_V_0_load_A <= (input_stream_V_id_V_0_state_cmp_full and not(input_stream_V_id_V_0_sel_wr));
    input_stream_V_id_V_0_load_B <= (input_stream_V_id_V_0_state_cmp_full and input_stream_V_id_V_0_sel_wr);
    input_stream_V_id_V_0_sel <= input_stream_V_id_V_0_sel_rd;
    input_stream_V_id_V_0_state_cmp_full <= '0' when (input_stream_V_id_V_0_state = ap_const_lv2_1) else '1';
    input_stream_V_id_V_0_vld_in <= input_stream_TVALID;
    input_stream_V_id_V_0_vld_out <= input_stream_V_id_V_0_state(0);
    input_stream_V_keep_V_0_ack_in <= input_stream_V_keep_V_0_state(1);

    input_stream_V_keep_V_0_ack_out_assign_proc : process(grp_read_input_fu_49_input_stream_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_stream_V_keep_V_0_ack_out <= grp_read_input_fu_49_input_stream_TREADY;
        else 
            input_stream_V_keep_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    input_stream_V_keep_V_0_data_out_assign_proc : process(input_stream_V_keep_V_0_payload_A, input_stream_V_keep_V_0_payload_B, input_stream_V_keep_V_0_sel)
    begin
        if ((input_stream_V_keep_V_0_sel = ap_const_logic_1)) then 
            input_stream_V_keep_V_0_data_out <= input_stream_V_keep_V_0_payload_B;
        else 
            input_stream_V_keep_V_0_data_out <= input_stream_V_keep_V_0_payload_A;
        end if; 
    end process;

    input_stream_V_keep_V_0_load_A <= (input_stream_V_keep_V_0_state_cmp_full and not(input_stream_V_keep_V_0_sel_wr));
    input_stream_V_keep_V_0_load_B <= (input_stream_V_keep_V_0_state_cmp_full and input_stream_V_keep_V_0_sel_wr);
    input_stream_V_keep_V_0_sel <= input_stream_V_keep_V_0_sel_rd;
    input_stream_V_keep_V_0_state_cmp_full <= '0' when (input_stream_V_keep_V_0_state = ap_const_lv2_1) else '1';
    input_stream_V_keep_V_0_vld_in <= input_stream_TVALID;
    input_stream_V_keep_V_0_vld_out <= input_stream_V_keep_V_0_state(0);
    input_stream_V_last_V_0_ack_in <= input_stream_V_last_V_0_state(1);

    input_stream_V_last_V_0_ack_out_assign_proc : process(grp_read_input_fu_49_input_stream_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_stream_V_last_V_0_ack_out <= grp_read_input_fu_49_input_stream_TREADY;
        else 
            input_stream_V_last_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    input_stream_V_last_V_0_data_out_assign_proc : process(input_stream_V_last_V_0_payload_A, input_stream_V_last_V_0_payload_B, input_stream_V_last_V_0_sel)
    begin
        if ((input_stream_V_last_V_0_sel = ap_const_logic_1)) then 
            input_stream_V_last_V_0_data_out <= input_stream_V_last_V_0_payload_B;
        else 
            input_stream_V_last_V_0_data_out <= input_stream_V_last_V_0_payload_A;
        end if; 
    end process;

    input_stream_V_last_V_0_load_A <= (input_stream_V_last_V_0_state_cmp_full and not(input_stream_V_last_V_0_sel_wr));
    input_stream_V_last_V_0_load_B <= (input_stream_V_last_V_0_state_cmp_full and input_stream_V_last_V_0_sel_wr);
    input_stream_V_last_V_0_sel <= input_stream_V_last_V_0_sel_rd;
    input_stream_V_last_V_0_state_cmp_full <= '0' when (input_stream_V_last_V_0_state = ap_const_lv2_1) else '1';
    input_stream_V_last_V_0_vld_in <= input_stream_TVALID;
    input_stream_V_last_V_0_vld_out <= input_stream_V_last_V_0_state(0);
    input_stream_V_strb_V_0_ack_in <= input_stream_V_strb_V_0_state(1);

    input_stream_V_strb_V_0_ack_out_assign_proc : process(grp_read_input_fu_49_input_stream_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_stream_V_strb_V_0_ack_out <= grp_read_input_fu_49_input_stream_TREADY;
        else 
            input_stream_V_strb_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    input_stream_V_strb_V_0_data_out_assign_proc : process(input_stream_V_strb_V_0_payload_A, input_stream_V_strb_V_0_payload_B, input_stream_V_strb_V_0_sel)
    begin
        if ((input_stream_V_strb_V_0_sel = ap_const_logic_1)) then 
            input_stream_V_strb_V_0_data_out <= input_stream_V_strb_V_0_payload_B;
        else 
            input_stream_V_strb_V_0_data_out <= input_stream_V_strb_V_0_payload_A;
        end if; 
    end process;

    input_stream_V_strb_V_0_load_A <= (input_stream_V_strb_V_0_state_cmp_full and not(input_stream_V_strb_V_0_sel_wr));
    input_stream_V_strb_V_0_load_B <= (input_stream_V_strb_V_0_state_cmp_full and input_stream_V_strb_V_0_sel_wr);
    input_stream_V_strb_V_0_sel <= input_stream_V_strb_V_0_sel_rd;
    input_stream_V_strb_V_0_state_cmp_full <= '0' when (input_stream_V_strb_V_0_state = ap_const_lv2_1) else '1';
    input_stream_V_strb_V_0_vld_in <= input_stream_TVALID;
    input_stream_V_strb_V_0_vld_out <= input_stream_V_strb_V_0_state(0);
    input_stream_V_user_V_0_ack_in <= input_stream_V_user_V_0_state(1);

    input_stream_V_user_V_0_ack_out_assign_proc : process(grp_read_input_fu_49_input_stream_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_stream_V_user_V_0_ack_out <= grp_read_input_fu_49_input_stream_TREADY;
        else 
            input_stream_V_user_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    input_stream_V_user_V_0_data_out_assign_proc : process(input_stream_V_user_V_0_payload_A, input_stream_V_user_V_0_payload_B, input_stream_V_user_V_0_sel)
    begin
        if ((input_stream_V_user_V_0_sel = ap_const_logic_1)) then 
            input_stream_V_user_V_0_data_out <= input_stream_V_user_V_0_payload_B;
        else 
            input_stream_V_user_V_0_data_out <= input_stream_V_user_V_0_payload_A;
        end if; 
    end process;

    input_stream_V_user_V_0_load_A <= (input_stream_V_user_V_0_state_cmp_full and not(input_stream_V_user_V_0_sel_wr));
    input_stream_V_user_V_0_load_B <= (input_stream_V_user_V_0_state_cmp_full and input_stream_V_user_V_0_sel_wr);
    input_stream_V_user_V_0_sel <= input_stream_V_user_V_0_sel_rd;
    input_stream_V_user_V_0_state_cmp_full <= '0' when (input_stream_V_user_V_0_state = ap_const_lv2_1) else '1';
    input_stream_V_user_V_0_vld_in <= input_stream_TVALID;
    input_stream_V_user_V_0_vld_out <= input_stream_V_user_V_0_state(0);
    seq_assign_fu_80_p0 <= seq;
    seq_assign_fu_80_p2 <= std_logic_vector(signed(seq_assign_fu_80_p0) + signed(ap_const_lv32_1));
    tmp_fu_75_p0 <= seq;
        tmp_fu_75_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_75_p0),64));

end behav;
