// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sigmoid (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        res_V_address0,
        res_V_ce0,
        res_V_q0,
        res_V_address1,
        res_V_ce1,
        res_V_we1,
        res_V_d1
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state33 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] res_V_address0;
output   res_V_ce0;
input  [15:0] res_V_q0;
output  [6:0] res_V_address1;
output   res_V_ce1;
output   res_V_we1;
output  [15:0] res_V_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg res_V_ce0;
reg res_V_ce1;
reg res_V_we1;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] i_reg_137;
wire   [0:0] exitcond_fu_166_p2;
reg   [0:0] exitcond_reg_765;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
wire    ap_block_state7_pp0_stage0_iter5;
wire    ap_block_state8_pp0_stage0_iter6;
wire    ap_block_state9_pp0_stage0_iter7;
wire    ap_block_state10_pp0_stage0_iter8;
wire    ap_block_state11_pp0_stage0_iter9;
wire    ap_block_state12_pp0_stage0_iter10;
wire    ap_block_state13_pp0_stage0_iter11;
wire    ap_block_state14_pp0_stage0_iter12;
wire    ap_block_state15_pp0_stage0_iter13;
wire    ap_block_state16_pp0_stage0_iter14;
wire    ap_block_state17_pp0_stage0_iter15;
wire    ap_block_state18_pp0_stage0_iter16;
wire    ap_block_state19_pp0_stage0_iter17;
wire    ap_block_state20_pp0_stage0_iter18;
wire    ap_block_state21_pp0_stage0_iter19;
wire    ap_block_state22_pp0_stage0_iter20;
wire    ap_block_state23_pp0_stage0_iter21;
wire    ap_block_state24_pp0_stage0_iter22;
wire    ap_block_state25_pp0_stage0_iter23;
wire    ap_block_state26_pp0_stage0_iter24;
wire    ap_block_state27_pp0_stage0_iter25;
wire    ap_block_state28_pp0_stage0_iter26;
wire    ap_block_state29_pp0_stage0_iter27;
wire    ap_block_state30_pp0_stage0_iter28;
wire    ap_block_state31_pp0_stage0_iter29;
wire    ap_block_state32_pp0_stage0_iter30;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond_reg_765_pp0_iter1_reg;
reg   [0:0] exitcond_reg_765_pp0_iter2_reg;
reg   [0:0] exitcond_reg_765_pp0_iter3_reg;
reg   [0:0] exitcond_reg_765_pp0_iter4_reg;
reg   [0:0] exitcond_reg_765_pp0_iter5_reg;
reg   [0:0] exitcond_reg_765_pp0_iter6_reg;
reg   [0:0] exitcond_reg_765_pp0_iter7_reg;
reg   [0:0] exitcond_reg_765_pp0_iter8_reg;
reg   [0:0] exitcond_reg_765_pp0_iter9_reg;
reg   [0:0] exitcond_reg_765_pp0_iter10_reg;
reg   [0:0] exitcond_reg_765_pp0_iter11_reg;
reg   [0:0] exitcond_reg_765_pp0_iter12_reg;
reg   [0:0] exitcond_reg_765_pp0_iter13_reg;
reg   [0:0] exitcond_reg_765_pp0_iter14_reg;
reg   [0:0] exitcond_reg_765_pp0_iter15_reg;
reg   [0:0] exitcond_reg_765_pp0_iter16_reg;
reg   [0:0] exitcond_reg_765_pp0_iter17_reg;
reg   [0:0] exitcond_reg_765_pp0_iter18_reg;
reg   [0:0] exitcond_reg_765_pp0_iter19_reg;
reg   [0:0] exitcond_reg_765_pp0_iter20_reg;
reg   [0:0] exitcond_reg_765_pp0_iter21_reg;
reg   [0:0] exitcond_reg_765_pp0_iter22_reg;
reg   [0:0] exitcond_reg_765_pp0_iter23_reg;
reg   [0:0] exitcond_reg_765_pp0_iter24_reg;
reg   [0:0] exitcond_reg_765_pp0_iter25_reg;
reg   [0:0] exitcond_reg_765_pp0_iter26_reg;
reg   [0:0] exitcond_reg_765_pp0_iter27_reg;
reg   [0:0] exitcond_reg_765_pp0_iter28_reg;
reg   [0:0] exitcond_reg_765_pp0_iter29_reg;
wire   [7:0] i_2_fu_172_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [6:0] x_V_addr_reg_774;
reg   [6:0] x_V_addr_reg_774_pp0_iter1_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter2_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter3_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter4_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter5_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter6_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter7_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter8_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter9_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter10_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter11_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter12_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter13_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter14_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter15_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter16_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter17_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter18_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter19_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter20_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter21_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter22_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter23_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter24_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter25_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter26_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter27_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter28_reg;
reg   [6:0] x_V_addr_reg_774_pp0_iter29_reg;
wire   [0:0] tmp_s_fu_183_p2;
reg   [0:0] tmp_s_reg_780;
reg   [0:0] tmp_s_reg_780_pp0_iter2_reg;
wire   [0:0] p_Result_33_fu_189_p3;
reg   [0:0] p_Result_33_reg_785;
reg   [0:0] p_Result_33_reg_785_pp0_iter2_reg;
wire   [15:0] tmp_V_12_fu_203_p3;
reg   [15:0] tmp_V_12_reg_790;
reg   [15:0] tmp_V_12_reg_790_pp0_iter2_reg;
reg   [31:0] l_fu_229_p3;
reg   [31:0] l_reg_797;
wire   [7:0] tmp_108_fu_237_p1;
reg   [7:0] tmp_108_reg_802;
reg   [7:0] tmp_108_reg_802_pp0_iter2_reg;
wire   [31:0] tmp_62_fu_348_p3;
reg   [31:0] tmp_62_reg_807;
wire   [0:0] tmp_63_fu_356_p2;
reg   [0:0] tmp_63_reg_812;
wire   [31:0] tmp_64_fu_362_p2;
reg   [31:0] tmp_64_reg_817;
wire   [31:0] tmp_66_fu_368_p2;
reg   [31:0] tmp_66_reg_822;
wire   [31:0] x_assign_fu_469_p3;
reg   [31:0] x_assign_reg_827;
wire   [31:0] grp_fu_161_p2;
reg   [31:0] tmp_i_i_reg_832;
wire   [31:0] grp_fu_148_p2;
reg   [31:0] tmp_70_reg_837;
wire   [31:0] grp_fu_153_p2;
reg   [31:0] v_assign_reg_842;
reg   [31:0] v_assign_reg_842_pp0_iter28_reg;
reg   [0:0] p_Result_36_reg_848;
wire   [51:0] tmp_111_fu_506_p1;
reg   [51:0] tmp_111_reg_853;
wire   [0:0] tmp_73_fu_510_p2;
reg   [0:0] tmp_73_reg_858;
wire   [11:0] F2_fu_516_p2;
reg   [11:0] F2_reg_864;
wire   [15:0] newSel9_fu_757_p3;
reg   [15:0] newSel9_reg_872;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
wire   [63:0] tmp_fu_178_p1;
wire    ap_block_pp0_stage0;
wire   [15:0] tmp_V_fu_197_p2;
reg   [15:0] p_Result_s_fu_211_p4;
wire   [31:0] p_Result_34_fu_221_p3;
wire   [31:0] tmp_57_fu_241_p2;
wire   [31:0] lsb_index_fu_250_p2;
wire   [30:0] tmp_95_fu_256_p4;
wire   [4:0] tmp_98_fu_272_p1;
wire   [4:0] tmp_99_fu_276_p2;
wire   [15:0] tmp_103_fu_282_p1;
wire   [15:0] tmp_104_fu_286_p2;
wire   [15:0] p_Result_28_fu_292_p2;
wire   [0:0] icmp_fu_266_p2;
wire   [0:0] tmp_58_fu_297_p2;
wire   [0:0] tmp_106_fu_309_p3;
wire   [15:0] tmp_93_fu_246_p1;
wire   [15:0] tmp_59_fu_323_p2;
wire   [0:0] p_Result_29_fu_329_p3;
wire   [0:0] rev_fu_317_p2;
wire   [0:0] tmp_60_fu_336_p2;
wire   [0:0] a_fu_303_p2;
wire   [0:0] tmp_61_fu_342_p2;
wire   [31:0] m_fu_374_p1;
wire   [31:0] tmp_65_fu_377_p2;
wire   [31:0] tmp_67_fu_382_p2;
wire   [31:0] m_9_fu_387_p3;
wire   [31:0] m_1_fu_394_p2;
wire   [30:0] m_s_fu_399_p4;
wire   [0:0] tmp_107_fu_413_p3;
wire   [7:0] tmp_68_fu_429_p2;
wire   [7:0] tmp_165_cast_cast_fu_421_p3;
wire   [7:0] p_Repl2_13_trunc_fu_434_p2;
wire   [31:0] m_12_fu_409_p1;
wire   [8:0] tmp_69_fu_440_p3;
wire   [31:0] p_Result_35_fu_447_p5;
wire   [31:0] p_Result_71_op_fu_459_p2;
wire   [31:0] tmp_23_fu_465_p1;
wire   [63:0] d_assign_fu_158_p1;
wire   [63:0] ireg_V_fu_476_p1;
wire   [10:0] exp_tmp_V_fu_492_p4;
wire   [62:0] tmp_109_fu_480_p1;
wire   [11:0] tmp_71_fu_502_p1;
wire   [52:0] tmp_72_fu_522_p3;
wire   [53:0] p_Result_37_fu_529_p1;
wire   [53:0] man_V_3_fu_533_p2;
wire   [0:0] tmp_74_fu_546_p2;
wire   [11:0] tmp_75_fu_551_p2;
wire   [11:0] tmp_76_fu_556_p2;
wire  signed [11:0] sh_amt_fu_561_p3;
wire   [53:0] man_V_4_fu_539_p3;
wire   [7:0] tmp_113_fu_588_p4;
wire  signed [31:0] sh_amt_cast_fu_569_p1;
wire   [53:0] tmp_79_fu_604_p1;
wire   [53:0] tmp_80_fu_608_p2;
wire   [31:0] ireg_V_to_int_fu_618_p1;
wire   [0:0] tmp_115_fu_621_p3;
wire  signed [15:0] tmp_112_fu_578_p1;
wire  signed [31:0] tmp_82_fu_637_p1;
wire   [31:0] tmp_83_fu_641_p2;
wire   [0:0] tmp_77_fu_573_p2;
wire   [0:0] sel_tmp1_fu_651_p2;
wire   [0:0] sel_tmp6_demorgan_fu_662_p2;
wire   [0:0] sel_tmp6_fu_667_p2;
wire   [0:0] tmp_78_fu_582_p2;
wire   [0:0] sel_tmp7_fu_673_p2;
wire   [0:0] sel_tmp8_fu_679_p2;
wire   [0:0] sel_tmp21_demorgan_fu_697_p2;
wire   [0:0] icmp3_fu_598_p2;
wire   [0:0] sel_tmp4_fu_703_p2;
wire   [0:0] sel_tmp5_fu_709_p2;
wire   [15:0] tmp_116_fu_647_p1;
wire   [15:0] tmp_114_fu_614_p1;
wire   [0:0] sel_tmp_fu_691_p2;
wire   [0:0] sel_tmp9_fu_685_p2;
wire   [15:0] tmp_81_fu_629_p3;
wire   [0:0] sel_tmp2_fu_656_p2;
wire   [0:0] or_cond_fu_723_p2;
wire   [15:0] newSel_fu_715_p3;
wire   [15:0] newSel7_fu_729_p3;
wire   [0:0] or_cond5_fu_737_p2;
wire   [0:0] or_cond6_fu_751_p2;
wire   [15:0] newSel8_fu_743_p3;
wire    ap_CS_fsm_state33;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
end

LSTM_Top_fadd_32ncud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
LSTM_Top_fadd_32ncud_U161(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_i_i_reg_832),
    .din1(32'd1065353216),
    .ce(1'b1),
    .dout(grp_fu_148_p2)
);

LSTM_Top_fdiv_32ndEe #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
LSTM_Top_fdiv_32ndEe_U162(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1065353216),
    .din1(tmp_70_reg_837),
    .ce(1'b1),
    .dout(grp_fu_153_p2)
);

LSTM_Top_fpext_32eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
LSTM_Top_fpext_32eOg_U163(
    .din0(v_assign_reg_842),
    .dout(d_assign_fu_158_p1)
);

LSTM_Top_fexp_32nfYi #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
LSTM_Top_fexp_32nfYi_U164(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(x_assign_reg_827),
    .ce(1'b1),
    .dout(grp_fu_161_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter30 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_fu_166_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        i_reg_137 <= i_2_fu_172_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_137 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_reg_765_pp0_iter27_reg == 1'd0))) begin
        F2_reg_864 <= F2_fu_516_p2;
        p_Result_36_reg_848 <= ireg_V_fu_476_p1[32'd63];
        tmp_111_reg_853 <= tmp_111_fu_506_p1;
        tmp_73_reg_858 <= tmp_73_fu_510_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond_reg_765 <= exitcond_fu_166_p2;
        exitcond_reg_765_pp0_iter1_reg <= exitcond_reg_765;
        x_V_addr_reg_774_pp0_iter1_reg <= x_V_addr_reg_774;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond_reg_765_pp0_iter10_reg <= exitcond_reg_765_pp0_iter9_reg;
        exitcond_reg_765_pp0_iter11_reg <= exitcond_reg_765_pp0_iter10_reg;
        exitcond_reg_765_pp0_iter12_reg <= exitcond_reg_765_pp0_iter11_reg;
        exitcond_reg_765_pp0_iter13_reg <= exitcond_reg_765_pp0_iter12_reg;
        exitcond_reg_765_pp0_iter14_reg <= exitcond_reg_765_pp0_iter13_reg;
        exitcond_reg_765_pp0_iter15_reg <= exitcond_reg_765_pp0_iter14_reg;
        exitcond_reg_765_pp0_iter16_reg <= exitcond_reg_765_pp0_iter15_reg;
        exitcond_reg_765_pp0_iter17_reg <= exitcond_reg_765_pp0_iter16_reg;
        exitcond_reg_765_pp0_iter18_reg <= exitcond_reg_765_pp0_iter17_reg;
        exitcond_reg_765_pp0_iter19_reg <= exitcond_reg_765_pp0_iter18_reg;
        exitcond_reg_765_pp0_iter20_reg <= exitcond_reg_765_pp0_iter19_reg;
        exitcond_reg_765_pp0_iter21_reg <= exitcond_reg_765_pp0_iter20_reg;
        exitcond_reg_765_pp0_iter22_reg <= exitcond_reg_765_pp0_iter21_reg;
        exitcond_reg_765_pp0_iter23_reg <= exitcond_reg_765_pp0_iter22_reg;
        exitcond_reg_765_pp0_iter24_reg <= exitcond_reg_765_pp0_iter23_reg;
        exitcond_reg_765_pp0_iter25_reg <= exitcond_reg_765_pp0_iter24_reg;
        exitcond_reg_765_pp0_iter26_reg <= exitcond_reg_765_pp0_iter25_reg;
        exitcond_reg_765_pp0_iter27_reg <= exitcond_reg_765_pp0_iter26_reg;
        exitcond_reg_765_pp0_iter28_reg <= exitcond_reg_765_pp0_iter27_reg;
        exitcond_reg_765_pp0_iter29_reg <= exitcond_reg_765_pp0_iter28_reg;
        exitcond_reg_765_pp0_iter2_reg <= exitcond_reg_765_pp0_iter1_reg;
        exitcond_reg_765_pp0_iter3_reg <= exitcond_reg_765_pp0_iter2_reg;
        exitcond_reg_765_pp0_iter4_reg <= exitcond_reg_765_pp0_iter3_reg;
        exitcond_reg_765_pp0_iter5_reg <= exitcond_reg_765_pp0_iter4_reg;
        exitcond_reg_765_pp0_iter6_reg <= exitcond_reg_765_pp0_iter5_reg;
        exitcond_reg_765_pp0_iter7_reg <= exitcond_reg_765_pp0_iter6_reg;
        exitcond_reg_765_pp0_iter8_reg <= exitcond_reg_765_pp0_iter7_reg;
        exitcond_reg_765_pp0_iter9_reg <= exitcond_reg_765_pp0_iter8_reg;
        p_Result_33_reg_785_pp0_iter2_reg <= p_Result_33_reg_785;
        tmp_108_reg_802_pp0_iter2_reg <= tmp_108_reg_802;
        tmp_V_12_reg_790_pp0_iter2_reg <= tmp_V_12_reg_790;
        tmp_s_reg_780_pp0_iter2_reg <= tmp_s_reg_780;
        v_assign_reg_842_pp0_iter28_reg <= v_assign_reg_842;
        x_V_addr_reg_774_pp0_iter10_reg <= x_V_addr_reg_774_pp0_iter9_reg;
        x_V_addr_reg_774_pp0_iter11_reg <= x_V_addr_reg_774_pp0_iter10_reg;
        x_V_addr_reg_774_pp0_iter12_reg <= x_V_addr_reg_774_pp0_iter11_reg;
        x_V_addr_reg_774_pp0_iter13_reg <= x_V_addr_reg_774_pp0_iter12_reg;
        x_V_addr_reg_774_pp0_iter14_reg <= x_V_addr_reg_774_pp0_iter13_reg;
        x_V_addr_reg_774_pp0_iter15_reg <= x_V_addr_reg_774_pp0_iter14_reg;
        x_V_addr_reg_774_pp0_iter16_reg <= x_V_addr_reg_774_pp0_iter15_reg;
        x_V_addr_reg_774_pp0_iter17_reg <= x_V_addr_reg_774_pp0_iter16_reg;
        x_V_addr_reg_774_pp0_iter18_reg <= x_V_addr_reg_774_pp0_iter17_reg;
        x_V_addr_reg_774_pp0_iter19_reg <= x_V_addr_reg_774_pp0_iter18_reg;
        x_V_addr_reg_774_pp0_iter20_reg <= x_V_addr_reg_774_pp0_iter19_reg;
        x_V_addr_reg_774_pp0_iter21_reg <= x_V_addr_reg_774_pp0_iter20_reg;
        x_V_addr_reg_774_pp0_iter22_reg <= x_V_addr_reg_774_pp0_iter21_reg;
        x_V_addr_reg_774_pp0_iter23_reg <= x_V_addr_reg_774_pp0_iter22_reg;
        x_V_addr_reg_774_pp0_iter24_reg <= x_V_addr_reg_774_pp0_iter23_reg;
        x_V_addr_reg_774_pp0_iter25_reg <= x_V_addr_reg_774_pp0_iter24_reg;
        x_V_addr_reg_774_pp0_iter26_reg <= x_V_addr_reg_774_pp0_iter25_reg;
        x_V_addr_reg_774_pp0_iter27_reg <= x_V_addr_reg_774_pp0_iter26_reg;
        x_V_addr_reg_774_pp0_iter28_reg <= x_V_addr_reg_774_pp0_iter27_reg;
        x_V_addr_reg_774_pp0_iter29_reg <= x_V_addr_reg_774_pp0_iter28_reg;
        x_V_addr_reg_774_pp0_iter2_reg <= x_V_addr_reg_774_pp0_iter1_reg;
        x_V_addr_reg_774_pp0_iter3_reg <= x_V_addr_reg_774_pp0_iter2_reg;
        x_V_addr_reg_774_pp0_iter4_reg <= x_V_addr_reg_774_pp0_iter3_reg;
        x_V_addr_reg_774_pp0_iter5_reg <= x_V_addr_reg_774_pp0_iter4_reg;
        x_V_addr_reg_774_pp0_iter6_reg <= x_V_addr_reg_774_pp0_iter5_reg;
        x_V_addr_reg_774_pp0_iter7_reg <= x_V_addr_reg_774_pp0_iter6_reg;
        x_V_addr_reg_774_pp0_iter8_reg <= x_V_addr_reg_774_pp0_iter7_reg;
        x_V_addr_reg_774_pp0_iter9_reg <= x_V_addr_reg_774_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_reg_765 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        l_reg_797 <= l_fu_229_p3;
        p_Result_33_reg_785 <= res_V_q0[32'd15];
        tmp_108_reg_802 <= tmp_108_fu_237_p1;
        tmp_V_12_reg_790 <= tmp_V_12_fu_203_p3;
        tmp_s_reg_780 <= tmp_s_fu_183_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_reg_765_pp0_iter28_reg == 1'd0))) begin
        newSel9_reg_872 <= newSel9_fu_757_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_765_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_reg_780 == 1'd0))) begin
        tmp_62_reg_807[0] <= tmp_62_fu_348_p3[0];
        tmp_63_reg_812 <= tmp_63_fu_356_p2;
        tmp_64_reg_817 <= tmp_64_fu_362_p2;
        tmp_66_reg_822 <= tmp_66_fu_368_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_765_pp0_iter14_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_70_reg_837 <= grp_fu_148_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_765_pp0_iter10_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_i_i_reg_832 <= grp_fu_161_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_reg_765_pp0_iter26_reg == 1'd0))) begin
        v_assign_reg_842 <= grp_fu_153_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_fu_166_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_V_addr_reg_774 <= tmp_fu_178_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_765_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_assign_reg_827 <= x_assign_fu_469_p3;
    end
end

always @ (*) begin
    if ((exitcond_fu_166_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state33) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0) & (ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        res_V_ce0 = 1'b1;
    end else begin
        res_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter30 == 1'b1))) begin
        res_V_ce1 = 1'b1;
    end else begin
        res_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter30 == 1'b1) & (exitcond_reg_765_pp0_iter29_reg == 1'd0))) begin
        res_V_we1 = 1'b1;
    end else begin
        res_V_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((exitcond_fu_166_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter29 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter30 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter29 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter30 == 1'b1)) | ((exitcond_fu_166_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign F2_fu_516_p2 = (12'd1075 - tmp_71_fu_502_p1);

assign a_fu_303_p2 = (tmp_58_fu_297_p2 & icmp_fu_266_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter29 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter30 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign exitcond_fu_166_p2 = ((i_reg_137 == 8'd128) ? 1'b1 : 1'b0);

assign exp_tmp_V_fu_492_p4 = {{ireg_V_fu_476_p1[62:52]}};

assign i_2_fu_172_p2 = (i_reg_137 + 8'd1);

assign icmp3_fu_598_p2 = ((tmp_113_fu_588_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_fu_266_p2 = (($signed(tmp_95_fu_256_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign ireg_V_fu_476_p1 = d_assign_fu_158_p1;

assign ireg_V_to_int_fu_618_p1 = v_assign_reg_842_pp0_iter28_reg;


always @ (p_Result_34_fu_221_p3) begin
    if (p_Result_34_fu_221_p3[0] == 1'b1) begin
        l_fu_229_p3 = 32'd0;
    end else if (p_Result_34_fu_221_p3[1] == 1'b1) begin
        l_fu_229_p3 = 32'd1;
    end else if (p_Result_34_fu_221_p3[2] == 1'b1) begin
        l_fu_229_p3 = 32'd2;
    end else if (p_Result_34_fu_221_p3[3] == 1'b1) begin
        l_fu_229_p3 = 32'd3;
    end else if (p_Result_34_fu_221_p3[4] == 1'b1) begin
        l_fu_229_p3 = 32'd4;
    end else if (p_Result_34_fu_221_p3[5] == 1'b1) begin
        l_fu_229_p3 = 32'd5;
    end else if (p_Result_34_fu_221_p3[6] == 1'b1) begin
        l_fu_229_p3 = 32'd6;
    end else if (p_Result_34_fu_221_p3[7] == 1'b1) begin
        l_fu_229_p3 = 32'd7;
    end else if (p_Result_34_fu_221_p3[8] == 1'b1) begin
        l_fu_229_p3 = 32'd8;
    end else if (p_Result_34_fu_221_p3[9] == 1'b1) begin
        l_fu_229_p3 = 32'd9;
    end else if (p_Result_34_fu_221_p3[10] == 1'b1) begin
        l_fu_229_p3 = 32'd10;
    end else if (p_Result_34_fu_221_p3[11] == 1'b1) begin
        l_fu_229_p3 = 32'd11;
    end else if (p_Result_34_fu_221_p3[12] == 1'b1) begin
        l_fu_229_p3 = 32'd12;
    end else if (p_Result_34_fu_221_p3[13] == 1'b1) begin
        l_fu_229_p3 = 32'd13;
    end else if (p_Result_34_fu_221_p3[14] == 1'b1) begin
        l_fu_229_p3 = 32'd14;
    end else if (p_Result_34_fu_221_p3[15] == 1'b1) begin
        l_fu_229_p3 = 32'd15;
    end else if (p_Result_34_fu_221_p3[16] == 1'b1) begin
        l_fu_229_p3 = 32'd16;
    end else if (p_Result_34_fu_221_p3[17] == 1'b1) begin
        l_fu_229_p3 = 32'd17;
    end else if (p_Result_34_fu_221_p3[18] == 1'b1) begin
        l_fu_229_p3 = 32'd18;
    end else if (p_Result_34_fu_221_p3[19] == 1'b1) begin
        l_fu_229_p3 = 32'd19;
    end else if (p_Result_34_fu_221_p3[20] == 1'b1) begin
        l_fu_229_p3 = 32'd20;
    end else if (p_Result_34_fu_221_p3[21] == 1'b1) begin
        l_fu_229_p3 = 32'd21;
    end else if (p_Result_34_fu_221_p3[22] == 1'b1) begin
        l_fu_229_p3 = 32'd22;
    end else if (p_Result_34_fu_221_p3[23] == 1'b1) begin
        l_fu_229_p3 = 32'd23;
    end else if (p_Result_34_fu_221_p3[24] == 1'b1) begin
        l_fu_229_p3 = 32'd24;
    end else if (p_Result_34_fu_221_p3[25] == 1'b1) begin
        l_fu_229_p3 = 32'd25;
    end else if (p_Result_34_fu_221_p3[26] == 1'b1) begin
        l_fu_229_p3 = 32'd26;
    end else if (p_Result_34_fu_221_p3[27] == 1'b1) begin
        l_fu_229_p3 = 32'd27;
    end else if (p_Result_34_fu_221_p3[28] == 1'b1) begin
        l_fu_229_p3 = 32'd28;
    end else if (p_Result_34_fu_221_p3[29] == 1'b1) begin
        l_fu_229_p3 = 32'd29;
    end else if (p_Result_34_fu_221_p3[30] == 1'b1) begin
        l_fu_229_p3 = 32'd30;
    end else if (p_Result_34_fu_221_p3[31] == 1'b1) begin
        l_fu_229_p3 = 32'd31;
    end else begin
        l_fu_229_p3 = 32'd32;
    end
end

assign lsb_index_fu_250_p2 = ($signed(32'd4294967272) + $signed(tmp_57_fu_241_p2));

assign m_12_fu_409_p1 = m_s_fu_399_p4;

assign m_1_fu_394_p2 = (tmp_62_reg_807 + m_9_fu_387_p3);

assign m_9_fu_387_p3 = ((tmp_63_reg_812[0:0] === 1'b1) ? tmp_65_fu_377_p2 : tmp_67_fu_382_p2);

assign m_fu_374_p1 = tmp_V_12_reg_790_pp0_iter2_reg;

assign m_s_fu_399_p4 = {{m_1_fu_394_p2[31:1]}};

assign man_V_3_fu_533_p2 = (54'd0 - p_Result_37_fu_529_p1);

assign man_V_4_fu_539_p3 = ((p_Result_36_reg_848[0:0] === 1'b1) ? man_V_3_fu_533_p2 : p_Result_37_fu_529_p1);

assign newSel7_fu_729_p3 = ((sel_tmp9_fu_685_p2[0:0] === 1'b1) ? tmp_81_fu_629_p3 : tmp_112_fu_578_p1);

assign newSel8_fu_743_p3 = ((or_cond_fu_723_p2[0:0] === 1'b1) ? newSel_fu_715_p3 : newSel7_fu_729_p3);

assign newSel9_fu_757_p3 = ((or_cond6_fu_751_p2[0:0] === 1'b1) ? newSel8_fu_743_p3 : 16'd0);

assign newSel_fu_715_p3 = ((sel_tmp5_fu_709_p2[0:0] === 1'b1) ? tmp_116_fu_647_p1 : tmp_114_fu_614_p1);

assign or_cond5_fu_737_p2 = (sel_tmp9_fu_685_p2 | sel_tmp2_fu_656_p2);

assign or_cond6_fu_751_p2 = (or_cond_fu_723_p2 | or_cond5_fu_737_p2);

assign or_cond_fu_723_p2 = (sel_tmp_fu_691_p2 | sel_tmp5_fu_709_p2);

assign p_Repl2_13_trunc_fu_434_p2 = (tmp_68_fu_429_p2 + tmp_165_cast_cast_fu_421_p3);

assign p_Result_28_fu_292_p2 = (tmp_V_12_reg_790 & tmp_104_fu_286_p2);

assign p_Result_29_fu_329_p3 = tmp_V_12_reg_790[tmp_59_fu_323_p2];

assign p_Result_33_fu_189_p3 = res_V_q0[32'd15];

assign p_Result_34_fu_221_p3 = {{16'd65535}, {p_Result_s_fu_211_p4}};

assign p_Result_35_fu_447_p5 = {{tmp_69_fu_440_p3}, {m_12_fu_409_p1[22:0]}};

assign p_Result_37_fu_529_p1 = tmp_72_fu_522_p3;

assign p_Result_71_op_fu_459_p2 = (p_Result_35_fu_447_p5 ^ 32'd2147483648);

integer ap_tvar_int_0;

always @ (tmp_V_12_fu_203_p3) begin
    for (ap_tvar_int_0 = 16 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 15 - 0) begin
            p_Result_s_fu_211_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_s_fu_211_p4[ap_tvar_int_0] = tmp_V_12_fu_203_p3[15 - ap_tvar_int_0];
        end
    end
end

assign res_V_address0 = tmp_fu_178_p1;

assign res_V_address1 = x_V_addr_reg_774_pp0_iter29_reg;

assign res_V_d1 = newSel9_reg_872;

assign rev_fu_317_p2 = (tmp_106_fu_309_p3 ^ 1'd1);

assign sel_tmp1_fu_651_p2 = (tmp_73_reg_858 ^ 1'd1);

assign sel_tmp21_demorgan_fu_697_p2 = (tmp_74_fu_546_p2 | sel_tmp6_demorgan_fu_662_p2);

assign sel_tmp2_fu_656_p2 = (tmp_77_fu_573_p2 & sel_tmp1_fu_651_p2);

assign sel_tmp4_fu_703_p2 = (sel_tmp21_demorgan_fu_697_p2 ^ 1'd1);

assign sel_tmp5_fu_709_p2 = (sel_tmp4_fu_703_p2 & icmp3_fu_598_p2);

assign sel_tmp6_demorgan_fu_662_p2 = (tmp_77_fu_573_p2 | tmp_73_reg_858);

assign sel_tmp6_fu_667_p2 = (sel_tmp6_demorgan_fu_662_p2 ^ 1'd1);

assign sel_tmp7_fu_673_p2 = (tmp_74_fu_546_p2 & sel_tmp6_fu_667_p2);

assign sel_tmp8_fu_679_p2 = (tmp_78_fu_582_p2 ^ 1'd1);

assign sel_tmp9_fu_685_p2 = (sel_tmp8_fu_679_p2 & sel_tmp7_fu_673_p2);

assign sel_tmp_fu_691_p2 = (tmp_78_fu_582_p2 & sel_tmp7_fu_673_p2);

assign sh_amt_cast_fu_569_p1 = sh_amt_fu_561_p3;

assign sh_amt_fu_561_p3 = ((tmp_74_fu_546_p2[0:0] === 1'b1) ? tmp_75_fu_551_p2 : tmp_76_fu_556_p2);

assign tmp_103_fu_282_p1 = tmp_99_fu_276_p2;

assign tmp_104_fu_286_p2 = 16'd65535 >> tmp_103_fu_282_p1;

assign tmp_106_fu_309_p3 = lsb_index_fu_250_p2[32'd31];

assign tmp_107_fu_413_p3 = m_1_fu_394_p2[32'd25];

assign tmp_108_fu_237_p1 = l_fu_229_p3[7:0];

assign tmp_109_fu_480_p1 = ireg_V_fu_476_p1[62:0];

assign tmp_111_fu_506_p1 = ireg_V_fu_476_p1[51:0];

assign tmp_112_fu_578_p1 = man_V_4_fu_539_p3[15:0];

assign tmp_113_fu_588_p4 = {{sh_amt_fu_561_p3[11:4]}};

assign tmp_114_fu_614_p1 = tmp_80_fu_608_p2[15:0];

assign tmp_115_fu_621_p3 = ireg_V_to_int_fu_618_p1[32'd31];

assign tmp_116_fu_647_p1 = tmp_83_fu_641_p2[15:0];

assign tmp_165_cast_cast_fu_421_p3 = ((tmp_107_fu_413_p3[0:0] === 1'b1) ? 8'd127 : 8'd126);

assign tmp_23_fu_465_p1 = p_Result_71_op_fu_459_p2;

assign tmp_57_fu_241_p2 = (32'd16 - l_reg_797);

assign tmp_58_fu_297_p2 = ((p_Result_28_fu_292_p2 != 16'd0) ? 1'b1 : 1'b0);

assign tmp_59_fu_323_p2 = ($signed(16'd65512) + $signed(tmp_93_fu_246_p1));

assign tmp_60_fu_336_p2 = (rev_fu_317_p2 & p_Result_29_fu_329_p3);

assign tmp_61_fu_342_p2 = (tmp_60_fu_336_p2 | a_fu_303_p2);

assign tmp_62_fu_348_p3 = {{31'd0}, {tmp_61_fu_342_p2}};

assign tmp_63_fu_356_p2 = (($signed(lsb_index_fu_250_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_64_fu_362_p2 = ($signed(32'd4294967271) + $signed(tmp_57_fu_241_p2));

assign tmp_65_fu_377_p2 = m_fu_374_p1 >> tmp_64_reg_817;

assign tmp_66_fu_368_p2 = (32'd25 - tmp_57_fu_241_p2);

assign tmp_67_fu_382_p2 = m_fu_374_p1 << tmp_66_reg_822;

assign tmp_68_fu_429_p2 = (8'd5 - tmp_108_reg_802_pp0_iter2_reg);

assign tmp_69_fu_440_p3 = {{p_Result_33_reg_785_pp0_iter2_reg}, {p_Repl2_13_trunc_fu_434_p2}};

assign tmp_71_fu_502_p1 = exp_tmp_V_fu_492_p4;

assign tmp_72_fu_522_p3 = {{1'd1}, {tmp_111_reg_853}};

assign tmp_73_fu_510_p2 = ((tmp_109_fu_480_p1 == 63'd0) ? 1'b1 : 1'b0);

assign tmp_74_fu_546_p2 = (($signed(F2_reg_864) > $signed(12'd11)) ? 1'b1 : 1'b0);

assign tmp_75_fu_551_p2 = ($signed(12'd4085) + $signed(F2_reg_864));

assign tmp_76_fu_556_p2 = (12'd11 - F2_reg_864);

assign tmp_77_fu_573_p2 = ((F2_reg_864 == 12'd11) ? 1'b1 : 1'b0);

assign tmp_78_fu_582_p2 = ((sh_amt_fu_561_p3 < 12'd54) ? 1'b1 : 1'b0);

assign tmp_79_fu_604_p1 = $unsigned(sh_amt_cast_fu_569_p1);

assign tmp_80_fu_608_p2 = $signed(man_V_4_fu_539_p3) >>> tmp_79_fu_604_p1;

assign tmp_81_fu_629_p3 = ((tmp_115_fu_621_p3[0:0] === 1'b1) ? 16'd65535 : 16'd0);

assign tmp_82_fu_637_p1 = tmp_112_fu_578_p1;

assign tmp_83_fu_641_p2 = tmp_82_fu_637_p1 << sh_amt_cast_fu_569_p1;

assign tmp_93_fu_246_p1 = tmp_57_fu_241_p2[15:0];

assign tmp_95_fu_256_p4 = {{lsb_index_fu_250_p2[31:1]}};

assign tmp_98_fu_272_p1 = tmp_57_fu_241_p2[4:0];

assign tmp_99_fu_276_p2 = (5'd9 - tmp_98_fu_272_p1);

assign tmp_V_12_fu_203_p3 = ((p_Result_33_fu_189_p3[0:0] === 1'b1) ? tmp_V_fu_197_p2 : res_V_q0);

assign tmp_V_fu_197_p2 = (16'd0 - res_V_q0);

assign tmp_fu_178_p1 = i_reg_137;

assign tmp_s_fu_183_p2 = ((res_V_q0 == 16'd0) ? 1'b1 : 1'b0);

assign x_assign_fu_469_p3 = ((tmp_s_reg_780_pp0_iter2_reg[0:0] === 1'b1) ? 32'd2147483648 : tmp_23_fu_465_p1);

always @ (posedge ap_clk) begin
    tmp_62_reg_807[31:1] <= 31'b0000000000000000000000000000000;
end

endmodule //sigmoid
