-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity read_input is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    input_stream_TVALID : IN STD_LOGIC;
    input_stream_TREADY : OUT STD_LOGIC;
    input_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    input_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    input_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    input_buf_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    input_buf_ce0 : OUT STD_LOGIC;
    input_buf_we0 : OUT STD_LOGIC;
    input_buf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    seq_i : IN STD_LOGIC_VECTOR (31 downto 0);
    seq_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    seq_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of read_input is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv12_F3C : STD_LOGIC_VECTOR (11 downto 0) := "111100111100";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv32_12C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal input_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal exitcond_fu_98_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_2_fu_104_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal i_reg_87 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_25_fu_119_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_s_fu_134_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_128_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_reg_87_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((exitcond_fu_98_p2 = ap_const_lv1_0) and (input_stream_TVALID = ap_const_logic_0))) and (exitcond_fu_98_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_reg_87 <= i_2_fu_104_p2;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_reg_87 <= ap_const_lv12_0;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, input_stream_TVALID, ap_CS_fsm_state2, exitcond_fu_98_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((exitcond_fu_98_p2 = ap_const_lv1_0) and (input_stream_TVALID = ap_const_logic_0))) and (exitcond_fu_98_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif ((not(((exitcond_fu_98_p2 = ap_const_lv1_0) and (input_stream_TVALID = ap_const_logic_0))) and (exitcond_fu_98_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_block_state2_assign_proc : process(input_stream_TVALID, exitcond_fu_98_p2)
    begin
                ap_block_state2 <= ((exitcond_fu_98_p2 = ap_const_lv1_0) and (input_stream_TVALID = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    exitcond_fu_98_p2 <= "1" when (i_reg_87 = ap_const_lv12_F3C) else "0";
    i_2_fu_104_p2 <= std_logic_vector(unsigned(i_reg_87) + unsigned(ap_const_lv12_1));
    input_buf_address0 <= tmp_25_fu_119_p1(12 - 1 downto 0);

    input_buf_ce0_assign_proc : process(input_stream_TVALID, ap_CS_fsm_state2, exitcond_fu_98_p2)
    begin
        if ((not(((exitcond_fu_98_p2 = ap_const_lv1_0) and (input_stream_TVALID = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            input_buf_ce0 <= ap_const_logic_1;
        else 
            input_buf_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    input_buf_d0 <= input_stream_TDATA;

    input_buf_we0_assign_proc : process(input_stream_TVALID, ap_CS_fsm_state2, exitcond_fu_98_p2)
    begin
        if ((not(((exitcond_fu_98_p2 = ap_const_lv1_0) and (input_stream_TVALID = ap_const_logic_0))) and (exitcond_fu_98_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            input_buf_we0 <= ap_const_logic_1;
        else 
            input_buf_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_stream_TDATA_blk_n_assign_proc : process(input_stream_TVALID, ap_CS_fsm_state2, exitcond_fu_98_p2)
    begin
        if (((exitcond_fu_98_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            input_stream_TDATA_blk_n <= input_stream_TVALID;
        else 
            input_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    input_stream_TREADY_assign_proc : process(input_stream_TVALID, ap_CS_fsm_state2, exitcond_fu_98_p2)
    begin
        if ((not(((exitcond_fu_98_p2 = ap_const_lv1_0) and (input_stream_TVALID = ap_const_logic_0))) and (exitcond_fu_98_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            input_stream_TREADY <= ap_const_logic_1;
        else 
            input_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    seq_o_assign_proc : process(seq_i, ap_CS_fsm_state3, tmp_s_fu_134_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            seq_o <= tmp_s_fu_134_p3;
        else 
            seq_o <= seq_i;
        end if; 
    end process;


    seq_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            seq_o_ap_vld <= ap_const_logic_1;
        else 
            seq_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_25_fu_119_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_87),64));
    tmp_fu_128_p2 <= "1" when (seq_i = ap_const_lv32_12C) else "0";
    tmp_s_fu_134_p3 <= 
        ap_const_lv32_0 when (tmp_fu_128_p2(0) = '1') else 
        seq_i;
end behav;
