// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module should_skip (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_t_0_V_read,
        x_t_1_V_read,
        x_t_2_V_read,
        x_t_3_V_read,
        x_t_4_V_read,
        x_t_5_V_read,
        x_t_6_V_read,
        x_t_7_V_read,
        x_t_8_V_read,
        x_t_9_V_read,
        x_t_10_V_read,
        x_t_11_V_read,
        x_t_12_V_read,
        x_t_13_V_read,
        x_t_14_V_read,
        x_t_15_V_read,
        x_t_16_V_read,
        x_t_17_V_read,
        x_t_18_V_read,
        x_t_19_V_read,
        x_t_20_V_read,
        x_t_21_V_read,
        x_t_22_V_read,
        x_t_23_V_read,
        x_t_24_V_read,
        x_t_25_V_read,
        x_t_26_V_read,
        x_t_27_V_read,
        x_prev_V_address0,
        x_prev_V_ce0,
        x_prev_V_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_pp0_stage0 = 6'd2;
parameter    ap_ST_fsm_state4 = 6'd4;
parameter    ap_ST_fsm_state5 = 6'd8;
parameter    ap_ST_fsm_state6 = 6'd16;
parameter    ap_ST_fsm_state7 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] x_t_0_V_read;
input  [15:0] x_t_1_V_read;
input  [15:0] x_t_2_V_read;
input  [15:0] x_t_3_V_read;
input  [15:0] x_t_4_V_read;
input  [15:0] x_t_5_V_read;
input  [15:0] x_t_6_V_read;
input  [15:0] x_t_7_V_read;
input  [15:0] x_t_8_V_read;
input  [15:0] x_t_9_V_read;
input  [15:0] x_t_10_V_read;
input  [15:0] x_t_11_V_read;
input  [15:0] x_t_12_V_read;
input  [15:0] x_t_13_V_read;
input  [15:0] x_t_14_V_read;
input  [15:0] x_t_15_V_read;
input  [15:0] x_t_16_V_read;
input  [15:0] x_t_17_V_read;
input  [15:0] x_t_18_V_read;
input  [15:0] x_t_19_V_read;
input  [15:0] x_t_20_V_read;
input  [15:0] x_t_21_V_read;
input  [15:0] x_t_22_V_read;
input  [15:0] x_t_23_V_read;
input  [15:0] x_t_24_V_read;
input  [15:0] x_t_25_V_read;
input  [15:0] x_t_26_V_read;
input  [15:0] x_t_27_V_read;
output  [7:0] x_prev_V_address0;
output   x_prev_V_ce0;
input  [15:0] x_prev_V_q0;
output  [0:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg x_prev_V_ce0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] tmp_V_6_reg_383;
reg   [15:0] tmp_V_7_reg_395;
reg   [4:0] i_reg_407;
wire   [0:0] exitcond_fu_490_p2;
reg   [0:0] exitcond_reg_1377;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [4:0] i_1_fu_496_p2;
reg   [4:0] i_1_reg_1381;
reg    ap_enable_reg_pp0_iter0;
wire   [15:0] diff_sum_V_fu_533_p3;
reg    ap_enable_reg_pp0_iter1;
wire   [15:0] energy_V_fu_561_p3;
wire   [0:0] tmp_fu_569_p2;
reg   [0:0] tmp_reg_1401;
wire    ap_CS_fsm_state4;
wire   [0:0] p_Result_12_fu_575_p3;
reg   [0:0] p_Result_12_reg_1406;
wire   [15:0] tmp_V_8_fu_589_p3;
reg   [15:0] tmp_V_8_reg_1411;
reg   [31:0] l_fu_615_p3;
reg   [31:0] l_reg_1419;
wire   [10:0] tmp_478_fu_623_p1;
reg   [10:0] tmp_478_reg_1424;
wire   [0:0] tmp_24_fu_627_p2;
reg   [0:0] tmp_24_reg_1429;
wire   [0:0] p_Result_15_fu_633_p3;
reg   [0:0] p_Result_15_reg_1434;
wire   [15:0] tmp_V_9_fu_647_p3;
reg   [15:0] tmp_V_9_reg_1439;
reg   [31:0] l_1_fu_673_p3;
reg   [31:0] l_1_reg_1447;
wire   [10:0] tmp_489_fu_681_p1;
reg   [10:0] tmp_489_reg_1452;
wire   [31:0] tmp_1_fu_685_p2;
reg   [31:0] tmp_1_reg_1457;
wire    ap_CS_fsm_state5;
wire   [31:0] tmp_13_fu_792_p3;
reg   [31:0] tmp_13_reg_1463;
wire   [0:0] tmp_14_fu_800_p2;
reg   [0:0] tmp_14_reg_1468;
wire   [31:0] tmp_25_fu_806_p2;
reg   [31:0] tmp_25_reg_1473;
wire   [31:0] tmp_33_fu_913_p3;
reg   [31:0] tmp_33_reg_1479;
wire   [0:0] tmp_34_fu_921_p2;
reg   [0:0] tmp_34_reg_1484;
reg   [62:0] m_s_reg_1489;
wire    ap_CS_fsm_state6;
wire   [10:0] p_Repl2_2_trunc_fu_1010_p2;
reg   [10:0] p_Repl2_2_trunc_reg_1494;
wire   [0:0] notrhs_fu_1026_p2;
reg   [0:0] notrhs_reg_1500;
reg   [62:0] m_3_reg_1505;
wire   [10:0] p_Repl2_5_trunc_fu_1115_p2;
reg   [10:0] p_Repl2_5_trunc_reg_1510;
wire   [0:0] notrhs8_fu_1131_p2;
reg   [0:0] notrhs8_reg_1516;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
wire    ap_block_pp0_stage0;
reg   [4:0] ap_phi_mux_i_phi_fu_411_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_p_Val2_2_reg_419;
reg   [15:0] ap_phi_reg_pp0_iter1_p_Val2_2_reg_419;
wire   [63:0] tmp_s_fu_502_p1;
wire   [63:0] tmp_406_fu_480_p0;
wire    ap_CS_fsm_state7;
wire   [63:0] tmp_410_fu_485_p0;
wire   [15:0] delta_V_fu_507_p2;
wire   [0:0] tmp_490_fu_513_p3;
wire   [15:0] tmp_7_fu_527_p2;
wire   [15:0] addconv1_fu_521_p2;
wire   [0:0] tmp_491_fu_541_p3;
wire   [15:0] tmp_9_fu_555_p2;
wire   [15:0] addconv_fu_549_p2;
wire   [15:0] tmp_V_fu_583_p2;
reg   [15:0] p_Result_s_fu_597_p4;
wire   [31:0] p_Result_13_fu_607_p3;
wire   [15:0] tmp_V_2_fu_641_p2;
reg   [15:0] p_Result_7_fu_655_p4;
wire   [31:0] p_Result_16_fu_665_p3;
wire   [31:0] lsb_index_fu_694_p2;
wire   [30:0] tmp_470_fu_700_p4;
wire   [4:0] tmp_471_fu_716_p1;
wire   [4:0] tmp_472_fu_720_p2;
wire   [15:0] tmp_473_fu_726_p1;
wire   [15:0] tmp_474_fu_730_p2;
wire   [15:0] p_Result_3_fu_736_p2;
wire   [0:0] icmp_fu_710_p2;
wire   [0:0] tmp_4_fu_741_p2;
wire   [0:0] tmp_476_fu_753_p3;
wire   [15:0] tmp_469_fu_690_p1;
wire   [15:0] tmp_10_fu_767_p2;
wire   [0:0] p_Result_4_fu_773_p3;
wire   [0:0] rev_fu_761_p2;
wire   [0:0] tmp_12_fu_780_p2;
wire   [0:0] a_fu_747_p2;
wire   [0:0] tmp_261_fu_786_p2;
wire   [31:0] lsb_index_1_fu_815_p2;
wire   [30:0] tmp_481_fu_821_p4;
wire   [4:0] tmp_482_fu_837_p1;
wire   [4:0] tmp_483_fu_841_p2;
wire   [15:0] tmp_484_fu_847_p1;
wire   [15:0] tmp_485_fu_851_p2;
wire   [15:0] p_Result_9_fu_857_p2;
wire   [0:0] icmp1_fu_831_p2;
wire   [0:0] tmp_28_fu_862_p2;
wire   [0:0] tmp_487_fu_874_p3;
wire   [15:0] tmp_480_fu_811_p1;
wire   [15:0] tmp_30_fu_888_p2;
wire   [0:0] p_Result_10_fu_894_p3;
wire   [0:0] rev1_fu_882_p2;
wire   [0:0] tmp_32_fu_901_p2;
wire   [0:0] a_1_fu_868_p2;
wire   [0:0] tmp_266_fu_907_p2;
wire   [31:0] m_cast_fu_930_p1;
wire   [31:0] tmp_15_fu_933_p2;
wire   [31:0] tmp_17_fu_938_p2;
wire   [31:0] tmp_18_fu_948_p2;
wire   [63:0] m_fu_927_p1;
wire   [63:0] tmp_19_fu_953_p1;
wire   [63:0] tmp_17_cast_fu_944_p1;
wire   [63:0] tmp_20_fu_957_p2;
wire   [63:0] tmp_21_fu_970_p1;
wire   [63:0] m_1_fu_963_p3;
wire   [63:0] m_2_fu_973_p2;
wire   [0:0] tmp_477_fu_989_p3;
wire   [10:0] tmp_263_fu_1005_p2;
wire   [10:0] tmp_264_cast_cast_fu_997_p3;
wire   [51:0] tmp_404_fu_1016_p4;
wire   [31:0] m_5_cast_fu_1035_p1;
wire   [31:0] tmp_35_fu_1038_p2;
wire   [31:0] tmp_37_fu_1043_p2;
wire   [31:0] tmp_38_fu_1053_p2;
wire   [63:0] m_5_fu_1032_p1;
wire   [63:0] tmp_39_fu_1058_p1;
wire   [63:0] tmp_37_cast_fu_1049_p1;
wire   [63:0] tmp_40_fu_1062_p2;
wire   [63:0] tmp_41_fu_1075_p1;
wire   [63:0] m_6_fu_1068_p3;
wire   [63:0] m_7_fu_1078_p2;
wire   [0:0] tmp_488_fu_1094_p3;
wire   [10:0] tmp_268_fu_1110_p2;
wire   [10:0] tmp_272_cast_cast_fu_1102_p3;
wire   [51:0] tmp_408_fu_1121_p4;
wire   [63:0] m_11_fu_1137_p1;
wire   [11:0] tmp_264_fu_1140_p3;
wire   [63:0] p_Result_14_fu_1146_p5;
wire   [0:0] notlhs_fu_1163_p2;
wire   [0:0] tmp_405_fu_1168_p2;
wire   [0:0] tmp_406_fu_480_p2;
wire   [63:0] m_12_fu_1179_p1;
wire   [11:0] tmp_269_fu_1182_p3;
wire   [63:0] p_Result_17_fu_1188_p5;
wire   [0:0] notlhs7_fu_1205_p2;
wire   [0:0] tmp_409_fu_1210_p2;
wire   [0:0] tmp_410_fu_485_p2;
wire   [0:0] tmp_411_fu_1215_p2;
wire   [0:0] tmp_407_fu_1173_p2;
wire   [0:0] tmp2_fu_1226_p2;
wire   [0:0] tmp1_fu_1221_p2;
reg   [5:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_367;
reg    ap_condition_146;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

LSTM_Top_dcmp_64nbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
LSTM_Top_dcmp_64nbkb_U1(
    .din0(tmp_406_fu_480_p0),
    .din1(64'd4588231271568042361),
    .opcode(5'd4),
    .dout(tmp_406_fu_480_p2)
);

LSTM_Top_dcmp_64nbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
LSTM_Top_dcmp_64nbkb_U2(
    .din0(tmp_410_fu_485_p0),
    .din1(64'd4580557137803003036),
    .opcode(5'd4),
    .dout(tmp_410_fu_485_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_146)) begin
        if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd0) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_0_V_read;
        end else if ((1'b1 == ap_condition_367)) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_27_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd26) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_26_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd25) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_25_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd24) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_24_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd23) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_23_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd22) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_22_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd21) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_21_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd20) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_20_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd19) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_19_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd18) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_18_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd17) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_17_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd16) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_16_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd15) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_15_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd14) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_14_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd13) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_13_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd12) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_12_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd11) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_11_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd10) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_10_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd9) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_9_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd8) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_8_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd7) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_7_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd6) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_6_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd5) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_5_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd4) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_4_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd3) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_3_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd2) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_2_V_read;
        end else if (((ap_phi_mux_i_phi_fu_411_p4 == 5'd1) & (exitcond_fu_490_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= x_t_1_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 <= ap_phi_reg_pp0_iter0_p_Val2_2_reg_419;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_reg_1377 == 1'd0))) begin
        i_reg_407 <= i_1_reg_1381;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_407 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_reg_1377 == 1'd0))) begin
        tmp_V_6_reg_383 <= diff_sum_V_fu_533_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_V_6_reg_383 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_reg_1377 == 1'd0))) begin
        tmp_V_7_reg_395 <= energy_V_fu_561_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_V_7_reg_395 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond_reg_1377 <= exitcond_fu_490_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_1_reg_1381 <= i_1_fu_496_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        l_1_reg_1447 <= l_1_fu_673_p3;
        l_reg_1419 <= l_fu_615_p3;
        p_Result_12_reg_1406 <= tmp_V_7_reg_395[32'd15];
        p_Result_15_reg_1434 <= tmp_V_6_reg_383[32'd15];
        tmp_24_reg_1429 <= tmp_24_fu_627_p2;
        tmp_478_reg_1424 <= tmp_478_fu_623_p1;
        tmp_489_reg_1452 <= tmp_489_fu_681_p1;
        tmp_V_8_reg_1411 <= tmp_V_8_fu_589_p3;
        tmp_V_9_reg_1439 <= tmp_V_9_fu_647_p3;
        tmp_reg_1401 <= tmp_fu_569_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        m_3_reg_1505 <= {{m_7_fu_1078_p2[63:1]}};
        m_s_reg_1489 <= {{m_2_fu_973_p2[63:1]}};
        notrhs8_reg_1516 <= notrhs8_fu_1131_p2;
        notrhs_reg_1500 <= notrhs_fu_1026_p2;
        p_Repl2_2_trunc_reg_1494 <= p_Repl2_2_trunc_fu_1010_p2;
        p_Repl2_5_trunc_reg_1510 <= p_Repl2_5_trunc_fu_1115_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_13_reg_1463[0] <= tmp_13_fu_792_p3[0];
        tmp_14_reg_1468 <= tmp_14_fu_800_p2;
        tmp_1_reg_1457 <= tmp_1_fu_685_p2;
        tmp_25_reg_1473 <= tmp_25_fu_806_p2;
        tmp_33_reg_1479[0] <= tmp_33_fu_913_p3[0];
        tmp_34_reg_1484 <= tmp_34_fu_921_p2;
    end
end

always @ (*) begin
    if ((exitcond_fu_490_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_reg_1377 == 1'd0))) begin
        ap_phi_mux_i_phi_fu_411_p4 = i_1_reg_1381;
    end else begin
        ap_phi_mux_i_phi_fu_411_p4 = i_reg_407;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_prev_V_ce0 = 1'b1;
    end else begin
        x_prev_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_fu_490_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_fu_490_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_1_fu_868_p2 = (tmp_28_fu_862_p2 & icmp1_fu_831_p2);

assign a_fu_747_p2 = (tmp_4_fu_741_p2 & icmp_fu_710_p2);

assign addconv1_fu_521_p2 = (tmp_V_6_reg_383 + delta_V_fu_507_p2);

assign addconv_fu_549_p2 = (ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 + tmp_V_7_reg_395);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_146 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_367 = ((((((ap_phi_mux_i_phi_fu_411_p4 == 5'd30) & (exitcond_fu_490_p2 == 1'd0)) | ((ap_phi_mux_i_phi_fu_411_p4 == 5'd31) & (exitcond_fu_490_p2 == 1'd0))) | ((ap_phi_mux_i_phi_fu_411_p4 == 5'd29) & (exitcond_fu_490_p2 == 1'd0))) | ((ap_phi_mux_i_phi_fu_411_p4 == 5'd28) & (exitcond_fu_490_p2 == 1'd0))) | ((ap_phi_mux_i_phi_fu_411_p4 == 5'd27) & (exitcond_fu_490_p2 == 1'd0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_p_Val2_2_reg_419 = 'bx;

assign ap_return = (tmp2_fu_1226_p2 | tmp1_fu_1221_p2);

assign delta_V_fu_507_p2 = (ap_phi_reg_pp0_iter1_p_Val2_2_reg_419 - x_prev_V_q0);

assign diff_sum_V_fu_533_p3 = ((tmp_490_fu_513_p3[0:0] === 1'b1) ? tmp_7_fu_527_p2 : addconv1_fu_521_p2);

assign energy_V_fu_561_p3 = ((tmp_491_fu_541_p3[0:0] === 1'b1) ? tmp_9_fu_555_p2 : addconv_fu_549_p2);

assign exitcond_fu_490_p2 = ((ap_phi_mux_i_phi_fu_411_p4 == 5'd28) ? 1'b1 : 1'b0);

assign i_1_fu_496_p2 = (ap_phi_mux_i_phi_fu_411_p4 + 5'd1);

assign icmp1_fu_831_p2 = (($signed(tmp_481_fu_821_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_fu_710_p2 = (($signed(tmp_470_fu_700_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);


always @ (p_Result_16_fu_665_p3) begin
    if (p_Result_16_fu_665_p3[0] == 1'b1) begin
        l_1_fu_673_p3 = 32'd0;
    end else if (p_Result_16_fu_665_p3[1] == 1'b1) begin
        l_1_fu_673_p3 = 32'd1;
    end else if (p_Result_16_fu_665_p3[2] == 1'b1) begin
        l_1_fu_673_p3 = 32'd2;
    end else if (p_Result_16_fu_665_p3[3] == 1'b1) begin
        l_1_fu_673_p3 = 32'd3;
    end else if (p_Result_16_fu_665_p3[4] == 1'b1) begin
        l_1_fu_673_p3 = 32'd4;
    end else if (p_Result_16_fu_665_p3[5] == 1'b1) begin
        l_1_fu_673_p3 = 32'd5;
    end else if (p_Result_16_fu_665_p3[6] == 1'b1) begin
        l_1_fu_673_p3 = 32'd6;
    end else if (p_Result_16_fu_665_p3[7] == 1'b1) begin
        l_1_fu_673_p3 = 32'd7;
    end else if (p_Result_16_fu_665_p3[8] == 1'b1) begin
        l_1_fu_673_p3 = 32'd8;
    end else if (p_Result_16_fu_665_p3[9] == 1'b1) begin
        l_1_fu_673_p3 = 32'd9;
    end else if (p_Result_16_fu_665_p3[10] == 1'b1) begin
        l_1_fu_673_p3 = 32'd10;
    end else if (p_Result_16_fu_665_p3[11] == 1'b1) begin
        l_1_fu_673_p3 = 32'd11;
    end else if (p_Result_16_fu_665_p3[12] == 1'b1) begin
        l_1_fu_673_p3 = 32'd12;
    end else if (p_Result_16_fu_665_p3[13] == 1'b1) begin
        l_1_fu_673_p3 = 32'd13;
    end else if (p_Result_16_fu_665_p3[14] == 1'b1) begin
        l_1_fu_673_p3 = 32'd14;
    end else if (p_Result_16_fu_665_p3[15] == 1'b1) begin
        l_1_fu_673_p3 = 32'd15;
    end else if (p_Result_16_fu_665_p3[16] == 1'b1) begin
        l_1_fu_673_p3 = 32'd16;
    end else if (p_Result_16_fu_665_p3[17] == 1'b1) begin
        l_1_fu_673_p3 = 32'd17;
    end else if (p_Result_16_fu_665_p3[18] == 1'b1) begin
        l_1_fu_673_p3 = 32'd18;
    end else if (p_Result_16_fu_665_p3[19] == 1'b1) begin
        l_1_fu_673_p3 = 32'd19;
    end else if (p_Result_16_fu_665_p3[20] == 1'b1) begin
        l_1_fu_673_p3 = 32'd20;
    end else if (p_Result_16_fu_665_p3[21] == 1'b1) begin
        l_1_fu_673_p3 = 32'd21;
    end else if (p_Result_16_fu_665_p3[22] == 1'b1) begin
        l_1_fu_673_p3 = 32'd22;
    end else if (p_Result_16_fu_665_p3[23] == 1'b1) begin
        l_1_fu_673_p3 = 32'd23;
    end else if (p_Result_16_fu_665_p3[24] == 1'b1) begin
        l_1_fu_673_p3 = 32'd24;
    end else if (p_Result_16_fu_665_p3[25] == 1'b1) begin
        l_1_fu_673_p3 = 32'd25;
    end else if (p_Result_16_fu_665_p3[26] == 1'b1) begin
        l_1_fu_673_p3 = 32'd26;
    end else if (p_Result_16_fu_665_p3[27] == 1'b1) begin
        l_1_fu_673_p3 = 32'd27;
    end else if (p_Result_16_fu_665_p3[28] == 1'b1) begin
        l_1_fu_673_p3 = 32'd28;
    end else if (p_Result_16_fu_665_p3[29] == 1'b1) begin
        l_1_fu_673_p3 = 32'd29;
    end else if (p_Result_16_fu_665_p3[30] == 1'b1) begin
        l_1_fu_673_p3 = 32'd30;
    end else if (p_Result_16_fu_665_p3[31] == 1'b1) begin
        l_1_fu_673_p3 = 32'd31;
    end else begin
        l_1_fu_673_p3 = 32'd32;
    end
end


always @ (p_Result_13_fu_607_p3) begin
    if (p_Result_13_fu_607_p3[0] == 1'b1) begin
        l_fu_615_p3 = 32'd0;
    end else if (p_Result_13_fu_607_p3[1] == 1'b1) begin
        l_fu_615_p3 = 32'd1;
    end else if (p_Result_13_fu_607_p3[2] == 1'b1) begin
        l_fu_615_p3 = 32'd2;
    end else if (p_Result_13_fu_607_p3[3] == 1'b1) begin
        l_fu_615_p3 = 32'd3;
    end else if (p_Result_13_fu_607_p3[4] == 1'b1) begin
        l_fu_615_p3 = 32'd4;
    end else if (p_Result_13_fu_607_p3[5] == 1'b1) begin
        l_fu_615_p3 = 32'd5;
    end else if (p_Result_13_fu_607_p3[6] == 1'b1) begin
        l_fu_615_p3 = 32'd6;
    end else if (p_Result_13_fu_607_p3[7] == 1'b1) begin
        l_fu_615_p3 = 32'd7;
    end else if (p_Result_13_fu_607_p3[8] == 1'b1) begin
        l_fu_615_p3 = 32'd8;
    end else if (p_Result_13_fu_607_p3[9] == 1'b1) begin
        l_fu_615_p3 = 32'd9;
    end else if (p_Result_13_fu_607_p3[10] == 1'b1) begin
        l_fu_615_p3 = 32'd10;
    end else if (p_Result_13_fu_607_p3[11] == 1'b1) begin
        l_fu_615_p3 = 32'd11;
    end else if (p_Result_13_fu_607_p3[12] == 1'b1) begin
        l_fu_615_p3 = 32'd12;
    end else if (p_Result_13_fu_607_p3[13] == 1'b1) begin
        l_fu_615_p3 = 32'd13;
    end else if (p_Result_13_fu_607_p3[14] == 1'b1) begin
        l_fu_615_p3 = 32'd14;
    end else if (p_Result_13_fu_607_p3[15] == 1'b1) begin
        l_fu_615_p3 = 32'd15;
    end else if (p_Result_13_fu_607_p3[16] == 1'b1) begin
        l_fu_615_p3 = 32'd16;
    end else if (p_Result_13_fu_607_p3[17] == 1'b1) begin
        l_fu_615_p3 = 32'd17;
    end else if (p_Result_13_fu_607_p3[18] == 1'b1) begin
        l_fu_615_p3 = 32'd18;
    end else if (p_Result_13_fu_607_p3[19] == 1'b1) begin
        l_fu_615_p3 = 32'd19;
    end else if (p_Result_13_fu_607_p3[20] == 1'b1) begin
        l_fu_615_p3 = 32'd20;
    end else if (p_Result_13_fu_607_p3[21] == 1'b1) begin
        l_fu_615_p3 = 32'd21;
    end else if (p_Result_13_fu_607_p3[22] == 1'b1) begin
        l_fu_615_p3 = 32'd22;
    end else if (p_Result_13_fu_607_p3[23] == 1'b1) begin
        l_fu_615_p3 = 32'd23;
    end else if (p_Result_13_fu_607_p3[24] == 1'b1) begin
        l_fu_615_p3 = 32'd24;
    end else if (p_Result_13_fu_607_p3[25] == 1'b1) begin
        l_fu_615_p3 = 32'd25;
    end else if (p_Result_13_fu_607_p3[26] == 1'b1) begin
        l_fu_615_p3 = 32'd26;
    end else if (p_Result_13_fu_607_p3[27] == 1'b1) begin
        l_fu_615_p3 = 32'd27;
    end else if (p_Result_13_fu_607_p3[28] == 1'b1) begin
        l_fu_615_p3 = 32'd28;
    end else if (p_Result_13_fu_607_p3[29] == 1'b1) begin
        l_fu_615_p3 = 32'd29;
    end else if (p_Result_13_fu_607_p3[30] == 1'b1) begin
        l_fu_615_p3 = 32'd30;
    end else if (p_Result_13_fu_607_p3[31] == 1'b1) begin
        l_fu_615_p3 = 32'd31;
    end else begin
        l_fu_615_p3 = 32'd32;
    end
end

assign lsb_index_1_fu_815_p2 = ($signed(32'd4294967243) + $signed(tmp_25_fu_806_p2));

assign lsb_index_fu_694_p2 = ($signed(32'd4294967243) + $signed(tmp_1_fu_685_p2));

assign m_11_fu_1137_p1 = m_s_reg_1489;

assign m_12_fu_1179_p1 = m_3_reg_1505;

assign m_1_fu_963_p3 = ((tmp_14_reg_1468[0:0] === 1'b1) ? tmp_17_cast_fu_944_p1 : tmp_20_fu_957_p2);

assign m_2_fu_973_p2 = (tmp_21_fu_970_p1 + m_1_fu_963_p3);

assign m_5_cast_fu_1035_p1 = tmp_V_9_reg_1439;

assign m_5_fu_1032_p1 = tmp_V_9_reg_1439;

assign m_6_fu_1068_p3 = ((tmp_34_reg_1484[0:0] === 1'b1) ? tmp_37_cast_fu_1049_p1 : tmp_40_fu_1062_p2);

assign m_7_fu_1078_p2 = (tmp_41_fu_1075_p1 + m_6_fu_1068_p3);

assign m_cast_fu_930_p1 = tmp_V_8_reg_1411;

assign m_fu_927_p1 = tmp_V_8_reg_1411;

assign notlhs7_fu_1205_p2 = ((p_Repl2_5_trunc_reg_1510 != 11'd2047) ? 1'b1 : 1'b0);

assign notlhs_fu_1163_p2 = ((p_Repl2_2_trunc_reg_1494 != 11'd2047) ? 1'b1 : 1'b0);

assign notrhs8_fu_1131_p2 = ((tmp_408_fu_1121_p4 == 52'd0) ? 1'b1 : 1'b0);

assign notrhs_fu_1026_p2 = ((tmp_404_fu_1016_p4 == 52'd0) ? 1'b1 : 1'b0);

assign p_Repl2_2_trunc_fu_1010_p2 = (tmp_263_fu_1005_p2 + tmp_264_cast_cast_fu_997_p3);

assign p_Repl2_5_trunc_fu_1115_p2 = (tmp_268_fu_1110_p2 + tmp_272_cast_cast_fu_1102_p3);

assign p_Result_10_fu_894_p3 = tmp_V_9_reg_1439[tmp_30_fu_888_p2];

assign p_Result_12_fu_575_p3 = tmp_V_7_reg_395[32'd15];

assign p_Result_13_fu_607_p3 = {{16'd65535}, {p_Result_s_fu_597_p4}};

assign p_Result_14_fu_1146_p5 = {{tmp_264_fu_1140_p3}, {m_11_fu_1137_p1[51:0]}};

assign p_Result_15_fu_633_p3 = tmp_V_6_reg_383[32'd15];

assign p_Result_16_fu_665_p3 = {{16'd65535}, {p_Result_7_fu_655_p4}};

assign p_Result_17_fu_1188_p5 = {{tmp_269_fu_1182_p3}, {m_12_fu_1179_p1[51:0]}};

assign p_Result_3_fu_736_p2 = (tmp_V_8_reg_1411 & tmp_474_fu_730_p2);

assign p_Result_4_fu_773_p3 = tmp_V_8_reg_1411[tmp_10_fu_767_p2];

integer ap_tvar_int_0;

always @ (tmp_V_9_fu_647_p3) begin
    for (ap_tvar_int_0 = 16 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 15 - 0) begin
            p_Result_7_fu_655_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_7_fu_655_p4[ap_tvar_int_0] = tmp_V_9_fu_647_p3[15 - ap_tvar_int_0];
        end
    end
end

assign p_Result_9_fu_857_p2 = (tmp_V_9_reg_1439 & tmp_485_fu_851_p2);

integer ap_tvar_int_1;

always @ (tmp_V_8_fu_589_p3) begin
    for (ap_tvar_int_1 = 16 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 15 - 0) begin
            p_Result_s_fu_597_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            p_Result_s_fu_597_p4[ap_tvar_int_1] = tmp_V_8_fu_589_p3[15 - ap_tvar_int_1];
        end
    end
end

assign rev1_fu_882_p2 = (tmp_487_fu_874_p3 ^ 1'd1);

assign rev_fu_761_p2 = (tmp_476_fu_753_p3 ^ 1'd1);

assign tmp1_fu_1221_p2 = (tmp_411_fu_1215_p2 | tmp_24_reg_1429);

assign tmp2_fu_1226_p2 = (tmp_reg_1401 | tmp_407_fu_1173_p2);

assign tmp_10_fu_767_p2 = ($signed(16'd65483) + $signed(tmp_469_fu_690_p1));

assign tmp_12_fu_780_p2 = (rev_fu_761_p2 & p_Result_4_fu_773_p3);

assign tmp_13_fu_792_p3 = {{31'd0}, {tmp_261_fu_786_p2}};

assign tmp_14_fu_800_p2 = (($signed(lsb_index_fu_694_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_15_fu_933_p2 = ($signed(32'd4294967242) + $signed(tmp_1_reg_1457));

assign tmp_17_cast_fu_944_p1 = tmp_17_fu_938_p2;

assign tmp_17_fu_938_p2 = m_cast_fu_930_p1 >> tmp_15_fu_933_p2;

assign tmp_18_fu_948_p2 = (32'd54 - tmp_1_reg_1457);

assign tmp_19_fu_953_p1 = tmp_18_fu_948_p2;

assign tmp_1_fu_685_p2 = (32'd16 - l_reg_1419);

assign tmp_20_fu_957_p2 = m_fu_927_p1 << tmp_19_fu_953_p1;

assign tmp_21_fu_970_p1 = tmp_13_reg_1463;

assign tmp_24_fu_627_p2 = ((tmp_V_6_reg_383 == 16'd0) ? 1'b1 : 1'b0);

assign tmp_25_fu_806_p2 = (32'd16 - l_1_reg_1447);

assign tmp_261_fu_786_p2 = (tmp_12_fu_780_p2 | a_fu_747_p2);

assign tmp_263_fu_1005_p2 = (11'd5 - tmp_478_reg_1424);

assign tmp_264_cast_cast_fu_997_p3 = ((tmp_477_fu_989_p3[0:0] === 1'b1) ? 11'd1023 : 11'd1022);

assign tmp_264_fu_1140_p3 = {{p_Result_12_reg_1406}, {p_Repl2_2_trunc_reg_1494}};

assign tmp_266_fu_907_p2 = (tmp_32_fu_901_p2 | a_1_fu_868_p2);

assign tmp_268_fu_1110_p2 = (11'd5 - tmp_489_reg_1452);

assign tmp_269_fu_1182_p3 = {{p_Result_15_reg_1434}, {p_Repl2_5_trunc_reg_1510}};

assign tmp_272_cast_cast_fu_1102_p3 = ((tmp_488_fu_1094_p3[0:0] === 1'b1) ? 11'd1023 : 11'd1022);

assign tmp_28_fu_862_p2 = ((p_Result_9_fu_857_p2 != 16'd0) ? 1'b1 : 1'b0);

assign tmp_30_fu_888_p2 = ($signed(16'd65483) + $signed(tmp_480_fu_811_p1));

assign tmp_32_fu_901_p2 = (rev1_fu_882_p2 & p_Result_10_fu_894_p3);

assign tmp_33_fu_913_p3 = {{31'd0}, {tmp_266_fu_907_p2}};

assign tmp_34_fu_921_p2 = (($signed(lsb_index_1_fu_815_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_35_fu_1038_p2 = ($signed(32'd4294967242) + $signed(tmp_25_reg_1473));

assign tmp_37_cast_fu_1049_p1 = tmp_37_fu_1043_p2;

assign tmp_37_fu_1043_p2 = m_5_cast_fu_1035_p1 >> tmp_35_fu_1038_p2;

assign tmp_38_fu_1053_p2 = (32'd54 - tmp_25_reg_1473);

assign tmp_39_fu_1058_p1 = tmp_38_fu_1053_p2;

assign tmp_404_fu_1016_p4 = {{m_2_fu_973_p2[52:1]}};

assign tmp_405_fu_1168_p2 = (notrhs_reg_1500 | notlhs_fu_1163_p2);

assign tmp_406_fu_480_p0 = p_Result_14_fu_1146_p5;

assign tmp_407_fu_1173_p2 = (tmp_406_fu_480_p2 & tmp_405_fu_1168_p2);

assign tmp_408_fu_1121_p4 = {{m_7_fu_1078_p2[52:1]}};

assign tmp_409_fu_1210_p2 = (notrhs8_reg_1516 | notlhs7_fu_1205_p2);

assign tmp_40_fu_1062_p2 = m_5_fu_1032_p1 << tmp_39_fu_1058_p1;

assign tmp_410_fu_485_p0 = p_Result_17_fu_1188_p5;

assign tmp_411_fu_1215_p2 = (tmp_410_fu_485_p2 & tmp_409_fu_1210_p2);

assign tmp_41_fu_1075_p1 = tmp_33_reg_1479;

assign tmp_469_fu_690_p1 = tmp_1_fu_685_p2[15:0];

assign tmp_470_fu_700_p4 = {{lsb_index_fu_694_p2[31:1]}};

assign tmp_471_fu_716_p1 = tmp_1_fu_685_p2[4:0];

assign tmp_472_fu_720_p2 = (5'd6 - tmp_471_fu_716_p1);

assign tmp_473_fu_726_p1 = tmp_472_fu_720_p2;

assign tmp_474_fu_730_p2 = 16'd65535 >> tmp_473_fu_726_p1;

assign tmp_476_fu_753_p3 = lsb_index_fu_694_p2[32'd31];

assign tmp_477_fu_989_p3 = m_2_fu_973_p2[32'd54];

assign tmp_478_fu_623_p1 = l_fu_615_p3[10:0];

assign tmp_480_fu_811_p1 = tmp_25_fu_806_p2[15:0];

assign tmp_481_fu_821_p4 = {{lsb_index_1_fu_815_p2[31:1]}};

assign tmp_482_fu_837_p1 = tmp_25_fu_806_p2[4:0];

assign tmp_483_fu_841_p2 = (5'd6 - tmp_482_fu_837_p1);

assign tmp_484_fu_847_p1 = tmp_483_fu_841_p2;

assign tmp_485_fu_851_p2 = 16'd65535 >> tmp_484_fu_847_p1;

assign tmp_487_fu_874_p3 = lsb_index_1_fu_815_p2[32'd31];

assign tmp_488_fu_1094_p3 = m_7_fu_1078_p2[32'd54];

assign tmp_489_fu_681_p1 = l_1_fu_673_p3[10:0];

assign tmp_490_fu_513_p3 = delta_V_fu_507_p2[32'd15];

assign tmp_491_fu_541_p3 = ap_phi_reg_pp0_iter1_p_Val2_2_reg_419[32'd15];

assign tmp_4_fu_741_p2 = ((p_Result_3_fu_736_p2 != 16'd0) ? 1'b1 : 1'b0);

assign tmp_7_fu_527_p2 = (tmp_V_6_reg_383 - delta_V_fu_507_p2);

assign tmp_9_fu_555_p2 = (tmp_V_7_reg_395 - ap_phi_reg_pp0_iter1_p_Val2_2_reg_419);

assign tmp_V_2_fu_641_p2 = (16'd0 - tmp_V_6_reg_383);

assign tmp_V_8_fu_589_p3 = ((p_Result_12_fu_575_p3[0:0] === 1'b1) ? tmp_V_fu_583_p2 : tmp_V_7_reg_395);

assign tmp_V_9_fu_647_p3 = ((p_Result_15_fu_633_p3[0:0] === 1'b1) ? tmp_V_2_fu_641_p2 : tmp_V_6_reg_383);

assign tmp_V_fu_583_p2 = (16'd0 - tmp_V_7_reg_395);

assign tmp_fu_569_p2 = ((tmp_V_7_reg_395 == 16'd0) ? 1'b1 : 1'b0);

assign tmp_s_fu_502_p1 = ap_phi_mux_i_phi_fu_411_p4;

assign x_prev_V_address0 = tmp_s_fu_502_p1;

always @ (posedge ap_clk) begin
    tmp_13_reg_1463[31:1] <= 31'b0000000000000000000000000000000;
    tmp_33_reg_1479[31:1] <= 31'b0000000000000000000000000000000;
end

endmodule //should_skip
