// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="BiLSTM_Top,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=9.760500,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=236,HLS_SYN_DSP=510,HLS_SYN_FF=17975,HLS_SYN_LUT=25914,HLS_VERSION=2018_3}" *)

module BiLSTM_Top (
        ap_clk,
        ap_rst_n,
        input_stream_TDATA,
        input_stream_TKEEP,
        input_stream_TSTRB,
        input_stream_TUSER,
        input_stream_TLAST,
        input_stream_TID,
        input_stream_TDEST,
        output_stream_TDATA,
        output_stream_TKEEP,
        output_stream_TSTRB,
        output_stream_TUSER,
        output_stream_TLAST,
        output_stream_TID,
        output_stream_TDEST,
        input_stream_TVALID,
        input_stream_TREADY,
        output_stream_TVALID,
        output_stream_TREADY
);


input   ap_clk;
input   ap_rst_n;
input  [31:0] input_stream_TDATA;
input  [3:0] input_stream_TKEEP;
input  [3:0] input_stream_TSTRB;
input  [0:0] input_stream_TUSER;
input  [0:0] input_stream_TLAST;
input  [0:0] input_stream_TID;
input  [0:0] input_stream_TDEST;
output  [31:0] output_stream_TDATA;
output  [3:0] output_stream_TKEEP;
output  [3:0] output_stream_TSTRB;
output  [0:0] output_stream_TUSER;
output  [0:0] output_stream_TLAST;
output  [0:0] output_stream_TID;
output  [0:0] output_stream_TDEST;
input   input_stream_TVALID;
output   input_stream_TREADY;
output   output_stream_TVALID;
input   output_stream_TREADY;

 reg    ap_rst_n_inv;
wire   [31:0] input_ping_i_q0;
wire   [31:0] input_ping_t_q0;
wire    Block_proc_U0_ap_start;
wire    Block_proc_U0_ap_done;
wire    Block_proc_U0_ap_continue;
wire    Block_proc_U0_ap_idle;
wire    Block_proc_U0_ap_ready;
wire    Block_proc_U0_input_stream_TREADY;
wire   [11:0] Block_proc_U0_input_ping_address0;
wire    Block_proc_U0_input_ping_ce0;
wire    Block_proc_U0_input_ping_we0;
wire   [31:0] Block_proc_U0_input_ping_d0;
wire   [6:0] Block_proc_U0_ap_return;
wire    ap_channel_done_data_lens_load_loc_c;
wire    data_lens_load_loc_c_full_n;
reg    ap_sync_reg_channel_write_data_lens_load_loc_c;
wire    ap_sync_channel_write_data_lens_load_loc_c;
wire    ap_channel_done_input_ping;
wire    Block_proc_U0_input_ping_full_n;
reg    ap_sync_reg_channel_write_input_ping;
wire    ap_sync_channel_write_input_ping;
wire   [11:0] lstm_infer_U0_input_r_address0;
wire    lstm_infer_U0_input_r_ce0;
wire   [31:0] lstm_infer_U0_input_r_d0;
wire    lstm_infer_U0_input_r_we0;
wire   [11:0] lstm_infer_U0_input_r_address1;
wire    lstm_infer_U0_input_r_ce1;
wire   [31:0] lstm_infer_U0_input_r_d1;
wire    lstm_infer_U0_input_r_we1;
wire   [31:0] lstm_infer_U0_ress_0;
wire   [31:0] lstm_infer_U0_ress_1;
wire   [31:0] lstm_infer_U0_ress_2;
wire   [31:0] lstm_infer_U0_ress_3;
wire   [31:0] lstm_infer_U0_ress_4;
wire   [31:0] lstm_infer_U0_ress_5;
wire   [31:0] lstm_infer_U0_ress_6;
wire   [31:0] lstm_infer_U0_ress_7;
wire   [31:0] lstm_infer_U0_ress_8;
wire   [31:0] lstm_infer_U0_ress_9;
wire    lstm_infer_U0_input_r_read;
wire    lstm_infer_U0_ap_start;
wire    lstm_infer_U0_ress_0_ap_vld;
wire    lstm_infer_U0_ress_1_ap_vld;
wire    lstm_infer_U0_ress_2_ap_vld;
wire    lstm_infer_U0_ress_3_ap_vld;
wire    lstm_infer_U0_ress_4_ap_vld;
wire    lstm_infer_U0_ress_5_ap_vld;
wire    lstm_infer_U0_ress_6_ap_vld;
wire    lstm_infer_U0_ress_7_ap_vld;
wire    lstm_infer_U0_ress_8_ap_vld;
wire    lstm_infer_U0_ress_9_ap_vld;
wire    lstm_infer_U0_ap_done;
wire    lstm_infer_U0_ap_ready;
wire    lstm_infer_U0_ap_idle;
wire    lstm_infer_U0_ap_continue;
wire    ap_channel_done_res_9;
wire    res_9_full_n;
reg    ap_sync_reg_channel_write_res_9;
wire    ap_sync_channel_write_res_9;
wire    ap_channel_done_res_8;
wire    res_8_full_n;
reg    ap_sync_reg_channel_write_res_8;
wire    ap_sync_channel_write_res_8;
wire    ap_channel_done_res_7;
wire    res_7_full_n;
reg    ap_sync_reg_channel_write_res_7;
wire    ap_sync_channel_write_res_7;
wire    ap_channel_done_res_6;
wire    res_6_full_n;
reg    ap_sync_reg_channel_write_res_6;
wire    ap_sync_channel_write_res_6;
wire    ap_channel_done_res_5;
wire    res_5_full_n;
reg    ap_sync_reg_channel_write_res_5;
wire    ap_sync_channel_write_res_5;
wire    ap_channel_done_res_4;
wire    res_4_full_n;
reg    ap_sync_reg_channel_write_res_4;
wire    ap_sync_channel_write_res_4;
wire    ap_channel_done_res_3;
wire    res_3_full_n;
reg    ap_sync_reg_channel_write_res_3;
wire    ap_sync_channel_write_res_3;
wire    ap_channel_done_res_2;
wire    res_2_full_n;
reg    ap_sync_reg_channel_write_res_2;
wire    ap_sync_channel_write_res_2;
wire    ap_channel_done_res_1;
wire    res_1_full_n;
reg    ap_sync_reg_channel_write_res_1;
wire    ap_sync_channel_write_res_1;
wire    ap_channel_done_res_0;
wire    res_0_full_n;
reg    ap_sync_reg_channel_write_res_0;
wire    ap_sync_channel_write_res_0;
wire    write_output_U0_ap_start;
wire    write_output_U0_ap_done;
wire    write_output_U0_ap_continue;
wire    write_output_U0_ap_idle;
wire    write_output_U0_ap_ready;
wire   [31:0] write_output_U0_output_stream_TDATA;
wire    write_output_U0_output_stream_TVALID;
wire   [3:0] write_output_U0_output_stream_TKEEP;
wire   [3:0] write_output_U0_output_stream_TSTRB;
wire   [0:0] write_output_U0_output_stream_TUSER;
wire   [0:0] write_output_U0_output_stream_TLAST;
wire   [0:0] write_output_U0_output_stream_TID;
wire   [0:0] write_output_U0_output_stream_TDEST;
wire    ap_sync_continue;
wire    input_ping_i_full_n;
wire    input_ping_t_empty_n;
wire   [6:0] data_lens_load_loc_c_dout;
wire    data_lens_load_loc_c_empty_n;
wire   [31:0] res_0_dout;
wire    res_0_empty_n;
wire   [31:0] res_1_dout;
wire    res_1_empty_n;
wire   [31:0] res_2_dout;
wire    res_2_empty_n;
wire   [31:0] res_3_dout;
wire    res_3_empty_n;
wire   [31:0] res_4_dout;
wire    res_4_empty_n;
wire   [31:0] res_5_dout;
wire    res_5_empty_n;
wire   [31:0] res_6_dout;
wire    res_6_empty_n;
wire   [31:0] res_7_dout;
wire    res_7_empty_n;
wire   [31:0] res_8_dout;
wire    res_8_empty_n;
wire   [31:0] res_9_dout;
wire    res_9_empty_n;
wire    Block_proc_U0_start_full_n;
wire    Block_proc_U0_start_write;
wire    lstm_infer_U0_start_full_n;
wire    lstm_infer_U0_start_write;
wire    write_output_U0_start_full_n;
wire    write_output_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_data_lens_load_loc_c = 1'b0;
#0 ap_sync_reg_channel_write_input_ping = 1'b0;
#0 ap_sync_reg_channel_write_res_9 = 1'b0;
#0 ap_sync_reg_channel_write_res_8 = 1'b0;
#0 ap_sync_reg_channel_write_res_7 = 1'b0;
#0 ap_sync_reg_channel_write_res_6 = 1'b0;
#0 ap_sync_reg_channel_write_res_5 = 1'b0;
#0 ap_sync_reg_channel_write_res_4 = 1'b0;
#0 ap_sync_reg_channel_write_res_3 = 1'b0;
#0 ap_sync_reg_channel_write_res_2 = 1'b0;
#0 ap_sync_reg_channel_write_res_1 = 1'b0;
#0 ap_sync_reg_channel_write_res_0 = 1'b0;
end

BiLSTM_Top_input_cKz #(
    .DataWidth( 32 ),
    .AddressRange( 3900 ),
    .AddressWidth( 12 ))
input_ping_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Block_proc_U0_input_ping_address0),
    .i_ce0(Block_proc_U0_input_ping_ce0),
    .i_we0(Block_proc_U0_input_ping_we0),
    .i_d0(Block_proc_U0_input_ping_d0),
    .i_q0(input_ping_i_q0),
    .t_address0(lstm_infer_U0_input_r_address0),
    .t_ce0(lstm_infer_U0_input_r_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(input_ping_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(input_ping_i_full_n),
    .i_write(ap_channel_done_input_ping),
    .t_empty_n(input_ping_t_empty_n),
    .t_read(lstm_infer_U0_ap_ready)
);

Block_proc Block_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_proc_U0_ap_start),
    .ap_done(Block_proc_U0_ap_done),
    .ap_continue(Block_proc_U0_ap_continue),
    .ap_idle(Block_proc_U0_ap_idle),
    .ap_ready(Block_proc_U0_ap_ready),
    .input_stream_TDATA(input_stream_TDATA),
    .input_stream_TVALID(input_stream_TVALID),
    .input_stream_TREADY(Block_proc_U0_input_stream_TREADY),
    .input_stream_TKEEP(input_stream_TKEEP),
    .input_stream_TSTRB(input_stream_TSTRB),
    .input_stream_TUSER(input_stream_TUSER),
    .input_stream_TLAST(input_stream_TLAST),
    .input_stream_TID(input_stream_TID),
    .input_stream_TDEST(input_stream_TDEST),
    .input_ping_address0(Block_proc_U0_input_ping_address0),
    .input_ping_ce0(Block_proc_U0_input_ping_ce0),
    .input_ping_we0(Block_proc_U0_input_ping_we0),
    .input_ping_d0(Block_proc_U0_input_ping_d0),
    .ap_return(Block_proc_U0_ap_return)
);

lstm_infer lstm_infer_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .input_r_address0(lstm_infer_U0_input_r_address0),
    .input_r_ce0(lstm_infer_U0_input_r_ce0),
    .input_r_d0(lstm_infer_U0_input_r_d0),
    .input_r_q0(input_ping_t_q0),
    .input_r_we0(lstm_infer_U0_input_r_we0),
    .input_r_address1(lstm_infer_U0_input_r_address1),
    .input_r_ce1(lstm_infer_U0_input_r_ce1),
    .input_r_d1(lstm_infer_U0_input_r_d1),
    .input_r_q1(32'd0),
    .input_r_we1(lstm_infer_U0_input_r_we1),
    .p_read(data_lens_load_loc_c_dout),
    .ress_0(lstm_infer_U0_ress_0),
    .ress_1(lstm_infer_U0_ress_1),
    .ress_2(lstm_infer_U0_ress_2),
    .ress_3(lstm_infer_U0_ress_3),
    .ress_4(lstm_infer_U0_ress_4),
    .ress_5(lstm_infer_U0_ress_5),
    .ress_6(lstm_infer_U0_ress_6),
    .ress_7(lstm_infer_U0_ress_7),
    .ress_8(lstm_infer_U0_ress_8),
    .ress_9(lstm_infer_U0_ress_9),
    .p_read_ap_vld(1'b0),
    .input_r_empty_n(1'b0),
    .input_r_read(lstm_infer_U0_input_r_read),
    .ap_start(lstm_infer_U0_ap_start),
    .ress_0_ap_vld(lstm_infer_U0_ress_0_ap_vld),
    .ress_1_ap_vld(lstm_infer_U0_ress_1_ap_vld),
    .ress_2_ap_vld(lstm_infer_U0_ress_2_ap_vld),
    .ress_3_ap_vld(lstm_infer_U0_ress_3_ap_vld),
    .ress_4_ap_vld(lstm_infer_U0_ress_4_ap_vld),
    .ress_5_ap_vld(lstm_infer_U0_ress_5_ap_vld),
    .ress_6_ap_vld(lstm_infer_U0_ress_6_ap_vld),
    .ress_7_ap_vld(lstm_infer_U0_ress_7_ap_vld),
    .ress_8_ap_vld(lstm_infer_U0_ress_8_ap_vld),
    .ress_9_ap_vld(lstm_infer_U0_ress_9_ap_vld),
    .ap_done(lstm_infer_U0_ap_done),
    .ap_ready(lstm_infer_U0_ap_ready),
    .ap_idle(lstm_infer_U0_ap_idle),
    .ap_continue(lstm_infer_U0_ap_continue)
);

write_output write_output_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(write_output_U0_ap_start),
    .ap_done(write_output_U0_ap_done),
    .ap_continue(write_output_U0_ap_continue),
    .ap_idle(write_output_U0_ap_idle),
    .ap_ready(write_output_U0_ap_ready),
    .output_stream_TDATA(write_output_U0_output_stream_TDATA),
    .output_stream_TVALID(write_output_U0_output_stream_TVALID),
    .output_stream_TREADY(output_stream_TREADY),
    .output_stream_TKEEP(write_output_U0_output_stream_TKEEP),
    .output_stream_TSTRB(write_output_U0_output_stream_TSTRB),
    .output_stream_TUSER(write_output_U0_output_stream_TUSER),
    .output_stream_TLAST(write_output_U0_output_stream_TLAST),
    .output_stream_TID(write_output_U0_output_stream_TID),
    .output_stream_TDEST(write_output_U0_output_stream_TDEST),
    .res_0(res_0_dout),
    .res_1(res_1_dout),
    .res_2(res_2_dout),
    .res_3(res_3_dout),
    .res_4(res_4_dout),
    .res_5(res_5_dout),
    .res_6(res_6_dout),
    .res_7(res_7_dout),
    .res_8(res_8_dout),
    .res_9(res_9_dout)
);

fifo_w7_d2_A_x_x data_lens_load_loc_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_ap_return),
    .if_full_n(data_lens_load_loc_c_full_n),
    .if_write(ap_channel_done_data_lens_load_loc_c),
    .if_dout(data_lens_load_loc_c_dout),
    .if_empty_n(data_lens_load_loc_c_empty_n),
    .if_read(lstm_infer_U0_ap_ready)
);

fifo_w32_d2_A res_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(lstm_infer_U0_ress_0),
    .if_full_n(res_0_full_n),
    .if_write(ap_channel_done_res_0),
    .if_dout(res_0_dout),
    .if_empty_n(res_0_empty_n),
    .if_read(write_output_U0_ap_ready)
);

fifo_w32_d2_A res_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(lstm_infer_U0_ress_1),
    .if_full_n(res_1_full_n),
    .if_write(ap_channel_done_res_1),
    .if_dout(res_1_dout),
    .if_empty_n(res_1_empty_n),
    .if_read(write_output_U0_ap_ready)
);

fifo_w32_d2_A res_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(lstm_infer_U0_ress_2),
    .if_full_n(res_2_full_n),
    .if_write(ap_channel_done_res_2),
    .if_dout(res_2_dout),
    .if_empty_n(res_2_empty_n),
    .if_read(write_output_U0_ap_ready)
);

fifo_w32_d2_A res_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(lstm_infer_U0_ress_3),
    .if_full_n(res_3_full_n),
    .if_write(ap_channel_done_res_3),
    .if_dout(res_3_dout),
    .if_empty_n(res_3_empty_n),
    .if_read(write_output_U0_ap_ready)
);

fifo_w32_d2_A res_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(lstm_infer_U0_ress_4),
    .if_full_n(res_4_full_n),
    .if_write(ap_channel_done_res_4),
    .if_dout(res_4_dout),
    .if_empty_n(res_4_empty_n),
    .if_read(write_output_U0_ap_ready)
);

fifo_w32_d2_A res_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(lstm_infer_U0_ress_5),
    .if_full_n(res_5_full_n),
    .if_write(ap_channel_done_res_5),
    .if_dout(res_5_dout),
    .if_empty_n(res_5_empty_n),
    .if_read(write_output_U0_ap_ready)
);

fifo_w32_d2_A res_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(lstm_infer_U0_ress_6),
    .if_full_n(res_6_full_n),
    .if_write(ap_channel_done_res_6),
    .if_dout(res_6_dout),
    .if_empty_n(res_6_empty_n),
    .if_read(write_output_U0_ap_ready)
);

fifo_w32_d2_A res_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(lstm_infer_U0_ress_7),
    .if_full_n(res_7_full_n),
    .if_write(ap_channel_done_res_7),
    .if_dout(res_7_dout),
    .if_empty_n(res_7_empty_n),
    .if_read(write_output_U0_ap_ready)
);

fifo_w32_d2_A res_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(lstm_infer_U0_ress_8),
    .if_full_n(res_8_full_n),
    .if_write(ap_channel_done_res_8),
    .if_dout(res_8_dout),
    .if_empty_n(res_8_empty_n),
    .if_read(write_output_U0_ap_ready)
);

fifo_w32_d2_A res_9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(lstm_infer_U0_ress_9),
    .if_full_n(res_9_full_n),
    .if_write(ap_channel_done_res_9),
    .if_dout(res_9_dout),
    .if_empty_n(res_9_empty_n),
    .if_read(write_output_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_data_lens_load_loc_c <= 1'b0;
    end else begin
        if (((Block_proc_U0_ap_done & Block_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_data_lens_load_loc_c <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_data_lens_load_loc_c <= ap_sync_channel_write_data_lens_load_loc_c;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_input_ping <= 1'b0;
    end else begin
        if (((Block_proc_U0_ap_done & Block_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_input_ping <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_input_ping <= ap_sync_channel_write_input_ping;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_res_0 <= 1'b0;
    end else begin
        if (((lstm_infer_U0_ap_done & lstm_infer_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_res_0 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_res_0 <= ap_sync_channel_write_res_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_res_1 <= 1'b0;
    end else begin
        if (((lstm_infer_U0_ap_done & lstm_infer_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_res_1 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_res_1 <= ap_sync_channel_write_res_1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_res_2 <= 1'b0;
    end else begin
        if (((lstm_infer_U0_ap_done & lstm_infer_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_res_2 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_res_2 <= ap_sync_channel_write_res_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_res_3 <= 1'b0;
    end else begin
        if (((lstm_infer_U0_ap_done & lstm_infer_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_res_3 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_res_3 <= ap_sync_channel_write_res_3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_res_4 <= 1'b0;
    end else begin
        if (((lstm_infer_U0_ap_done & lstm_infer_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_res_4 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_res_4 <= ap_sync_channel_write_res_4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_res_5 <= 1'b0;
    end else begin
        if (((lstm_infer_U0_ap_done & lstm_infer_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_res_5 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_res_5 <= ap_sync_channel_write_res_5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_res_6 <= 1'b0;
    end else begin
        if (((lstm_infer_U0_ap_done & lstm_infer_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_res_6 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_res_6 <= ap_sync_channel_write_res_6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_res_7 <= 1'b0;
    end else begin
        if (((lstm_infer_U0_ap_done & lstm_infer_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_res_7 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_res_7 <= ap_sync_channel_write_res_7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_res_8 <= 1'b0;
    end else begin
        if (((lstm_infer_U0_ap_done & lstm_infer_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_res_8 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_res_8 <= ap_sync_channel_write_res_8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_res_9 <= 1'b0;
    end else begin
        if (((lstm_infer_U0_ap_done & lstm_infer_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_res_9 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_res_9 <= ap_sync_channel_write_res_9;
        end
    end
end

assign Block_proc_U0_ap_continue = (ap_sync_channel_write_input_ping & ap_sync_channel_write_data_lens_load_loc_c);

assign Block_proc_U0_ap_start = 1'b1;

assign Block_proc_U0_input_ping_full_n = input_ping_i_full_n;

assign Block_proc_U0_start_full_n = 1'b1;

assign Block_proc_U0_start_write = 1'b0;

assign ap_channel_done_data_lens_load_loc_c = ((ap_sync_reg_channel_write_data_lens_load_loc_c ^ 1'b1) & Block_proc_U0_ap_done);

assign ap_channel_done_input_ping = ((ap_sync_reg_channel_write_input_ping ^ 1'b1) & Block_proc_U0_ap_done);

assign ap_channel_done_res_0 = (lstm_infer_U0_ap_done & (ap_sync_reg_channel_write_res_0 ^ 1'b1));

assign ap_channel_done_res_1 = (lstm_infer_U0_ap_done & (ap_sync_reg_channel_write_res_1 ^ 1'b1));

assign ap_channel_done_res_2 = (lstm_infer_U0_ap_done & (ap_sync_reg_channel_write_res_2 ^ 1'b1));

assign ap_channel_done_res_3 = (lstm_infer_U0_ap_done & (ap_sync_reg_channel_write_res_3 ^ 1'b1));

assign ap_channel_done_res_4 = (lstm_infer_U0_ap_done & (ap_sync_reg_channel_write_res_4 ^ 1'b1));

assign ap_channel_done_res_5 = (lstm_infer_U0_ap_done & (ap_sync_reg_channel_write_res_5 ^ 1'b1));

assign ap_channel_done_res_6 = (lstm_infer_U0_ap_done & (ap_sync_reg_channel_write_res_6 ^ 1'b1));

assign ap_channel_done_res_7 = (lstm_infer_U0_ap_done & (ap_sync_reg_channel_write_res_7 ^ 1'b1));

assign ap_channel_done_res_8 = (lstm_infer_U0_ap_done & (ap_sync_reg_channel_write_res_8 ^ 1'b1));

assign ap_channel_done_res_9 = (lstm_infer_U0_ap_done & (ap_sync_reg_channel_write_res_9 ^ 1'b1));

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_channel_write_data_lens_load_loc_c = ((data_lens_load_loc_c_full_n & ap_channel_done_data_lens_load_loc_c) | ap_sync_reg_channel_write_data_lens_load_loc_c);

assign ap_sync_channel_write_input_ping = ((ap_channel_done_input_ping & Block_proc_U0_input_ping_full_n) | ap_sync_reg_channel_write_input_ping);

assign ap_sync_channel_write_res_0 = ((res_0_full_n & ap_channel_done_res_0) | ap_sync_reg_channel_write_res_0);

assign ap_sync_channel_write_res_1 = ((res_1_full_n & ap_channel_done_res_1) | ap_sync_reg_channel_write_res_1);

assign ap_sync_channel_write_res_2 = ((res_2_full_n & ap_channel_done_res_2) | ap_sync_reg_channel_write_res_2);

assign ap_sync_channel_write_res_3 = ((res_3_full_n & ap_channel_done_res_3) | ap_sync_reg_channel_write_res_3);

assign ap_sync_channel_write_res_4 = ((res_4_full_n & ap_channel_done_res_4) | ap_sync_reg_channel_write_res_4);

assign ap_sync_channel_write_res_5 = ((res_5_full_n & ap_channel_done_res_5) | ap_sync_reg_channel_write_res_5);

assign ap_sync_channel_write_res_6 = ((res_6_full_n & ap_channel_done_res_6) | ap_sync_reg_channel_write_res_6);

assign ap_sync_channel_write_res_7 = ((res_7_full_n & ap_channel_done_res_7) | ap_sync_reg_channel_write_res_7);

assign ap_sync_channel_write_res_8 = ((res_8_full_n & ap_channel_done_res_8) | ap_sync_reg_channel_write_res_8);

assign ap_sync_channel_write_res_9 = ((res_9_full_n & ap_channel_done_res_9) | ap_sync_reg_channel_write_res_9);

assign ap_sync_continue = 1'b0;

assign input_stream_TREADY = Block_proc_U0_input_stream_TREADY;

assign lstm_infer_U0_ap_continue = (ap_sync_channel_write_res_9 & ap_sync_channel_write_res_8 & ap_sync_channel_write_res_7 & ap_sync_channel_write_res_6 & ap_sync_channel_write_res_5 & ap_sync_channel_write_res_4 & ap_sync_channel_write_res_3 & ap_sync_channel_write_res_2 & ap_sync_channel_write_res_1 & ap_sync_channel_write_res_0);

assign lstm_infer_U0_ap_start = (input_ping_t_empty_n & data_lens_load_loc_c_empty_n);

assign lstm_infer_U0_start_full_n = 1'b1;

assign lstm_infer_U0_start_write = 1'b0;

assign output_stream_TDATA = write_output_U0_output_stream_TDATA;

assign output_stream_TDEST = write_output_U0_output_stream_TDEST;

assign output_stream_TID = write_output_U0_output_stream_TID;

assign output_stream_TKEEP = write_output_U0_output_stream_TKEEP;

assign output_stream_TLAST = write_output_U0_output_stream_TLAST;

assign output_stream_TSTRB = write_output_U0_output_stream_TSTRB;

assign output_stream_TUSER = write_output_U0_output_stream_TUSER;

assign output_stream_TVALID = write_output_U0_output_stream_TVALID;

assign write_output_U0_ap_continue = 1'b1;

assign write_output_U0_ap_start = (res_9_empty_n & res_8_empty_n & res_7_empty_n & res_6_empty_n & res_5_empty_n & res_4_empty_n & res_3_empty_n & res_2_empty_n & res_1_empty_n & res_0_empty_n);

assign write_output_U0_start_full_n = 1'b1;

assign write_output_U0_start_write = 1'b0;

endmodule //BiLSTM_Top
