-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity BiLSTM_Top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    input_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    input_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    input_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    input_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TVALID : IN STD_LOGIC;
    input_stream_TREADY : OUT STD_LOGIC;
    output_stream_TVALID : OUT STD_LOGIC;
    output_stream_TREADY : IN STD_LOGIC );
end;


architecture behav of BiLSTM_Top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "BiLSTM_Top,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=9.760500,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=236,HLS_SYN_DSP=510,HLS_SYN_FF=17975,HLS_SYN_LUT=25914,HLS_VERSION=2018_3}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal input_ping_i_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_ping_t_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_proc_U0_ap_start : STD_LOGIC;
    signal Block_proc_U0_ap_done : STD_LOGIC;
    signal Block_proc_U0_ap_continue : STD_LOGIC;
    signal Block_proc_U0_ap_idle : STD_LOGIC;
    signal Block_proc_U0_ap_ready : STD_LOGIC;
    signal Block_proc_U0_input_stream_TREADY : STD_LOGIC;
    signal Block_proc_U0_input_ping_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal Block_proc_U0_input_ping_ce0 : STD_LOGIC;
    signal Block_proc_U0_input_ping_we0 : STD_LOGIC;
    signal Block_proc_U0_input_ping_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_proc_U0_ap_return : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_channel_done_data_lens_load_loc_c : STD_LOGIC;
    signal data_lens_load_loc_c_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_data_lens_load_loc_c : STD_LOGIC := '0';
    signal ap_sync_channel_write_data_lens_load_loc_c : STD_LOGIC;
    signal ap_channel_done_input_ping : STD_LOGIC;
    signal Block_proc_U0_input_ping_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_input_ping : STD_LOGIC := '0';
    signal ap_sync_channel_write_input_ping : STD_LOGIC;
    signal lstm_infer_U0_input_r_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal lstm_infer_U0_input_r_ce0 : STD_LOGIC;
    signal lstm_infer_U0_input_r_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal lstm_infer_U0_input_r_we0 : STD_LOGIC;
    signal lstm_infer_U0_input_r_address1 : STD_LOGIC_VECTOR (11 downto 0);
    signal lstm_infer_U0_input_r_ce1 : STD_LOGIC;
    signal lstm_infer_U0_input_r_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lstm_infer_U0_input_r_we1 : STD_LOGIC;
    signal lstm_infer_U0_ress_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal lstm_infer_U0_ress_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lstm_infer_U0_ress_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lstm_infer_U0_ress_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal lstm_infer_U0_ress_4 : STD_LOGIC_VECTOR (31 downto 0);
    signal lstm_infer_U0_ress_5 : STD_LOGIC_VECTOR (31 downto 0);
    signal lstm_infer_U0_ress_6 : STD_LOGIC_VECTOR (31 downto 0);
    signal lstm_infer_U0_ress_7 : STD_LOGIC_VECTOR (31 downto 0);
    signal lstm_infer_U0_ress_8 : STD_LOGIC_VECTOR (31 downto 0);
    signal lstm_infer_U0_ress_9 : STD_LOGIC_VECTOR (31 downto 0);
    signal lstm_infer_U0_input_r_read : STD_LOGIC;
    signal lstm_infer_U0_ap_start : STD_LOGIC;
    signal lstm_infer_U0_ress_0_ap_vld : STD_LOGIC;
    signal lstm_infer_U0_ress_1_ap_vld : STD_LOGIC;
    signal lstm_infer_U0_ress_2_ap_vld : STD_LOGIC;
    signal lstm_infer_U0_ress_3_ap_vld : STD_LOGIC;
    signal lstm_infer_U0_ress_4_ap_vld : STD_LOGIC;
    signal lstm_infer_U0_ress_5_ap_vld : STD_LOGIC;
    signal lstm_infer_U0_ress_6_ap_vld : STD_LOGIC;
    signal lstm_infer_U0_ress_7_ap_vld : STD_LOGIC;
    signal lstm_infer_U0_ress_8_ap_vld : STD_LOGIC;
    signal lstm_infer_U0_ress_9_ap_vld : STD_LOGIC;
    signal lstm_infer_U0_ap_done : STD_LOGIC;
    signal lstm_infer_U0_ap_ready : STD_LOGIC;
    signal lstm_infer_U0_ap_idle : STD_LOGIC;
    signal lstm_infer_U0_ap_continue : STD_LOGIC;
    signal ap_channel_done_res_9 : STD_LOGIC;
    signal res_9_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_res_9 : STD_LOGIC := '0';
    signal ap_sync_channel_write_res_9 : STD_LOGIC;
    signal ap_channel_done_res_8 : STD_LOGIC;
    signal res_8_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_res_8 : STD_LOGIC := '0';
    signal ap_sync_channel_write_res_8 : STD_LOGIC;
    signal ap_channel_done_res_7 : STD_LOGIC;
    signal res_7_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_res_7 : STD_LOGIC := '0';
    signal ap_sync_channel_write_res_7 : STD_LOGIC;
    signal ap_channel_done_res_6 : STD_LOGIC;
    signal res_6_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_res_6 : STD_LOGIC := '0';
    signal ap_sync_channel_write_res_6 : STD_LOGIC;
    signal ap_channel_done_res_5 : STD_LOGIC;
    signal res_5_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_res_5 : STD_LOGIC := '0';
    signal ap_sync_channel_write_res_5 : STD_LOGIC;
    signal ap_channel_done_res_4 : STD_LOGIC;
    signal res_4_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_res_4 : STD_LOGIC := '0';
    signal ap_sync_channel_write_res_4 : STD_LOGIC;
    signal ap_channel_done_res_3 : STD_LOGIC;
    signal res_3_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_res_3 : STD_LOGIC := '0';
    signal ap_sync_channel_write_res_3 : STD_LOGIC;
    signal ap_channel_done_res_2 : STD_LOGIC;
    signal res_2_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_res_2 : STD_LOGIC := '0';
    signal ap_sync_channel_write_res_2 : STD_LOGIC;
    signal ap_channel_done_res_1 : STD_LOGIC;
    signal res_1_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_res_1 : STD_LOGIC := '0';
    signal ap_sync_channel_write_res_1 : STD_LOGIC;
    signal ap_channel_done_res_0 : STD_LOGIC;
    signal res_0_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_res_0 : STD_LOGIC := '0';
    signal ap_sync_channel_write_res_0 : STD_LOGIC;
    signal write_output_U0_ap_start : STD_LOGIC;
    signal write_output_U0_ap_done : STD_LOGIC;
    signal write_output_U0_ap_continue : STD_LOGIC;
    signal write_output_U0_ap_idle : STD_LOGIC;
    signal write_output_U0_ap_ready : STD_LOGIC;
    signal write_output_U0_output_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal write_output_U0_output_stream_TVALID : STD_LOGIC;
    signal write_output_U0_output_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal write_output_U0_output_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal write_output_U0_output_stream_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal write_output_U0_output_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal write_output_U0_output_stream_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal write_output_U0_output_stream_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sync_continue : STD_LOGIC;
    signal input_ping_i_full_n : STD_LOGIC;
    signal input_ping_t_empty_n : STD_LOGIC;
    signal data_lens_load_loc_c_dout : STD_LOGIC_VECTOR (6 downto 0);
    signal data_lens_load_loc_c_empty_n : STD_LOGIC;
    signal res_0_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal res_0_empty_n : STD_LOGIC;
    signal res_1_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal res_1_empty_n : STD_LOGIC;
    signal res_2_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal res_2_empty_n : STD_LOGIC;
    signal res_3_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal res_3_empty_n : STD_LOGIC;
    signal res_4_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal res_4_empty_n : STD_LOGIC;
    signal res_5_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal res_5_empty_n : STD_LOGIC;
    signal res_6_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal res_6_empty_n : STD_LOGIC;
    signal res_7_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal res_7_empty_n : STD_LOGIC;
    signal res_8_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal res_8_empty_n : STD_LOGIC;
    signal res_9_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal res_9_empty_n : STD_LOGIC;
    signal Block_proc_U0_start_full_n : STD_LOGIC;
    signal Block_proc_U0_start_write : STD_LOGIC;
    signal lstm_infer_U0_start_full_n : STD_LOGIC;
    signal lstm_infer_U0_start_write : STD_LOGIC;
    signal write_output_U0_start_full_n : STD_LOGIC;
    signal write_output_U0_start_write : STD_LOGIC;

    component Block_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        input_stream_TVALID : IN STD_LOGIC;
        input_stream_TREADY : OUT STD_LOGIC;
        input_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        input_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        input_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        input_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        input_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        input_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        input_ping_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        input_ping_ce0 : OUT STD_LOGIC;
        input_ping_we0 : OUT STD_LOGIC;
        input_ping_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component lstm_infer IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        input_r_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_r_we0 : OUT STD_LOGIC;
        input_r_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
        input_r_ce1 : OUT STD_LOGIC;
        input_r_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_r_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_r_we1 : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (6 downto 0);
        ress_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ress_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ress_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ress_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ress_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ress_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ress_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ress_7 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ress_8 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ress_9 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_read_ap_vld : IN STD_LOGIC;
        input_r_empty_n : IN STD_LOGIC;
        input_r_read : OUT STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ress_0_ap_vld : OUT STD_LOGIC;
        ress_1_ap_vld : OUT STD_LOGIC;
        ress_2_ap_vld : OUT STD_LOGIC;
        ress_3_ap_vld : OUT STD_LOGIC;
        ress_4_ap_vld : OUT STD_LOGIC;
        ress_5_ap_vld : OUT STD_LOGIC;
        ress_6_ap_vld : OUT STD_LOGIC;
        ress_7_ap_vld : OUT STD_LOGIC;
        ress_8_ap_vld : OUT STD_LOGIC;
        ress_9_ap_vld : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component write_output IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        output_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        output_stream_TVALID : OUT STD_LOGIC;
        output_stream_TREADY : IN STD_LOGIC;
        output_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        output_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        output_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        output_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        output_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        output_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
        res_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        res_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        res_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        res_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        res_4 : IN STD_LOGIC_VECTOR (31 downto 0);
        res_5 : IN STD_LOGIC_VECTOR (31 downto 0);
        res_6 : IN STD_LOGIC_VECTOR (31 downto 0);
        res_7 : IN STD_LOGIC_VECTOR (31 downto 0);
        res_8 : IN STD_LOGIC_VECTOR (31 downto 0);
        res_9 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component BiLSTM_Top_input_cKz IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        i_address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        i_ce0 : IN STD_LOGIC;
        i_we0 : IN STD_LOGIC;
        i_d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        i_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        t_address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        t_ce0 : IN STD_LOGIC;
        t_we0 : IN STD_LOGIC;
        t_d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        t_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        i_ce : IN STD_LOGIC;
        t_ce : IN STD_LOGIC;
        i_full_n : OUT STD_LOGIC;
        i_write : IN STD_LOGIC;
        t_empty_n : OUT STD_LOGIC;
        t_read : IN STD_LOGIC );
    end component;


    component fifo_w7_d2_A_x_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (6 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fifo_w32_d2_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    input_ping_U : component BiLSTM_Top_input_cKz
    generic map (
        DataWidth => 32,
        AddressRange => 3900,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => Block_proc_U0_input_ping_address0,
        i_ce0 => Block_proc_U0_input_ping_ce0,
        i_we0 => Block_proc_U0_input_ping_we0,
        i_d0 => Block_proc_U0_input_ping_d0,
        i_q0 => input_ping_i_q0,
        t_address0 => lstm_infer_U0_input_r_address0,
        t_ce0 => lstm_infer_U0_input_r_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv32_0,
        t_q0 => input_ping_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => input_ping_i_full_n,
        i_write => ap_channel_done_input_ping,
        t_empty_n => input_ping_t_empty_n,
        t_read => lstm_infer_U0_ap_ready);

    Block_proc_U0 : component Block_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_proc_U0_ap_start,
        ap_done => Block_proc_U0_ap_done,
        ap_continue => Block_proc_U0_ap_continue,
        ap_idle => Block_proc_U0_ap_idle,
        ap_ready => Block_proc_U0_ap_ready,
        input_stream_TDATA => input_stream_TDATA,
        input_stream_TVALID => input_stream_TVALID,
        input_stream_TREADY => Block_proc_U0_input_stream_TREADY,
        input_stream_TKEEP => input_stream_TKEEP,
        input_stream_TSTRB => input_stream_TSTRB,
        input_stream_TUSER => input_stream_TUSER,
        input_stream_TLAST => input_stream_TLAST,
        input_stream_TID => input_stream_TID,
        input_stream_TDEST => input_stream_TDEST,
        input_ping_address0 => Block_proc_U0_input_ping_address0,
        input_ping_ce0 => Block_proc_U0_input_ping_ce0,
        input_ping_we0 => Block_proc_U0_input_ping_we0,
        input_ping_d0 => Block_proc_U0_input_ping_d0,
        ap_return => Block_proc_U0_ap_return);

    lstm_infer_U0 : component lstm_infer
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        input_r_address0 => lstm_infer_U0_input_r_address0,
        input_r_ce0 => lstm_infer_U0_input_r_ce0,
        input_r_d0 => lstm_infer_U0_input_r_d0,
        input_r_q0 => input_ping_t_q0,
        input_r_we0 => lstm_infer_U0_input_r_we0,
        input_r_address1 => lstm_infer_U0_input_r_address1,
        input_r_ce1 => lstm_infer_U0_input_r_ce1,
        input_r_d1 => lstm_infer_U0_input_r_d1,
        input_r_q1 => ap_const_lv32_0,
        input_r_we1 => lstm_infer_U0_input_r_we1,
        p_read => data_lens_load_loc_c_dout,
        ress_0 => lstm_infer_U0_ress_0,
        ress_1 => lstm_infer_U0_ress_1,
        ress_2 => lstm_infer_U0_ress_2,
        ress_3 => lstm_infer_U0_ress_3,
        ress_4 => lstm_infer_U0_ress_4,
        ress_5 => lstm_infer_U0_ress_5,
        ress_6 => lstm_infer_U0_ress_6,
        ress_7 => lstm_infer_U0_ress_7,
        ress_8 => lstm_infer_U0_ress_8,
        ress_9 => lstm_infer_U0_ress_9,
        p_read_ap_vld => ap_const_logic_0,
        input_r_empty_n => ap_const_logic_0,
        input_r_read => lstm_infer_U0_input_r_read,
        ap_start => lstm_infer_U0_ap_start,
        ress_0_ap_vld => lstm_infer_U0_ress_0_ap_vld,
        ress_1_ap_vld => lstm_infer_U0_ress_1_ap_vld,
        ress_2_ap_vld => lstm_infer_U0_ress_2_ap_vld,
        ress_3_ap_vld => lstm_infer_U0_ress_3_ap_vld,
        ress_4_ap_vld => lstm_infer_U0_ress_4_ap_vld,
        ress_5_ap_vld => lstm_infer_U0_ress_5_ap_vld,
        ress_6_ap_vld => lstm_infer_U0_ress_6_ap_vld,
        ress_7_ap_vld => lstm_infer_U0_ress_7_ap_vld,
        ress_8_ap_vld => lstm_infer_U0_ress_8_ap_vld,
        ress_9_ap_vld => lstm_infer_U0_ress_9_ap_vld,
        ap_done => lstm_infer_U0_ap_done,
        ap_ready => lstm_infer_U0_ap_ready,
        ap_idle => lstm_infer_U0_ap_idle,
        ap_continue => lstm_infer_U0_ap_continue);

    write_output_U0 : component write_output
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => write_output_U0_ap_start,
        ap_done => write_output_U0_ap_done,
        ap_continue => write_output_U0_ap_continue,
        ap_idle => write_output_U0_ap_idle,
        ap_ready => write_output_U0_ap_ready,
        output_stream_TDATA => write_output_U0_output_stream_TDATA,
        output_stream_TVALID => write_output_U0_output_stream_TVALID,
        output_stream_TREADY => output_stream_TREADY,
        output_stream_TKEEP => write_output_U0_output_stream_TKEEP,
        output_stream_TSTRB => write_output_U0_output_stream_TSTRB,
        output_stream_TUSER => write_output_U0_output_stream_TUSER,
        output_stream_TLAST => write_output_U0_output_stream_TLAST,
        output_stream_TID => write_output_U0_output_stream_TID,
        output_stream_TDEST => write_output_U0_output_stream_TDEST,
        res_0 => res_0_dout,
        res_1 => res_1_dout,
        res_2 => res_2_dout,
        res_3 => res_3_dout,
        res_4 => res_4_dout,
        res_5 => res_5_dout,
        res_6 => res_6_dout,
        res_7 => res_7_dout,
        res_8 => res_8_dout,
        res_9 => res_9_dout);

    data_lens_load_loc_c_U : component fifo_w7_d2_A_x_x
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_proc_U0_ap_return,
        if_full_n => data_lens_load_loc_c_full_n,
        if_write => ap_channel_done_data_lens_load_loc_c,
        if_dout => data_lens_load_loc_c_dout,
        if_empty_n => data_lens_load_loc_c_empty_n,
        if_read => lstm_infer_U0_ap_ready);

    res_0_U : component fifo_w32_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => lstm_infer_U0_ress_0,
        if_full_n => res_0_full_n,
        if_write => ap_channel_done_res_0,
        if_dout => res_0_dout,
        if_empty_n => res_0_empty_n,
        if_read => write_output_U0_ap_ready);

    res_1_U : component fifo_w32_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => lstm_infer_U0_ress_1,
        if_full_n => res_1_full_n,
        if_write => ap_channel_done_res_1,
        if_dout => res_1_dout,
        if_empty_n => res_1_empty_n,
        if_read => write_output_U0_ap_ready);

    res_2_U : component fifo_w32_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => lstm_infer_U0_ress_2,
        if_full_n => res_2_full_n,
        if_write => ap_channel_done_res_2,
        if_dout => res_2_dout,
        if_empty_n => res_2_empty_n,
        if_read => write_output_U0_ap_ready);

    res_3_U : component fifo_w32_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => lstm_infer_U0_ress_3,
        if_full_n => res_3_full_n,
        if_write => ap_channel_done_res_3,
        if_dout => res_3_dout,
        if_empty_n => res_3_empty_n,
        if_read => write_output_U0_ap_ready);

    res_4_U : component fifo_w32_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => lstm_infer_U0_ress_4,
        if_full_n => res_4_full_n,
        if_write => ap_channel_done_res_4,
        if_dout => res_4_dout,
        if_empty_n => res_4_empty_n,
        if_read => write_output_U0_ap_ready);

    res_5_U : component fifo_w32_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => lstm_infer_U0_ress_5,
        if_full_n => res_5_full_n,
        if_write => ap_channel_done_res_5,
        if_dout => res_5_dout,
        if_empty_n => res_5_empty_n,
        if_read => write_output_U0_ap_ready);

    res_6_U : component fifo_w32_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => lstm_infer_U0_ress_6,
        if_full_n => res_6_full_n,
        if_write => ap_channel_done_res_6,
        if_dout => res_6_dout,
        if_empty_n => res_6_empty_n,
        if_read => write_output_U0_ap_ready);

    res_7_U : component fifo_w32_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => lstm_infer_U0_ress_7,
        if_full_n => res_7_full_n,
        if_write => ap_channel_done_res_7,
        if_dout => res_7_dout,
        if_empty_n => res_7_empty_n,
        if_read => write_output_U0_ap_ready);

    res_8_U : component fifo_w32_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => lstm_infer_U0_ress_8,
        if_full_n => res_8_full_n,
        if_write => ap_channel_done_res_8,
        if_dout => res_8_dout,
        if_empty_n => res_8_empty_n,
        if_read => write_output_U0_ap_ready);

    res_9_U : component fifo_w32_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => lstm_infer_U0_ress_9,
        if_full_n => res_9_full_n,
        if_write => ap_channel_done_res_9,
        if_dout => res_9_dout,
        if_empty_n => res_9_empty_n,
        if_read => write_output_U0_ap_ready);





    ap_sync_reg_channel_write_data_lens_load_loc_c_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_data_lens_load_loc_c <= ap_const_logic_0;
            else
                if (((Block_proc_U0_ap_done and Block_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_data_lens_load_loc_c <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_data_lens_load_loc_c <= ap_sync_channel_write_data_lens_load_loc_c;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_input_ping_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_input_ping <= ap_const_logic_0;
            else
                if (((Block_proc_U0_ap_done and Block_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_input_ping <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_input_ping <= ap_sync_channel_write_input_ping;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_res_0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_res_0 <= ap_const_logic_0;
            else
                if (((lstm_infer_U0_ap_done and lstm_infer_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_res_0 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_res_0 <= ap_sync_channel_write_res_0;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_res_1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_res_1 <= ap_const_logic_0;
            else
                if (((lstm_infer_U0_ap_done and lstm_infer_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_res_1 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_res_1 <= ap_sync_channel_write_res_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_res_2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_res_2 <= ap_const_logic_0;
            else
                if (((lstm_infer_U0_ap_done and lstm_infer_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_res_2 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_res_2 <= ap_sync_channel_write_res_2;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_res_3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_res_3 <= ap_const_logic_0;
            else
                if (((lstm_infer_U0_ap_done and lstm_infer_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_res_3 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_res_3 <= ap_sync_channel_write_res_3;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_res_4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_res_4 <= ap_const_logic_0;
            else
                if (((lstm_infer_U0_ap_done and lstm_infer_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_res_4 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_res_4 <= ap_sync_channel_write_res_4;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_res_5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_res_5 <= ap_const_logic_0;
            else
                if (((lstm_infer_U0_ap_done and lstm_infer_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_res_5 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_res_5 <= ap_sync_channel_write_res_5;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_res_6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_res_6 <= ap_const_logic_0;
            else
                if (((lstm_infer_U0_ap_done and lstm_infer_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_res_6 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_res_6 <= ap_sync_channel_write_res_6;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_res_7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_res_7 <= ap_const_logic_0;
            else
                if (((lstm_infer_U0_ap_done and lstm_infer_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_res_7 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_res_7 <= ap_sync_channel_write_res_7;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_res_8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_res_8 <= ap_const_logic_0;
            else
                if (((lstm_infer_U0_ap_done and lstm_infer_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_res_8 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_res_8 <= ap_sync_channel_write_res_8;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_res_9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_res_9 <= ap_const_logic_0;
            else
                if (((lstm_infer_U0_ap_done and lstm_infer_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_res_9 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_res_9 <= ap_sync_channel_write_res_9;
                end if; 
            end if;
        end if;
    end process;

    Block_proc_U0_ap_continue <= (ap_sync_channel_write_input_ping and ap_sync_channel_write_data_lens_load_loc_c);
    Block_proc_U0_ap_start <= ap_const_logic_1;
    Block_proc_U0_input_ping_full_n <= input_ping_i_full_n;
    Block_proc_U0_start_full_n <= ap_const_logic_1;
    Block_proc_U0_start_write <= ap_const_logic_0;
    ap_channel_done_data_lens_load_loc_c <= ((ap_sync_reg_channel_write_data_lens_load_loc_c xor ap_const_logic_1) and Block_proc_U0_ap_done);
    ap_channel_done_input_ping <= ((ap_sync_reg_channel_write_input_ping xor ap_const_logic_1) and Block_proc_U0_ap_done);
    ap_channel_done_res_0 <= (lstm_infer_U0_ap_done and (ap_sync_reg_channel_write_res_0 xor ap_const_logic_1));
    ap_channel_done_res_1 <= (lstm_infer_U0_ap_done and (ap_sync_reg_channel_write_res_1 xor ap_const_logic_1));
    ap_channel_done_res_2 <= (lstm_infer_U0_ap_done and (ap_sync_reg_channel_write_res_2 xor ap_const_logic_1));
    ap_channel_done_res_3 <= (lstm_infer_U0_ap_done and (ap_sync_reg_channel_write_res_3 xor ap_const_logic_1));
    ap_channel_done_res_4 <= (lstm_infer_U0_ap_done and (ap_sync_reg_channel_write_res_4 xor ap_const_logic_1));
    ap_channel_done_res_5 <= (lstm_infer_U0_ap_done and (ap_sync_reg_channel_write_res_5 xor ap_const_logic_1));
    ap_channel_done_res_6 <= (lstm_infer_U0_ap_done and (ap_sync_reg_channel_write_res_6 xor ap_const_logic_1));
    ap_channel_done_res_7 <= (lstm_infer_U0_ap_done and (ap_sync_reg_channel_write_res_7 xor ap_const_logic_1));
    ap_channel_done_res_8 <= (lstm_infer_U0_ap_done and (ap_sync_reg_channel_write_res_8 xor ap_const_logic_1));
    ap_channel_done_res_9 <= (lstm_infer_U0_ap_done and (ap_sync_reg_channel_write_res_9 xor ap_const_logic_1));

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_channel_write_data_lens_load_loc_c <= ((data_lens_load_loc_c_full_n and ap_channel_done_data_lens_load_loc_c) or ap_sync_reg_channel_write_data_lens_load_loc_c);
    ap_sync_channel_write_input_ping <= ((ap_channel_done_input_ping and Block_proc_U0_input_ping_full_n) or ap_sync_reg_channel_write_input_ping);
    ap_sync_channel_write_res_0 <= ((res_0_full_n and ap_channel_done_res_0) or ap_sync_reg_channel_write_res_0);
    ap_sync_channel_write_res_1 <= ((res_1_full_n and ap_channel_done_res_1) or ap_sync_reg_channel_write_res_1);
    ap_sync_channel_write_res_2 <= ((res_2_full_n and ap_channel_done_res_2) or ap_sync_reg_channel_write_res_2);
    ap_sync_channel_write_res_3 <= ((res_3_full_n and ap_channel_done_res_3) or ap_sync_reg_channel_write_res_3);
    ap_sync_channel_write_res_4 <= ((res_4_full_n and ap_channel_done_res_4) or ap_sync_reg_channel_write_res_4);
    ap_sync_channel_write_res_5 <= ((res_5_full_n and ap_channel_done_res_5) or ap_sync_reg_channel_write_res_5);
    ap_sync_channel_write_res_6 <= ((res_6_full_n and ap_channel_done_res_6) or ap_sync_reg_channel_write_res_6);
    ap_sync_channel_write_res_7 <= ((res_7_full_n and ap_channel_done_res_7) or ap_sync_reg_channel_write_res_7);
    ap_sync_channel_write_res_8 <= ((res_8_full_n and ap_channel_done_res_8) or ap_sync_reg_channel_write_res_8);
    ap_sync_channel_write_res_9 <= ((res_9_full_n and ap_channel_done_res_9) or ap_sync_reg_channel_write_res_9);
    ap_sync_continue <= ap_const_logic_0;
    input_stream_TREADY <= Block_proc_U0_input_stream_TREADY;
    lstm_infer_U0_ap_continue <= (ap_sync_channel_write_res_9 and ap_sync_channel_write_res_8 and ap_sync_channel_write_res_7 and ap_sync_channel_write_res_6 and ap_sync_channel_write_res_5 and ap_sync_channel_write_res_4 and ap_sync_channel_write_res_3 and ap_sync_channel_write_res_2 and ap_sync_channel_write_res_1 and ap_sync_channel_write_res_0);
    lstm_infer_U0_ap_start <= (input_ping_t_empty_n and data_lens_load_loc_c_empty_n);
    lstm_infer_U0_start_full_n <= ap_const_logic_1;
    lstm_infer_U0_start_write <= ap_const_logic_0;
    output_stream_TDATA <= write_output_U0_output_stream_TDATA;
    output_stream_TDEST <= write_output_U0_output_stream_TDEST;
    output_stream_TID <= write_output_U0_output_stream_TID;
    output_stream_TKEEP <= write_output_U0_output_stream_TKEEP;
    output_stream_TLAST <= write_output_U0_output_stream_TLAST;
    output_stream_TSTRB <= write_output_U0_output_stream_TSTRB;
    output_stream_TUSER <= write_output_U0_output_stream_TUSER;
    output_stream_TVALID <= write_output_U0_output_stream_TVALID;
    write_output_U0_ap_continue <= ap_const_logic_1;
    write_output_U0_ap_start <= (res_9_empty_n and res_8_empty_n and res_7_empty_n and res_6_empty_n and res_5_empty_n and res_4_empty_n and res_3_empty_n and res_2_empty_n and res_1_empty_n and res_0_empty_n);
    write_output_U0_start_full_n <= ap_const_logic_1;
    write_output_U0_start_write <= ap_const_logic_0;
end behav;
