// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="BiLSTM_Top,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.235000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=92,HLS_SYN_DSP=493,HLS_SYN_FF=20789,HLS_SYN_LUT=18048,HLS_VERSION=2018_3}" *)

module BiLSTM_Top (
        ap_clk,
        ap_rst_n,
        input_stream_TDATA,
        input_stream_TVALID,
        input_stream_TREADY,
        input_stream_TKEEP,
        input_stream_TSTRB,
        input_stream_TUSER,
        input_stream_TLAST,
        input_stream_TID,
        input_stream_TDEST,
        output_stream_TDATA,
        output_stream_TVALID,
        output_stream_TREADY,
        output_stream_TKEEP,
        output_stream_TSTRB,
        output_stream_TUSER,
        output_stream_TLAST,
        output_stream_TID,
        output_stream_TDEST
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst_n;
input  [31:0] input_stream_TDATA;
input   input_stream_TVALID;
output   input_stream_TREADY;
input  [3:0] input_stream_TKEEP;
input  [3:0] input_stream_TSTRB;
input  [0:0] input_stream_TUSER;
input  [0:0] input_stream_TLAST;
input  [0:0] input_stream_TID;
input  [0:0] input_stream_TDEST;
output  [31:0] output_stream_TDATA;
output   output_stream_TVALID;
input   output_stream_TREADY;
output  [3:0] output_stream_TKEEP;
output  [3:0] output_stream_TSTRB;
output  [0:0] output_stream_TUSER;
output  [0:0] output_stream_TLAST;
output  [0:0] output_stream_TID;
output  [0:0] output_stream_TDEST;

 reg    ap_rst_n_inv;
reg   [31:0] input_stream_V_data_V_0_data_out;
wire    input_stream_V_data_V_0_vld_in;
wire    input_stream_V_data_V_0_vld_out;
wire    input_stream_V_data_V_0_ack_in;
reg    input_stream_V_data_V_0_ack_out;
reg   [31:0] input_stream_V_data_V_0_payload_A;
reg   [31:0] input_stream_V_data_V_0_payload_B;
reg    input_stream_V_data_V_0_sel_rd;
reg    input_stream_V_data_V_0_sel_wr;
wire    input_stream_V_data_V_0_sel;
wire    input_stream_V_data_V_0_load_A;
wire    input_stream_V_data_V_0_load_B;
reg   [1:0] input_stream_V_data_V_0_state;
wire    input_stream_V_data_V_0_state_cmp_full;
reg   [3:0] input_stream_V_keep_V_0_data_out;
wire    input_stream_V_keep_V_0_vld_in;
wire    input_stream_V_keep_V_0_vld_out;
wire    input_stream_V_keep_V_0_ack_in;
reg    input_stream_V_keep_V_0_ack_out;
reg   [3:0] input_stream_V_keep_V_0_payload_A;
reg   [3:0] input_stream_V_keep_V_0_payload_B;
reg    input_stream_V_keep_V_0_sel_rd;
reg    input_stream_V_keep_V_0_sel_wr;
wire    input_stream_V_keep_V_0_sel;
wire    input_stream_V_keep_V_0_load_A;
wire    input_stream_V_keep_V_0_load_B;
reg   [1:0] input_stream_V_keep_V_0_state;
wire    input_stream_V_keep_V_0_state_cmp_full;
reg   [3:0] input_stream_V_strb_V_0_data_out;
wire    input_stream_V_strb_V_0_vld_in;
wire    input_stream_V_strb_V_0_vld_out;
wire    input_stream_V_strb_V_0_ack_in;
reg    input_stream_V_strb_V_0_ack_out;
reg   [3:0] input_stream_V_strb_V_0_payload_A;
reg   [3:0] input_stream_V_strb_V_0_payload_B;
reg    input_stream_V_strb_V_0_sel_rd;
reg    input_stream_V_strb_V_0_sel_wr;
wire    input_stream_V_strb_V_0_sel;
wire    input_stream_V_strb_V_0_load_A;
wire    input_stream_V_strb_V_0_load_B;
reg   [1:0] input_stream_V_strb_V_0_state;
wire    input_stream_V_strb_V_0_state_cmp_full;
reg   [0:0] input_stream_V_user_V_0_data_out;
wire    input_stream_V_user_V_0_vld_in;
wire    input_stream_V_user_V_0_vld_out;
wire    input_stream_V_user_V_0_ack_in;
reg    input_stream_V_user_V_0_ack_out;
reg   [0:0] input_stream_V_user_V_0_payload_A;
reg   [0:0] input_stream_V_user_V_0_payload_B;
reg    input_stream_V_user_V_0_sel_rd;
reg    input_stream_V_user_V_0_sel_wr;
wire    input_stream_V_user_V_0_sel;
wire    input_stream_V_user_V_0_load_A;
wire    input_stream_V_user_V_0_load_B;
reg   [1:0] input_stream_V_user_V_0_state;
wire    input_stream_V_user_V_0_state_cmp_full;
reg   [0:0] input_stream_V_last_V_0_data_out;
wire    input_stream_V_last_V_0_vld_in;
wire    input_stream_V_last_V_0_vld_out;
wire    input_stream_V_last_V_0_ack_in;
reg    input_stream_V_last_V_0_ack_out;
reg   [0:0] input_stream_V_last_V_0_payload_A;
reg   [0:0] input_stream_V_last_V_0_payload_B;
reg    input_stream_V_last_V_0_sel_rd;
reg    input_stream_V_last_V_0_sel_wr;
wire    input_stream_V_last_V_0_sel;
wire    input_stream_V_last_V_0_load_A;
wire    input_stream_V_last_V_0_load_B;
reg   [1:0] input_stream_V_last_V_0_state;
wire    input_stream_V_last_V_0_state_cmp_full;
reg   [0:0] input_stream_V_id_V_0_data_out;
wire    input_stream_V_id_V_0_vld_in;
wire    input_stream_V_id_V_0_vld_out;
wire    input_stream_V_id_V_0_ack_in;
reg    input_stream_V_id_V_0_ack_out;
reg   [0:0] input_stream_V_id_V_0_payload_A;
reg   [0:0] input_stream_V_id_V_0_payload_B;
reg    input_stream_V_id_V_0_sel_rd;
reg    input_stream_V_id_V_0_sel_wr;
wire    input_stream_V_id_V_0_sel;
wire    input_stream_V_id_V_0_load_A;
wire    input_stream_V_id_V_0_load_B;
reg   [1:0] input_stream_V_id_V_0_state;
wire    input_stream_V_id_V_0_state_cmp_full;
reg   [0:0] input_stream_V_dest_V_0_data_out;
wire    input_stream_V_dest_V_0_vld_in;
wire    input_stream_V_dest_V_0_vld_out;
wire    input_stream_V_dest_V_0_ack_in;
reg    input_stream_V_dest_V_0_ack_out;
reg   [0:0] input_stream_V_dest_V_0_payload_A;
reg   [0:0] input_stream_V_dest_V_0_payload_B;
reg    input_stream_V_dest_V_0_sel_rd;
reg    input_stream_V_dest_V_0_sel_wr;
wire    input_stream_V_dest_V_0_sel;
wire    input_stream_V_dest_V_0_load_A;
wire    input_stream_V_dest_V_0_load_B;
reg   [1:0] input_stream_V_dest_V_0_state;
wire    input_stream_V_dest_V_0_state_cmp_full;
reg   [31:0] output_stream_V_data_V_1_data_out;
wire    output_stream_V_data_V_1_vld_in;
wire    output_stream_V_data_V_1_vld_out;
wire    output_stream_V_data_V_1_ack_in;
wire    output_stream_V_data_V_1_ack_out;
reg   [31:0] output_stream_V_data_V_1_payload_A;
reg   [31:0] output_stream_V_data_V_1_payload_B;
reg    output_stream_V_data_V_1_sel_rd;
reg    output_stream_V_data_V_1_sel_wr;
wire    output_stream_V_data_V_1_sel;
wire    output_stream_V_data_V_1_load_A;
wire    output_stream_V_data_V_1_load_B;
reg   [1:0] output_stream_V_data_V_1_state;
wire    output_stream_V_data_V_1_state_cmp_full;
reg   [3:0] output_stream_V_keep_V_1_data_out;
wire    output_stream_V_keep_V_1_vld_in;
wire    output_stream_V_keep_V_1_vld_out;
wire    output_stream_V_keep_V_1_ack_in;
wire    output_stream_V_keep_V_1_ack_out;
reg   [3:0] output_stream_V_keep_V_1_payload_A;
reg   [3:0] output_stream_V_keep_V_1_payload_B;
reg    output_stream_V_keep_V_1_sel_rd;
reg    output_stream_V_keep_V_1_sel_wr;
wire    output_stream_V_keep_V_1_sel;
wire    output_stream_V_keep_V_1_load_A;
wire    output_stream_V_keep_V_1_load_B;
reg   [1:0] output_stream_V_keep_V_1_state;
wire    output_stream_V_keep_V_1_state_cmp_full;
reg   [3:0] output_stream_V_strb_V_1_data_out;
wire    output_stream_V_strb_V_1_vld_in;
wire    output_stream_V_strb_V_1_vld_out;
wire    output_stream_V_strb_V_1_ack_in;
wire    output_stream_V_strb_V_1_ack_out;
reg   [3:0] output_stream_V_strb_V_1_payload_A;
reg   [3:0] output_stream_V_strb_V_1_payload_B;
reg    output_stream_V_strb_V_1_sel_rd;
reg    output_stream_V_strb_V_1_sel_wr;
wire    output_stream_V_strb_V_1_sel;
wire    output_stream_V_strb_V_1_load_A;
wire    output_stream_V_strb_V_1_load_B;
reg   [1:0] output_stream_V_strb_V_1_state;
wire    output_stream_V_strb_V_1_state_cmp_full;
reg   [0:0] output_stream_V_user_V_1_data_out;
wire    output_stream_V_user_V_1_vld_in;
wire    output_stream_V_user_V_1_vld_out;
wire    output_stream_V_user_V_1_ack_in;
wire    output_stream_V_user_V_1_ack_out;
reg   [0:0] output_stream_V_user_V_1_payload_A;
reg   [0:0] output_stream_V_user_V_1_payload_B;
reg    output_stream_V_user_V_1_sel_rd;
reg    output_stream_V_user_V_1_sel_wr;
wire    output_stream_V_user_V_1_sel;
wire    output_stream_V_user_V_1_load_A;
wire    output_stream_V_user_V_1_load_B;
reg   [1:0] output_stream_V_user_V_1_state;
wire    output_stream_V_user_V_1_state_cmp_full;
reg   [0:0] output_stream_V_last_V_1_data_out;
wire    output_stream_V_last_V_1_vld_in;
wire    output_stream_V_last_V_1_vld_out;
wire    output_stream_V_last_V_1_ack_in;
wire    output_stream_V_last_V_1_ack_out;
reg   [0:0] output_stream_V_last_V_1_payload_A;
reg   [0:0] output_stream_V_last_V_1_payload_B;
reg    output_stream_V_last_V_1_sel_rd;
reg    output_stream_V_last_V_1_sel_wr;
wire    output_stream_V_last_V_1_sel;
wire    output_stream_V_last_V_1_load_A;
wire    output_stream_V_last_V_1_load_B;
reg   [1:0] output_stream_V_last_V_1_state;
wire    output_stream_V_last_V_1_state_cmp_full;
reg   [0:0] output_stream_V_id_V_1_data_out;
wire    output_stream_V_id_V_1_vld_in;
wire    output_stream_V_id_V_1_vld_out;
wire    output_stream_V_id_V_1_ack_in;
wire    output_stream_V_id_V_1_ack_out;
reg   [0:0] output_stream_V_id_V_1_payload_A;
reg   [0:0] output_stream_V_id_V_1_payload_B;
reg    output_stream_V_id_V_1_sel_rd;
reg    output_stream_V_id_V_1_sel_wr;
wire    output_stream_V_id_V_1_sel;
wire    output_stream_V_id_V_1_load_A;
wire    output_stream_V_id_V_1_load_B;
reg   [1:0] output_stream_V_id_V_1_state;
wire    output_stream_V_id_V_1_state_cmp_full;
reg   [0:0] output_stream_V_dest_V_1_data_out;
wire    output_stream_V_dest_V_1_vld_in;
wire    output_stream_V_dest_V_1_vld_out;
wire    output_stream_V_dest_V_1_ack_in;
wire    output_stream_V_dest_V_1_ack_out;
reg   [0:0] output_stream_V_dest_V_1_payload_A;
reg   [0:0] output_stream_V_dest_V_1_payload_B;
reg    output_stream_V_dest_V_1_sel_rd;
reg    output_stream_V_dest_V_1_sel_wr;
wire    output_stream_V_dest_V_1_sel;
wire    output_stream_V_dest_V_1_load_A;
wire    output_stream_V_dest_V_1_load_B;
reg   [1:0] output_stream_V_dest_V_1_state;
wire    output_stream_V_dest_V_1_state_cmp_full;
reg   [31:0] seq;
wire   [8:0] data_lens_address0;
reg    data_lens_ce0;
wire   [6:0] data_lens_q0;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state4;
reg   [6:0] data_lens_load_reg_587;
wire    ap_CS_fsm_state5;
reg   [31:0] res_0_reg_592;
wire    ap_CS_fsm_state6;
wire    grp_lstm_infer_fu_267_ap_ready;
wire    grp_lstm_infer_fu_267_ap_done;
reg   [31:0] res_1_reg_597;
reg   [31:0] res_2_reg_602;
reg   [31:0] res_3_reg_607;
reg   [31:0] res_4_reg_612;
reg   [31:0] res_5_reg_617;
reg   [31:0] res_6_reg_622;
reg   [31:0] res_7_reg_627;
reg   [31:0] res_8_reg_632;
reg   [31:0] res_9_reg_637;
reg   [11:0] input_ping_address0;
reg    input_ping_ce0;
reg    input_ping_we0;
wire   [31:0] input_ping_q0;
reg    input_ping_ce1;
wire   [31:0] input_ping_q1;
wire    grp_lstm_infer_fu_267_ap_start;
wire    grp_lstm_infer_fu_267_ap_idle;
wire   [11:0] grp_lstm_infer_fu_267_input_r_address0;
wire    grp_lstm_infer_fu_267_input_r_ce0;
wire   [11:0] grp_lstm_infer_fu_267_input_r_address1;
wire    grp_lstm_infer_fu_267_input_r_ce1;
wire   [31:0] grp_lstm_infer_fu_267_ap_return_0;
wire   [31:0] grp_lstm_infer_fu_267_ap_return_1;
wire   [31:0] grp_lstm_infer_fu_267_ap_return_2;
wire   [31:0] grp_lstm_infer_fu_267_ap_return_3;
wire   [31:0] grp_lstm_infer_fu_267_ap_return_4;
wire   [31:0] grp_lstm_infer_fu_267_ap_return_5;
wire   [31:0] grp_lstm_infer_fu_267_ap_return_6;
wire   [31:0] grp_lstm_infer_fu_267_ap_return_7;
wire   [31:0] grp_lstm_infer_fu_267_ap_return_8;
wire   [31:0] grp_lstm_infer_fu_267_ap_return_9;
wire    grp_write_output_fu_462_ap_start;
wire    grp_write_output_fu_462_ap_done;
wire    grp_write_output_fu_462_ap_idle;
wire    grp_write_output_fu_462_ap_ready;
wire   [31:0] grp_write_output_fu_462_output_stream_TDATA;
wire    grp_write_output_fu_462_output_stream_TVALID;
wire    grp_write_output_fu_462_output_stream_TREADY;
wire   [3:0] grp_write_output_fu_462_output_stream_TKEEP;
wire   [3:0] grp_write_output_fu_462_output_stream_TSTRB;
wire   [0:0] grp_write_output_fu_462_output_stream_TUSER;
wire   [0:0] grp_write_output_fu_462_output_stream_TLAST;
wire   [0:0] grp_write_output_fu_462_output_stream_TID;
wire   [0:0] grp_write_output_fu_462_output_stream_TDEST;
wire    grp_read_input_fu_490_ap_start;
wire    grp_read_input_fu_490_ap_done;
wire    grp_read_input_fu_490_ap_idle;
wire    grp_read_input_fu_490_ap_ready;
wire    grp_read_input_fu_490_input_stream_TVALID;
wire    grp_read_input_fu_490_input_stream_TREADY;
wire   [11:0] grp_read_input_fu_490_input_buf_address0;
wire    grp_read_input_fu_490_input_buf_ce0;
wire    grp_read_input_fu_490_input_buf_we0;
wire   [31:0] grp_read_input_fu_490_input_buf_d0;
wire   [31:0] grp_read_input_fu_490_seq_o;
wire    grp_read_input_fu_490_seq_o_ap_vld;
reg    grp_lstm_infer_fu_267_ap_start_reg;
reg    grp_write_output_fu_462_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_read_input_fu_490_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire  signed [63:0] tmp_fu_527_p1;
wire   [31:0] seq_assign_fu_515_p2;
wire  signed [31:0] seq_assign_fu_515_p0;
wire  signed [31:0] tmp_fu_527_p0;
reg   [7:0] ap_NS_fsm;
wire    ap_CS_fsm_state8;
reg    ap_block_state8;

// power-on initialization
initial begin
#0 input_stream_V_data_V_0_sel_rd = 1'b0;
#0 input_stream_V_data_V_0_sel_wr = 1'b0;
#0 input_stream_V_data_V_0_state = 2'd0;
#0 input_stream_V_keep_V_0_sel_rd = 1'b0;
#0 input_stream_V_keep_V_0_sel_wr = 1'b0;
#0 input_stream_V_keep_V_0_state = 2'd0;
#0 input_stream_V_strb_V_0_sel_rd = 1'b0;
#0 input_stream_V_strb_V_0_sel_wr = 1'b0;
#0 input_stream_V_strb_V_0_state = 2'd0;
#0 input_stream_V_user_V_0_sel_rd = 1'b0;
#0 input_stream_V_user_V_0_sel_wr = 1'b0;
#0 input_stream_V_user_V_0_state = 2'd0;
#0 input_stream_V_last_V_0_sel_rd = 1'b0;
#0 input_stream_V_last_V_0_sel_wr = 1'b0;
#0 input_stream_V_last_V_0_state = 2'd0;
#0 input_stream_V_id_V_0_sel_rd = 1'b0;
#0 input_stream_V_id_V_0_sel_wr = 1'b0;
#0 input_stream_V_id_V_0_state = 2'd0;
#0 input_stream_V_dest_V_0_sel_rd = 1'b0;
#0 input_stream_V_dest_V_0_sel_wr = 1'b0;
#0 input_stream_V_dest_V_0_state = 2'd0;
#0 output_stream_V_data_V_1_sel_rd = 1'b0;
#0 output_stream_V_data_V_1_sel_wr = 1'b0;
#0 output_stream_V_data_V_1_state = 2'd0;
#0 output_stream_V_keep_V_1_sel_rd = 1'b0;
#0 output_stream_V_keep_V_1_sel_wr = 1'b0;
#0 output_stream_V_keep_V_1_state = 2'd0;
#0 output_stream_V_strb_V_1_sel_rd = 1'b0;
#0 output_stream_V_strb_V_1_sel_wr = 1'b0;
#0 output_stream_V_strb_V_1_state = 2'd0;
#0 output_stream_V_user_V_1_sel_rd = 1'b0;
#0 output_stream_V_user_V_1_sel_wr = 1'b0;
#0 output_stream_V_user_V_1_state = 2'd0;
#0 output_stream_V_last_V_1_sel_rd = 1'b0;
#0 output_stream_V_last_V_1_sel_wr = 1'b0;
#0 output_stream_V_last_V_1_state = 2'd0;
#0 output_stream_V_id_V_1_sel_rd = 1'b0;
#0 output_stream_V_id_V_1_sel_wr = 1'b0;
#0 output_stream_V_id_V_1_state = 2'd0;
#0 output_stream_V_dest_V_1_sel_rd = 1'b0;
#0 output_stream_V_dest_V_1_sel_wr = 1'b0;
#0 output_stream_V_dest_V_1_state = 2'd0;
#0 seq = 32'd0;
#0 ap_CS_fsm = 8'd1;
#0 grp_lstm_infer_fu_267_ap_start_reg = 1'b0;
#0 grp_write_output_fu_462_ap_start_reg = 1'b0;
#0 grp_read_input_fu_490_ap_start_reg = 1'b0;
end

BiLSTM_Top_data_lb2s #(
    .DataWidth( 7 ),
    .AddressRange( 300 ),
    .AddressWidth( 9 ))
data_lens_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_lens_address0),
    .ce0(data_lens_ce0),
    .q0(data_lens_q0)
);

BiLSTM_Top_input_b3s #(
    .DataWidth( 32 ),
    .AddressRange( 3900 ),
    .AddressWidth( 12 ))
input_ping_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_ping_address0),
    .ce0(input_ping_ce0),
    .we0(input_ping_we0),
    .d0(grp_read_input_fu_490_input_buf_d0),
    .q0(input_ping_q0),
    .address1(grp_lstm_infer_fu_267_input_r_address1),
    .ce1(input_ping_ce1),
    .q1(input_ping_q1)
);

lstm_infer grp_lstm_infer_fu_267(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_lstm_infer_fu_267_ap_start),
    .ap_done(grp_lstm_infer_fu_267_ap_done),
    .ap_idle(grp_lstm_infer_fu_267_ap_idle),
    .ap_ready(grp_lstm_infer_fu_267_ap_ready),
    .input_r_address0(grp_lstm_infer_fu_267_input_r_address0),
    .input_r_ce0(grp_lstm_infer_fu_267_input_r_ce0),
    .input_r_q0(input_ping_q0),
    .input_r_address1(grp_lstm_infer_fu_267_input_r_address1),
    .input_r_ce1(grp_lstm_infer_fu_267_input_r_ce1),
    .input_r_q1(input_ping_q1),
    .valid_len(data_lens_load_reg_587),
    .ap_return_0(grp_lstm_infer_fu_267_ap_return_0),
    .ap_return_1(grp_lstm_infer_fu_267_ap_return_1),
    .ap_return_2(grp_lstm_infer_fu_267_ap_return_2),
    .ap_return_3(grp_lstm_infer_fu_267_ap_return_3),
    .ap_return_4(grp_lstm_infer_fu_267_ap_return_4),
    .ap_return_5(grp_lstm_infer_fu_267_ap_return_5),
    .ap_return_6(grp_lstm_infer_fu_267_ap_return_6),
    .ap_return_7(grp_lstm_infer_fu_267_ap_return_7),
    .ap_return_8(grp_lstm_infer_fu_267_ap_return_8),
    .ap_return_9(grp_lstm_infer_fu_267_ap_return_9)
);

write_output grp_write_output_fu_462(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_write_output_fu_462_ap_start),
    .ap_done(grp_write_output_fu_462_ap_done),
    .ap_idle(grp_write_output_fu_462_ap_idle),
    .ap_ready(grp_write_output_fu_462_ap_ready),
    .output_stream_TDATA(grp_write_output_fu_462_output_stream_TDATA),
    .output_stream_TVALID(grp_write_output_fu_462_output_stream_TVALID),
    .output_stream_TREADY(grp_write_output_fu_462_output_stream_TREADY),
    .output_stream_TKEEP(grp_write_output_fu_462_output_stream_TKEEP),
    .output_stream_TSTRB(grp_write_output_fu_462_output_stream_TSTRB),
    .output_stream_TUSER(grp_write_output_fu_462_output_stream_TUSER),
    .output_stream_TLAST(grp_write_output_fu_462_output_stream_TLAST),
    .output_stream_TID(grp_write_output_fu_462_output_stream_TID),
    .output_stream_TDEST(grp_write_output_fu_462_output_stream_TDEST),
    .res_0_read(res_0_reg_592),
    .res_1_read(res_1_reg_597),
    .res_2_read(res_2_reg_602),
    .res_3_read(res_3_reg_607),
    .res_4_read(res_4_reg_612),
    .res_5_read(res_5_reg_617),
    .res_6_read(res_6_reg_622),
    .res_7_read(res_7_reg_627),
    .res_8_read(res_8_reg_632),
    .res_9_read(res_9_reg_637)
);

read_input grp_read_input_fu_490(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_read_input_fu_490_ap_start),
    .ap_done(grp_read_input_fu_490_ap_done),
    .ap_idle(grp_read_input_fu_490_ap_idle),
    .ap_ready(grp_read_input_fu_490_ap_ready),
    .input_stream_TDATA(input_stream_V_data_V_0_data_out),
    .input_stream_TVALID(grp_read_input_fu_490_input_stream_TVALID),
    .input_stream_TREADY(grp_read_input_fu_490_input_stream_TREADY),
    .input_stream_TKEEP(input_stream_V_keep_V_0_data_out),
    .input_stream_TSTRB(input_stream_V_strb_V_0_data_out),
    .input_stream_TUSER(input_stream_V_user_V_0_data_out),
    .input_stream_TLAST(input_stream_V_last_V_0_data_out),
    .input_stream_TID(input_stream_V_id_V_0_data_out),
    .input_stream_TDEST(input_stream_V_dest_V_0_data_out),
    .input_buf_address0(grp_read_input_fu_490_input_buf_address0),
    .input_buf_ce0(grp_read_input_fu_490_input_buf_ce0),
    .input_buf_we0(grp_read_input_fu_490_input_buf_we0),
    .input_buf_d0(grp_read_input_fu_490_input_buf_d0),
    .seq_i(seq),
    .seq_o(grp_read_input_fu_490_seq_o),
    .seq_o_ap_vld(grp_read_input_fu_490_seq_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_lstm_infer_fu_267_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_lstm_infer_fu_267_ap_start_reg <= 1'b1;
        end else if ((grp_lstm_infer_fu_267_ap_ready == 1'b1)) begin
            grp_lstm_infer_fu_267_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_read_input_fu_490_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_read_input_fu_490_ap_start_reg <= 1'b1;
        end else if ((grp_read_input_fu_490_ap_ready == 1'b1)) begin
            grp_read_input_fu_490_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_write_output_fu_462_ap_start_reg <= 1'b0;
    end else begin
        if (((grp_lstm_infer_fu_267_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
            grp_write_output_fu_462_ap_start_reg <= 1'b1;
        end else if ((grp_write_output_fu_462_ap_ready == 1'b1)) begin
            grp_write_output_fu_462_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_data_V_0_sel_rd <= 1'b0;
    end else begin
        if (((input_stream_V_data_V_0_ack_out == 1'b1) & (input_stream_V_data_V_0_vld_out == 1'b1))) begin
            input_stream_V_data_V_0_sel_rd <= ~input_stream_V_data_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_data_V_0_sel_wr <= 1'b0;
    end else begin
        if (((input_stream_V_data_V_0_ack_in == 1'b1) & (input_stream_V_data_V_0_vld_in == 1'b1))) begin
            input_stream_V_data_V_0_sel_wr <= ~input_stream_V_data_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_data_V_0_state <= 2'd0;
    end else begin
        if ((((input_stream_V_data_V_0_state == 2'd2) & (input_stream_V_data_V_0_vld_in == 1'b0)) | ((input_stream_V_data_V_0_state == 2'd3) & (input_stream_V_data_V_0_vld_in == 1'b0) & (input_stream_V_data_V_0_ack_out == 1'b1)))) begin
            input_stream_V_data_V_0_state <= 2'd2;
        end else if ((((input_stream_V_data_V_0_state == 2'd1) & (input_stream_V_data_V_0_ack_out == 1'b0)) | ((input_stream_V_data_V_0_state == 2'd3) & (input_stream_V_data_V_0_ack_out == 1'b0) & (input_stream_V_data_V_0_vld_in == 1'b1)))) begin
            input_stream_V_data_V_0_state <= 2'd1;
        end else if (((~((input_stream_V_data_V_0_vld_in == 1'b0) & (input_stream_V_data_V_0_ack_out == 1'b1)) & ~((input_stream_V_data_V_0_ack_out == 1'b0) & (input_stream_V_data_V_0_vld_in == 1'b1)) & (input_stream_V_data_V_0_state == 2'd3)) | ((input_stream_V_data_V_0_state == 2'd1) & (input_stream_V_data_V_0_ack_out == 1'b1)) | ((input_stream_V_data_V_0_state == 2'd2) & (input_stream_V_data_V_0_vld_in == 1'b1)))) begin
            input_stream_V_data_V_0_state <= 2'd3;
        end else begin
            input_stream_V_data_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_dest_V_0_sel_rd <= 1'b0;
    end else begin
        if (((input_stream_V_dest_V_0_ack_out == 1'b1) & (input_stream_V_dest_V_0_vld_out == 1'b1))) begin
            input_stream_V_dest_V_0_sel_rd <= ~input_stream_V_dest_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_dest_V_0_sel_wr <= 1'b0;
    end else begin
        if (((input_stream_V_dest_V_0_ack_in == 1'b1) & (input_stream_V_dest_V_0_vld_in == 1'b1))) begin
            input_stream_V_dest_V_0_sel_wr <= ~input_stream_V_dest_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_dest_V_0_state <= 2'd0;
    end else begin
        if ((((input_stream_V_dest_V_0_state == 2'd2) & (input_stream_V_dest_V_0_vld_in == 1'b0)) | ((input_stream_V_dest_V_0_state == 2'd3) & (input_stream_V_dest_V_0_vld_in == 1'b0) & (input_stream_V_dest_V_0_ack_out == 1'b1)))) begin
            input_stream_V_dest_V_0_state <= 2'd2;
        end else if ((((input_stream_V_dest_V_0_state == 2'd1) & (input_stream_V_dest_V_0_ack_out == 1'b0)) | ((input_stream_V_dest_V_0_state == 2'd3) & (input_stream_V_dest_V_0_ack_out == 1'b0) & (input_stream_V_dest_V_0_vld_in == 1'b1)))) begin
            input_stream_V_dest_V_0_state <= 2'd1;
        end else if (((~((input_stream_V_dest_V_0_vld_in == 1'b0) & (input_stream_V_dest_V_0_ack_out == 1'b1)) & ~((input_stream_V_dest_V_0_ack_out == 1'b0) & (input_stream_V_dest_V_0_vld_in == 1'b1)) & (input_stream_V_dest_V_0_state == 2'd3)) | ((input_stream_V_dest_V_0_state == 2'd1) & (input_stream_V_dest_V_0_ack_out == 1'b1)) | ((input_stream_V_dest_V_0_state == 2'd2) & (input_stream_V_dest_V_0_vld_in == 1'b1)))) begin
            input_stream_V_dest_V_0_state <= 2'd3;
        end else begin
            input_stream_V_dest_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_id_V_0_sel_rd <= 1'b0;
    end else begin
        if (((input_stream_V_id_V_0_ack_out == 1'b1) & (input_stream_V_id_V_0_vld_out == 1'b1))) begin
            input_stream_V_id_V_0_sel_rd <= ~input_stream_V_id_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_id_V_0_sel_wr <= 1'b0;
    end else begin
        if (((input_stream_V_id_V_0_ack_in == 1'b1) & (input_stream_V_id_V_0_vld_in == 1'b1))) begin
            input_stream_V_id_V_0_sel_wr <= ~input_stream_V_id_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_id_V_0_state <= 2'd0;
    end else begin
        if ((((input_stream_V_id_V_0_state == 2'd2) & (input_stream_V_id_V_0_vld_in == 1'b0)) | ((input_stream_V_id_V_0_state == 2'd3) & (input_stream_V_id_V_0_vld_in == 1'b0) & (input_stream_V_id_V_0_ack_out == 1'b1)))) begin
            input_stream_V_id_V_0_state <= 2'd2;
        end else if ((((input_stream_V_id_V_0_state == 2'd1) & (input_stream_V_id_V_0_ack_out == 1'b0)) | ((input_stream_V_id_V_0_state == 2'd3) & (input_stream_V_id_V_0_ack_out == 1'b0) & (input_stream_V_id_V_0_vld_in == 1'b1)))) begin
            input_stream_V_id_V_0_state <= 2'd1;
        end else if (((~((input_stream_V_id_V_0_vld_in == 1'b0) & (input_stream_V_id_V_0_ack_out == 1'b1)) & ~((input_stream_V_id_V_0_ack_out == 1'b0) & (input_stream_V_id_V_0_vld_in == 1'b1)) & (input_stream_V_id_V_0_state == 2'd3)) | ((input_stream_V_id_V_0_state == 2'd1) & (input_stream_V_id_V_0_ack_out == 1'b1)) | ((input_stream_V_id_V_0_state == 2'd2) & (input_stream_V_id_V_0_vld_in == 1'b1)))) begin
            input_stream_V_id_V_0_state <= 2'd3;
        end else begin
            input_stream_V_id_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_keep_V_0_sel_rd <= 1'b0;
    end else begin
        if (((input_stream_V_keep_V_0_ack_out == 1'b1) & (input_stream_V_keep_V_0_vld_out == 1'b1))) begin
            input_stream_V_keep_V_0_sel_rd <= ~input_stream_V_keep_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_keep_V_0_sel_wr <= 1'b0;
    end else begin
        if (((input_stream_V_keep_V_0_ack_in == 1'b1) & (input_stream_V_keep_V_0_vld_in == 1'b1))) begin
            input_stream_V_keep_V_0_sel_wr <= ~input_stream_V_keep_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_keep_V_0_state <= 2'd0;
    end else begin
        if ((((input_stream_V_keep_V_0_state == 2'd2) & (input_stream_V_keep_V_0_vld_in == 1'b0)) | ((input_stream_V_keep_V_0_state == 2'd3) & (input_stream_V_keep_V_0_vld_in == 1'b0) & (input_stream_V_keep_V_0_ack_out == 1'b1)))) begin
            input_stream_V_keep_V_0_state <= 2'd2;
        end else if ((((input_stream_V_keep_V_0_state == 2'd1) & (input_stream_V_keep_V_0_ack_out == 1'b0)) | ((input_stream_V_keep_V_0_state == 2'd3) & (input_stream_V_keep_V_0_ack_out == 1'b0) & (input_stream_V_keep_V_0_vld_in == 1'b1)))) begin
            input_stream_V_keep_V_0_state <= 2'd1;
        end else if (((~((input_stream_V_keep_V_0_vld_in == 1'b0) & (input_stream_V_keep_V_0_ack_out == 1'b1)) & ~((input_stream_V_keep_V_0_ack_out == 1'b0) & (input_stream_V_keep_V_0_vld_in == 1'b1)) & (input_stream_V_keep_V_0_state == 2'd3)) | ((input_stream_V_keep_V_0_state == 2'd1) & (input_stream_V_keep_V_0_ack_out == 1'b1)) | ((input_stream_V_keep_V_0_state == 2'd2) & (input_stream_V_keep_V_0_vld_in == 1'b1)))) begin
            input_stream_V_keep_V_0_state <= 2'd3;
        end else begin
            input_stream_V_keep_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_last_V_0_sel_rd <= 1'b0;
    end else begin
        if (((input_stream_V_last_V_0_ack_out == 1'b1) & (input_stream_V_last_V_0_vld_out == 1'b1))) begin
            input_stream_V_last_V_0_sel_rd <= ~input_stream_V_last_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_last_V_0_sel_wr <= 1'b0;
    end else begin
        if (((input_stream_V_last_V_0_ack_in == 1'b1) & (input_stream_V_last_V_0_vld_in == 1'b1))) begin
            input_stream_V_last_V_0_sel_wr <= ~input_stream_V_last_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_last_V_0_state <= 2'd0;
    end else begin
        if ((((input_stream_V_last_V_0_state == 2'd2) & (input_stream_V_last_V_0_vld_in == 1'b0)) | ((input_stream_V_last_V_0_state == 2'd3) & (input_stream_V_last_V_0_vld_in == 1'b0) & (input_stream_V_last_V_0_ack_out == 1'b1)))) begin
            input_stream_V_last_V_0_state <= 2'd2;
        end else if ((((input_stream_V_last_V_0_state == 2'd1) & (input_stream_V_last_V_0_ack_out == 1'b0)) | ((input_stream_V_last_V_0_state == 2'd3) & (input_stream_V_last_V_0_ack_out == 1'b0) & (input_stream_V_last_V_0_vld_in == 1'b1)))) begin
            input_stream_V_last_V_0_state <= 2'd1;
        end else if (((~((input_stream_V_last_V_0_vld_in == 1'b0) & (input_stream_V_last_V_0_ack_out == 1'b1)) & ~((input_stream_V_last_V_0_ack_out == 1'b0) & (input_stream_V_last_V_0_vld_in == 1'b1)) & (input_stream_V_last_V_0_state == 2'd3)) | ((input_stream_V_last_V_0_state == 2'd1) & (input_stream_V_last_V_0_ack_out == 1'b1)) | ((input_stream_V_last_V_0_state == 2'd2) & (input_stream_V_last_V_0_vld_in == 1'b1)))) begin
            input_stream_V_last_V_0_state <= 2'd3;
        end else begin
            input_stream_V_last_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_strb_V_0_sel_rd <= 1'b0;
    end else begin
        if (((input_stream_V_strb_V_0_ack_out == 1'b1) & (input_stream_V_strb_V_0_vld_out == 1'b1))) begin
            input_stream_V_strb_V_0_sel_rd <= ~input_stream_V_strb_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_strb_V_0_sel_wr <= 1'b0;
    end else begin
        if (((input_stream_V_strb_V_0_ack_in == 1'b1) & (input_stream_V_strb_V_0_vld_in == 1'b1))) begin
            input_stream_V_strb_V_0_sel_wr <= ~input_stream_V_strb_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_strb_V_0_state <= 2'd0;
    end else begin
        if ((((input_stream_V_strb_V_0_state == 2'd2) & (input_stream_V_strb_V_0_vld_in == 1'b0)) | ((input_stream_V_strb_V_0_state == 2'd3) & (input_stream_V_strb_V_0_vld_in == 1'b0) & (input_stream_V_strb_V_0_ack_out == 1'b1)))) begin
            input_stream_V_strb_V_0_state <= 2'd2;
        end else if ((((input_stream_V_strb_V_0_state == 2'd1) & (input_stream_V_strb_V_0_ack_out == 1'b0)) | ((input_stream_V_strb_V_0_state == 2'd3) & (input_stream_V_strb_V_0_ack_out == 1'b0) & (input_stream_V_strb_V_0_vld_in == 1'b1)))) begin
            input_stream_V_strb_V_0_state <= 2'd1;
        end else if (((~((input_stream_V_strb_V_0_vld_in == 1'b0) & (input_stream_V_strb_V_0_ack_out == 1'b1)) & ~((input_stream_V_strb_V_0_ack_out == 1'b0) & (input_stream_V_strb_V_0_vld_in == 1'b1)) & (input_stream_V_strb_V_0_state == 2'd3)) | ((input_stream_V_strb_V_0_state == 2'd1) & (input_stream_V_strb_V_0_ack_out == 1'b1)) | ((input_stream_V_strb_V_0_state == 2'd2) & (input_stream_V_strb_V_0_vld_in == 1'b1)))) begin
            input_stream_V_strb_V_0_state <= 2'd3;
        end else begin
            input_stream_V_strb_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_user_V_0_sel_rd <= 1'b0;
    end else begin
        if (((input_stream_V_user_V_0_ack_out == 1'b1) & (input_stream_V_user_V_0_vld_out == 1'b1))) begin
            input_stream_V_user_V_0_sel_rd <= ~input_stream_V_user_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_user_V_0_sel_wr <= 1'b0;
    end else begin
        if (((input_stream_V_user_V_0_ack_in == 1'b1) & (input_stream_V_user_V_0_vld_in == 1'b1))) begin
            input_stream_V_user_V_0_sel_wr <= ~input_stream_V_user_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        input_stream_V_user_V_0_state <= 2'd0;
    end else begin
        if ((((input_stream_V_user_V_0_state == 2'd2) & (input_stream_V_user_V_0_vld_in == 1'b0)) | ((input_stream_V_user_V_0_state == 2'd3) & (input_stream_V_user_V_0_vld_in == 1'b0) & (input_stream_V_user_V_0_ack_out == 1'b1)))) begin
            input_stream_V_user_V_0_state <= 2'd2;
        end else if ((((input_stream_V_user_V_0_state == 2'd1) & (input_stream_V_user_V_0_ack_out == 1'b0)) | ((input_stream_V_user_V_0_state == 2'd3) & (input_stream_V_user_V_0_ack_out == 1'b0) & (input_stream_V_user_V_0_vld_in == 1'b1)))) begin
            input_stream_V_user_V_0_state <= 2'd1;
        end else if (((~((input_stream_V_user_V_0_vld_in == 1'b0) & (input_stream_V_user_V_0_ack_out == 1'b1)) & ~((input_stream_V_user_V_0_ack_out == 1'b0) & (input_stream_V_user_V_0_vld_in == 1'b1)) & (input_stream_V_user_V_0_state == 2'd3)) | ((input_stream_V_user_V_0_state == 2'd1) & (input_stream_V_user_V_0_ack_out == 1'b1)) | ((input_stream_V_user_V_0_state == 2'd2) & (input_stream_V_user_V_0_vld_in == 1'b1)))) begin
            input_stream_V_user_V_0_state <= 2'd3;
        end else begin
            input_stream_V_user_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_data_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_stream_V_data_V_1_ack_out == 1'b1) & (output_stream_V_data_V_1_vld_out == 1'b1))) begin
            output_stream_V_data_V_1_sel_rd <= ~output_stream_V_data_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_data_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_stream_V_data_V_1_ack_in == 1'b1) & (output_stream_V_data_V_1_vld_in == 1'b1))) begin
            output_stream_V_data_V_1_sel_wr <= ~output_stream_V_data_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_data_V_1_state <= 2'd0;
    end else begin
        if ((((output_stream_V_data_V_1_state == 2'd2) & (output_stream_V_data_V_1_vld_in == 1'b0)) | ((output_stream_V_data_V_1_state == 2'd3) & (output_stream_V_data_V_1_vld_in == 1'b0) & (output_stream_V_data_V_1_ack_out == 1'b1)))) begin
            output_stream_V_data_V_1_state <= 2'd2;
        end else if ((((output_stream_V_data_V_1_state == 2'd1) & (output_stream_V_data_V_1_ack_out == 1'b0)) | ((output_stream_V_data_V_1_state == 2'd3) & (output_stream_V_data_V_1_ack_out == 1'b0) & (output_stream_V_data_V_1_vld_in == 1'b1)))) begin
            output_stream_V_data_V_1_state <= 2'd1;
        end else if (((~((output_stream_V_data_V_1_vld_in == 1'b0) & (output_stream_V_data_V_1_ack_out == 1'b1)) & ~((output_stream_V_data_V_1_ack_out == 1'b0) & (output_stream_V_data_V_1_vld_in == 1'b1)) & (output_stream_V_data_V_1_state == 2'd3)) | ((output_stream_V_data_V_1_state == 2'd1) & (output_stream_V_data_V_1_ack_out == 1'b1)) | ((output_stream_V_data_V_1_state == 2'd2) & (output_stream_V_data_V_1_vld_in == 1'b1)))) begin
            output_stream_V_data_V_1_state <= 2'd3;
        end else begin
            output_stream_V_data_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_dest_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_stream_V_dest_V_1_ack_out == 1'b1) & (output_stream_V_dest_V_1_vld_out == 1'b1))) begin
            output_stream_V_dest_V_1_sel_rd <= ~output_stream_V_dest_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_dest_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_stream_V_dest_V_1_ack_in == 1'b1) & (output_stream_V_dest_V_1_vld_in == 1'b1))) begin
            output_stream_V_dest_V_1_sel_wr <= ~output_stream_V_dest_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_dest_V_1_state <= 2'd0;
    end else begin
        if ((((output_stream_V_dest_V_1_state == 2'd2) & (output_stream_V_dest_V_1_vld_in == 1'b0)) | ((output_stream_V_dest_V_1_state == 2'd3) & (output_stream_V_dest_V_1_vld_in == 1'b0) & (output_stream_V_dest_V_1_ack_out == 1'b1)))) begin
            output_stream_V_dest_V_1_state <= 2'd2;
        end else if ((((output_stream_V_dest_V_1_state == 2'd1) & (output_stream_V_dest_V_1_ack_out == 1'b0)) | ((output_stream_V_dest_V_1_state == 2'd3) & (output_stream_V_dest_V_1_ack_out == 1'b0) & (output_stream_V_dest_V_1_vld_in == 1'b1)))) begin
            output_stream_V_dest_V_1_state <= 2'd1;
        end else if (((~((output_stream_V_dest_V_1_vld_in == 1'b0) & (output_stream_V_dest_V_1_ack_out == 1'b1)) & ~((output_stream_V_dest_V_1_ack_out == 1'b0) & (output_stream_V_dest_V_1_vld_in == 1'b1)) & (output_stream_V_dest_V_1_state == 2'd3)) | ((output_stream_V_dest_V_1_state == 2'd1) & (output_stream_V_dest_V_1_ack_out == 1'b1)) | ((output_stream_V_dest_V_1_state == 2'd2) & (output_stream_V_dest_V_1_vld_in == 1'b1)))) begin
            output_stream_V_dest_V_1_state <= 2'd3;
        end else begin
            output_stream_V_dest_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_id_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_stream_V_id_V_1_ack_out == 1'b1) & (output_stream_V_id_V_1_vld_out == 1'b1))) begin
            output_stream_V_id_V_1_sel_rd <= ~output_stream_V_id_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_id_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_stream_V_id_V_1_ack_in == 1'b1) & (output_stream_V_id_V_1_vld_in == 1'b1))) begin
            output_stream_V_id_V_1_sel_wr <= ~output_stream_V_id_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_id_V_1_state <= 2'd0;
    end else begin
        if ((((output_stream_V_id_V_1_state == 2'd2) & (output_stream_V_id_V_1_vld_in == 1'b0)) | ((output_stream_V_id_V_1_state == 2'd3) & (output_stream_V_id_V_1_vld_in == 1'b0) & (output_stream_V_id_V_1_ack_out == 1'b1)))) begin
            output_stream_V_id_V_1_state <= 2'd2;
        end else if ((((output_stream_V_id_V_1_state == 2'd1) & (output_stream_V_id_V_1_ack_out == 1'b0)) | ((output_stream_V_id_V_1_state == 2'd3) & (output_stream_V_id_V_1_ack_out == 1'b0) & (output_stream_V_id_V_1_vld_in == 1'b1)))) begin
            output_stream_V_id_V_1_state <= 2'd1;
        end else if (((~((output_stream_V_id_V_1_vld_in == 1'b0) & (output_stream_V_id_V_1_ack_out == 1'b1)) & ~((output_stream_V_id_V_1_ack_out == 1'b0) & (output_stream_V_id_V_1_vld_in == 1'b1)) & (output_stream_V_id_V_1_state == 2'd3)) | ((output_stream_V_id_V_1_state == 2'd1) & (output_stream_V_id_V_1_ack_out == 1'b1)) | ((output_stream_V_id_V_1_state == 2'd2) & (output_stream_V_id_V_1_vld_in == 1'b1)))) begin
            output_stream_V_id_V_1_state <= 2'd3;
        end else begin
            output_stream_V_id_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_keep_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_stream_V_keep_V_1_ack_out == 1'b1) & (output_stream_V_keep_V_1_vld_out == 1'b1))) begin
            output_stream_V_keep_V_1_sel_rd <= ~output_stream_V_keep_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_keep_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_stream_V_keep_V_1_ack_in == 1'b1) & (output_stream_V_keep_V_1_vld_in == 1'b1))) begin
            output_stream_V_keep_V_1_sel_wr <= ~output_stream_V_keep_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_keep_V_1_state <= 2'd0;
    end else begin
        if ((((output_stream_V_keep_V_1_state == 2'd2) & (output_stream_V_keep_V_1_vld_in == 1'b0)) | ((output_stream_V_keep_V_1_state == 2'd3) & (output_stream_V_keep_V_1_vld_in == 1'b0) & (output_stream_V_keep_V_1_ack_out == 1'b1)))) begin
            output_stream_V_keep_V_1_state <= 2'd2;
        end else if ((((output_stream_V_keep_V_1_state == 2'd1) & (output_stream_V_keep_V_1_ack_out == 1'b0)) | ((output_stream_V_keep_V_1_state == 2'd3) & (output_stream_V_keep_V_1_ack_out == 1'b0) & (output_stream_V_keep_V_1_vld_in == 1'b1)))) begin
            output_stream_V_keep_V_1_state <= 2'd1;
        end else if (((~((output_stream_V_keep_V_1_vld_in == 1'b0) & (output_stream_V_keep_V_1_ack_out == 1'b1)) & ~((output_stream_V_keep_V_1_ack_out == 1'b0) & (output_stream_V_keep_V_1_vld_in == 1'b1)) & (output_stream_V_keep_V_1_state == 2'd3)) | ((output_stream_V_keep_V_1_state == 2'd1) & (output_stream_V_keep_V_1_ack_out == 1'b1)) | ((output_stream_V_keep_V_1_state == 2'd2) & (output_stream_V_keep_V_1_vld_in == 1'b1)))) begin
            output_stream_V_keep_V_1_state <= 2'd3;
        end else begin
            output_stream_V_keep_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_stream_V_last_V_1_ack_out == 1'b1) & (output_stream_V_last_V_1_vld_out == 1'b1))) begin
            output_stream_V_last_V_1_sel_rd <= ~output_stream_V_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_stream_V_last_V_1_ack_in == 1'b1) & (output_stream_V_last_V_1_vld_in == 1'b1))) begin
            output_stream_V_last_V_1_sel_wr <= ~output_stream_V_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_last_V_1_state <= 2'd0;
    end else begin
        if ((((output_stream_V_last_V_1_state == 2'd2) & (output_stream_V_last_V_1_vld_in == 1'b0)) | ((output_stream_V_last_V_1_state == 2'd3) & (output_stream_V_last_V_1_vld_in == 1'b0) & (output_stream_V_last_V_1_ack_out == 1'b1)))) begin
            output_stream_V_last_V_1_state <= 2'd2;
        end else if ((((output_stream_V_last_V_1_state == 2'd1) & (output_stream_V_last_V_1_ack_out == 1'b0)) | ((output_stream_V_last_V_1_state == 2'd3) & (output_stream_V_last_V_1_ack_out == 1'b0) & (output_stream_V_last_V_1_vld_in == 1'b1)))) begin
            output_stream_V_last_V_1_state <= 2'd1;
        end else if (((~((output_stream_V_last_V_1_vld_in == 1'b0) & (output_stream_V_last_V_1_ack_out == 1'b1)) & ~((output_stream_V_last_V_1_ack_out == 1'b0) & (output_stream_V_last_V_1_vld_in == 1'b1)) & (output_stream_V_last_V_1_state == 2'd3)) | ((output_stream_V_last_V_1_state == 2'd1) & (output_stream_V_last_V_1_ack_out == 1'b1)) | ((output_stream_V_last_V_1_state == 2'd2) & (output_stream_V_last_V_1_vld_in == 1'b1)))) begin
            output_stream_V_last_V_1_state <= 2'd3;
        end else begin
            output_stream_V_last_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_strb_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_stream_V_strb_V_1_ack_out == 1'b1) & (output_stream_V_strb_V_1_vld_out == 1'b1))) begin
            output_stream_V_strb_V_1_sel_rd <= ~output_stream_V_strb_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_strb_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_stream_V_strb_V_1_ack_in == 1'b1) & (output_stream_V_strb_V_1_vld_in == 1'b1))) begin
            output_stream_V_strb_V_1_sel_wr <= ~output_stream_V_strb_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_strb_V_1_state <= 2'd0;
    end else begin
        if ((((output_stream_V_strb_V_1_state == 2'd2) & (output_stream_V_strb_V_1_vld_in == 1'b0)) | ((output_stream_V_strb_V_1_state == 2'd3) & (output_stream_V_strb_V_1_vld_in == 1'b0) & (output_stream_V_strb_V_1_ack_out == 1'b1)))) begin
            output_stream_V_strb_V_1_state <= 2'd2;
        end else if ((((output_stream_V_strb_V_1_state == 2'd1) & (output_stream_V_strb_V_1_ack_out == 1'b0)) | ((output_stream_V_strb_V_1_state == 2'd3) & (output_stream_V_strb_V_1_ack_out == 1'b0) & (output_stream_V_strb_V_1_vld_in == 1'b1)))) begin
            output_stream_V_strb_V_1_state <= 2'd1;
        end else if (((~((output_stream_V_strb_V_1_vld_in == 1'b0) & (output_stream_V_strb_V_1_ack_out == 1'b1)) & ~((output_stream_V_strb_V_1_ack_out == 1'b0) & (output_stream_V_strb_V_1_vld_in == 1'b1)) & (output_stream_V_strb_V_1_state == 2'd3)) | ((output_stream_V_strb_V_1_state == 2'd1) & (output_stream_V_strb_V_1_ack_out == 1'b1)) | ((output_stream_V_strb_V_1_state == 2'd2) & (output_stream_V_strb_V_1_vld_in == 1'b1)))) begin
            output_stream_V_strb_V_1_state <= 2'd3;
        end else begin
            output_stream_V_strb_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_user_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_stream_V_user_V_1_ack_out == 1'b1) & (output_stream_V_user_V_1_vld_out == 1'b1))) begin
            output_stream_V_user_V_1_sel_rd <= ~output_stream_V_user_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_user_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_stream_V_user_V_1_ack_in == 1'b1) & (output_stream_V_user_V_1_vld_in == 1'b1))) begin
            output_stream_V_user_V_1_sel_wr <= ~output_stream_V_user_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        output_stream_V_user_V_1_state <= 2'd0;
    end else begin
        if ((((output_stream_V_user_V_1_state == 2'd2) & (output_stream_V_user_V_1_vld_in == 1'b0)) | ((output_stream_V_user_V_1_state == 2'd3) & (output_stream_V_user_V_1_vld_in == 1'b0) & (output_stream_V_user_V_1_ack_out == 1'b1)))) begin
            output_stream_V_user_V_1_state <= 2'd2;
        end else if ((((output_stream_V_user_V_1_state == 2'd1) & (output_stream_V_user_V_1_ack_out == 1'b0)) | ((output_stream_V_user_V_1_state == 2'd3) & (output_stream_V_user_V_1_ack_out == 1'b0) & (output_stream_V_user_V_1_vld_in == 1'b1)))) begin
            output_stream_V_user_V_1_state <= 2'd1;
        end else if (((~((output_stream_V_user_V_1_vld_in == 1'b0) & (output_stream_V_user_V_1_ack_out == 1'b1)) & ~((output_stream_V_user_V_1_ack_out == 1'b0) & (output_stream_V_user_V_1_vld_in == 1'b1)) & (output_stream_V_user_V_1_state == 2'd3)) | ((output_stream_V_user_V_1_state == 2'd1) & (output_stream_V_user_V_1_ack_out == 1'b1)) | ((output_stream_V_user_V_1_state == 2'd2) & (output_stream_V_user_V_1_vld_in == 1'b1)))) begin
            output_stream_V_user_V_1_state <= 2'd3;
        end else begin
            output_stream_V_user_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        seq <= seq_assign_fu_515_p2;
    end else if (((grp_read_input_fu_490_seq_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        seq <= grp_read_input_fu_490_seq_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        data_lens_load_reg_587 <= data_lens_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((input_stream_V_data_V_0_load_A == 1'b1)) begin
        input_stream_V_data_V_0_payload_A <= input_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((input_stream_V_data_V_0_load_B == 1'b1)) begin
        input_stream_V_data_V_0_payload_B <= input_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((input_stream_V_dest_V_0_load_A == 1'b1)) begin
        input_stream_V_dest_V_0_payload_A <= input_stream_TDEST;
    end
end

always @ (posedge ap_clk) begin
    if ((input_stream_V_dest_V_0_load_B == 1'b1)) begin
        input_stream_V_dest_V_0_payload_B <= input_stream_TDEST;
    end
end

always @ (posedge ap_clk) begin
    if ((input_stream_V_id_V_0_load_A == 1'b1)) begin
        input_stream_V_id_V_0_payload_A <= input_stream_TID;
    end
end

always @ (posedge ap_clk) begin
    if ((input_stream_V_id_V_0_load_B == 1'b1)) begin
        input_stream_V_id_V_0_payload_B <= input_stream_TID;
    end
end

always @ (posedge ap_clk) begin
    if ((input_stream_V_keep_V_0_load_A == 1'b1)) begin
        input_stream_V_keep_V_0_payload_A <= input_stream_TKEEP;
    end
end

always @ (posedge ap_clk) begin
    if ((input_stream_V_keep_V_0_load_B == 1'b1)) begin
        input_stream_V_keep_V_0_payload_B <= input_stream_TKEEP;
    end
end

always @ (posedge ap_clk) begin
    if ((input_stream_V_last_V_0_load_A == 1'b1)) begin
        input_stream_V_last_V_0_payload_A <= input_stream_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((input_stream_V_last_V_0_load_B == 1'b1)) begin
        input_stream_V_last_V_0_payload_B <= input_stream_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((input_stream_V_strb_V_0_load_A == 1'b1)) begin
        input_stream_V_strb_V_0_payload_A <= input_stream_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if ((input_stream_V_strb_V_0_load_B == 1'b1)) begin
        input_stream_V_strb_V_0_payload_B <= input_stream_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if ((input_stream_V_user_V_0_load_A == 1'b1)) begin
        input_stream_V_user_V_0_payload_A <= input_stream_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((input_stream_V_user_V_0_load_B == 1'b1)) begin
        input_stream_V_user_V_0_payload_B <= input_stream_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((output_stream_V_data_V_1_load_A == 1'b1)) begin
        output_stream_V_data_V_1_payload_A <= grp_write_output_fu_462_output_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((output_stream_V_data_V_1_load_B == 1'b1)) begin
        output_stream_V_data_V_1_payload_B <= grp_write_output_fu_462_output_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((output_stream_V_dest_V_1_load_A == 1'b1)) begin
        output_stream_V_dest_V_1_payload_A <= grp_write_output_fu_462_output_stream_TDEST;
    end
end

always @ (posedge ap_clk) begin
    if ((output_stream_V_dest_V_1_load_B == 1'b1)) begin
        output_stream_V_dest_V_1_payload_B <= grp_write_output_fu_462_output_stream_TDEST;
    end
end

always @ (posedge ap_clk) begin
    if ((output_stream_V_id_V_1_load_A == 1'b1)) begin
        output_stream_V_id_V_1_payload_A <= grp_write_output_fu_462_output_stream_TID;
    end
end

always @ (posedge ap_clk) begin
    if ((output_stream_V_id_V_1_load_B == 1'b1)) begin
        output_stream_V_id_V_1_payload_B <= grp_write_output_fu_462_output_stream_TID;
    end
end

always @ (posedge ap_clk) begin
    if ((output_stream_V_keep_V_1_load_A == 1'b1)) begin
        output_stream_V_keep_V_1_payload_A <= grp_write_output_fu_462_output_stream_TKEEP;
    end
end

always @ (posedge ap_clk) begin
    if ((output_stream_V_keep_V_1_load_B == 1'b1)) begin
        output_stream_V_keep_V_1_payload_B <= grp_write_output_fu_462_output_stream_TKEEP;
    end
end

always @ (posedge ap_clk) begin
    if ((output_stream_V_last_V_1_load_A == 1'b1)) begin
        output_stream_V_last_V_1_payload_A <= grp_write_output_fu_462_output_stream_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((output_stream_V_last_V_1_load_B == 1'b1)) begin
        output_stream_V_last_V_1_payload_B <= grp_write_output_fu_462_output_stream_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((output_stream_V_strb_V_1_load_A == 1'b1)) begin
        output_stream_V_strb_V_1_payload_A <= grp_write_output_fu_462_output_stream_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if ((output_stream_V_strb_V_1_load_B == 1'b1)) begin
        output_stream_V_strb_V_1_payload_B <= grp_write_output_fu_462_output_stream_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if ((output_stream_V_user_V_1_load_A == 1'b1)) begin
        output_stream_V_user_V_1_payload_A <= grp_write_output_fu_462_output_stream_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((output_stream_V_user_V_1_load_B == 1'b1)) begin
        output_stream_V_user_V_1_payload_B <= grp_write_output_fu_462_output_stream_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lstm_infer_fu_267_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        res_0_reg_592 <= grp_lstm_infer_fu_267_ap_return_0;
        res_1_reg_597 <= grp_lstm_infer_fu_267_ap_return_1;
        res_2_reg_602 <= grp_lstm_infer_fu_267_ap_return_2;
        res_3_reg_607 <= grp_lstm_infer_fu_267_ap_return_3;
        res_4_reg_612 <= grp_lstm_infer_fu_267_ap_return_4;
        res_5_reg_617 <= grp_lstm_infer_fu_267_ap_return_5;
        res_6_reg_622 <= grp_lstm_infer_fu_267_ap_return_6;
        res_7_reg_627 <= grp_lstm_infer_fu_267_ap_return_7;
        res_8_reg_632 <= grp_lstm_infer_fu_267_ap_return_8;
        res_9_reg_637 <= grp_lstm_infer_fu_267_ap_return_9;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_lens_ce0 = 1'b1;
    end else begin
        data_lens_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_ping_address0 = grp_read_input_fu_490_input_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        input_ping_address0 = grp_lstm_infer_fu_267_input_r_address0;
    end else begin
        input_ping_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_ping_ce0 = grp_read_input_fu_490_input_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        input_ping_ce0 = grp_lstm_infer_fu_267_input_r_ce0;
    end else begin
        input_ping_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_ping_ce1 = grp_lstm_infer_fu_267_input_r_ce1;
    end else begin
        input_ping_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_ping_we0 = grp_read_input_fu_490_input_buf_we0;
    end else begin
        input_ping_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_stream_V_data_V_0_ack_out = grp_read_input_fu_490_input_stream_TREADY;
    end else begin
        input_stream_V_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((input_stream_V_data_V_0_sel == 1'b1)) begin
        input_stream_V_data_V_0_data_out = input_stream_V_data_V_0_payload_B;
    end else begin
        input_stream_V_data_V_0_data_out = input_stream_V_data_V_0_payload_A;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_stream_V_dest_V_0_ack_out = grp_read_input_fu_490_input_stream_TREADY;
    end else begin
        input_stream_V_dest_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((input_stream_V_dest_V_0_sel == 1'b1)) begin
        input_stream_V_dest_V_0_data_out = input_stream_V_dest_V_0_payload_B;
    end else begin
        input_stream_V_dest_V_0_data_out = input_stream_V_dest_V_0_payload_A;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_stream_V_id_V_0_ack_out = grp_read_input_fu_490_input_stream_TREADY;
    end else begin
        input_stream_V_id_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((input_stream_V_id_V_0_sel == 1'b1)) begin
        input_stream_V_id_V_0_data_out = input_stream_V_id_V_0_payload_B;
    end else begin
        input_stream_V_id_V_0_data_out = input_stream_V_id_V_0_payload_A;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_stream_V_keep_V_0_ack_out = grp_read_input_fu_490_input_stream_TREADY;
    end else begin
        input_stream_V_keep_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((input_stream_V_keep_V_0_sel == 1'b1)) begin
        input_stream_V_keep_V_0_data_out = input_stream_V_keep_V_0_payload_B;
    end else begin
        input_stream_V_keep_V_0_data_out = input_stream_V_keep_V_0_payload_A;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_stream_V_last_V_0_ack_out = grp_read_input_fu_490_input_stream_TREADY;
    end else begin
        input_stream_V_last_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((input_stream_V_last_V_0_sel == 1'b1)) begin
        input_stream_V_last_V_0_data_out = input_stream_V_last_V_0_payload_B;
    end else begin
        input_stream_V_last_V_0_data_out = input_stream_V_last_V_0_payload_A;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_stream_V_strb_V_0_ack_out = grp_read_input_fu_490_input_stream_TREADY;
    end else begin
        input_stream_V_strb_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((input_stream_V_strb_V_0_sel == 1'b1)) begin
        input_stream_V_strb_V_0_data_out = input_stream_V_strb_V_0_payload_B;
    end else begin
        input_stream_V_strb_V_0_data_out = input_stream_V_strb_V_0_payload_A;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_stream_V_user_V_0_ack_out = grp_read_input_fu_490_input_stream_TREADY;
    end else begin
        input_stream_V_user_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((input_stream_V_user_V_0_sel == 1'b1)) begin
        input_stream_V_user_V_0_data_out = input_stream_V_user_V_0_payload_B;
    end else begin
        input_stream_V_user_V_0_data_out = input_stream_V_user_V_0_payload_A;
    end
end

always @ (*) begin
    if ((output_stream_V_data_V_1_sel == 1'b1)) begin
        output_stream_V_data_V_1_data_out = output_stream_V_data_V_1_payload_B;
    end else begin
        output_stream_V_data_V_1_data_out = output_stream_V_data_V_1_payload_A;
    end
end

always @ (*) begin
    if ((output_stream_V_dest_V_1_sel == 1'b1)) begin
        output_stream_V_dest_V_1_data_out = output_stream_V_dest_V_1_payload_B;
    end else begin
        output_stream_V_dest_V_1_data_out = output_stream_V_dest_V_1_payload_A;
    end
end

always @ (*) begin
    if ((output_stream_V_id_V_1_sel == 1'b1)) begin
        output_stream_V_id_V_1_data_out = output_stream_V_id_V_1_payload_B;
    end else begin
        output_stream_V_id_V_1_data_out = output_stream_V_id_V_1_payload_A;
    end
end

always @ (*) begin
    if ((output_stream_V_keep_V_1_sel == 1'b1)) begin
        output_stream_V_keep_V_1_data_out = output_stream_V_keep_V_1_payload_B;
    end else begin
        output_stream_V_keep_V_1_data_out = output_stream_V_keep_V_1_payload_A;
    end
end

always @ (*) begin
    if ((output_stream_V_last_V_1_sel == 1'b1)) begin
        output_stream_V_last_V_1_data_out = output_stream_V_last_V_1_payload_B;
    end else begin
        output_stream_V_last_V_1_data_out = output_stream_V_last_V_1_payload_A;
    end
end

always @ (*) begin
    if ((output_stream_V_strb_V_1_sel == 1'b1)) begin
        output_stream_V_strb_V_1_data_out = output_stream_V_strb_V_1_payload_B;
    end else begin
        output_stream_V_strb_V_1_data_out = output_stream_V_strb_V_1_payload_A;
    end
end

always @ (*) begin
    if ((output_stream_V_user_V_1_sel == 1'b1)) begin
        output_stream_V_user_V_1_data_out = output_stream_V_user_V_1_payload_B;
    end else begin
        output_stream_V_user_V_1_data_out = output_stream_V_user_V_1_payload_A;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_read_input_fu_490_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_lstm_infer_fu_267_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((grp_write_output_fu_462_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if ((~((output_stream_V_dest_V_1_ack_in == 1'b0) | (output_stream_V_id_V_1_ack_in == 1'b0) | (output_stream_V_last_V_1_ack_in == 1'b0) | (output_stream_V_user_V_1_ack_in == 1'b0) | (output_stream_V_strb_V_1_ack_in == 1'b0) | (output_stream_V_keep_V_1_ack_in == 1'b0) | (output_stream_V_data_V_1_ack_in == 1'b0)) & (output_stream_V_dest_V_1_state[1'd0] == 1'b0) & (output_stream_V_id_V_1_state[1'd0] == 1'b0) & (output_stream_V_last_V_1_state[1'd0] == 1'b0) & (output_stream_V_user_V_1_state[1'd0] == 1'b0) & (output_stream_V_strb_V_1_state[1'd0] == 1'b0) & (output_stream_V_keep_V_1_state[1'd0] == 1'b0) & (output_stream_V_data_V_1_state[1'd0] == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state8 = ((output_stream_V_dest_V_1_ack_in == 1'b0) | (output_stream_V_id_V_1_ack_in == 1'b0) | (output_stream_V_last_V_1_ack_in == 1'b0) | (output_stream_V_user_V_1_ack_in == 1'b0) | (output_stream_V_strb_V_1_ack_in == 1'b0) | (output_stream_V_keep_V_1_ack_in == 1'b0) | (output_stream_V_data_V_1_ack_in == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign data_lens_address0 = tmp_fu_527_p1;

assign grp_lstm_infer_fu_267_ap_start = grp_lstm_infer_fu_267_ap_start_reg;

assign grp_read_input_fu_490_ap_start = grp_read_input_fu_490_ap_start_reg;

assign grp_read_input_fu_490_input_stream_TVALID = input_stream_V_dest_V_0_state[1'd0];

assign grp_write_output_fu_462_ap_start = grp_write_output_fu_462_ap_start_reg;

assign grp_write_output_fu_462_output_stream_TREADY = ((output_stream_V_dest_V_1_ack_in & ap_CS_fsm_state7) | (output_stream_V_id_V_1_ack_in & ap_CS_fsm_state7) | (output_stream_V_last_V_1_ack_in & ap_CS_fsm_state7) | (output_stream_V_user_V_1_ack_in & ap_CS_fsm_state7) | (output_stream_V_strb_V_1_ack_in & ap_CS_fsm_state7) | (output_stream_V_keep_V_1_ack_in & ap_CS_fsm_state7) | (output_stream_V_data_V_1_ack_in & ap_CS_fsm_state7));

assign input_stream_TREADY = input_stream_V_dest_V_0_state[1'd1];

assign input_stream_V_data_V_0_ack_in = input_stream_V_data_V_0_state[1'd1];

assign input_stream_V_data_V_0_load_A = (input_stream_V_data_V_0_state_cmp_full & ~input_stream_V_data_V_0_sel_wr);

assign input_stream_V_data_V_0_load_B = (input_stream_V_data_V_0_state_cmp_full & input_stream_V_data_V_0_sel_wr);

assign input_stream_V_data_V_0_sel = input_stream_V_data_V_0_sel_rd;

assign input_stream_V_data_V_0_state_cmp_full = ((input_stream_V_data_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign input_stream_V_data_V_0_vld_in = input_stream_TVALID;

assign input_stream_V_data_V_0_vld_out = input_stream_V_data_V_0_state[1'd0];

assign input_stream_V_dest_V_0_ack_in = input_stream_V_dest_V_0_state[1'd1];

assign input_stream_V_dest_V_0_load_A = (input_stream_V_dest_V_0_state_cmp_full & ~input_stream_V_dest_V_0_sel_wr);

assign input_stream_V_dest_V_0_load_B = (input_stream_V_dest_V_0_state_cmp_full & input_stream_V_dest_V_0_sel_wr);

assign input_stream_V_dest_V_0_sel = input_stream_V_dest_V_0_sel_rd;

assign input_stream_V_dest_V_0_state_cmp_full = ((input_stream_V_dest_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign input_stream_V_dest_V_0_vld_in = input_stream_TVALID;

assign input_stream_V_dest_V_0_vld_out = input_stream_V_dest_V_0_state[1'd0];

assign input_stream_V_id_V_0_ack_in = input_stream_V_id_V_0_state[1'd1];

assign input_stream_V_id_V_0_load_A = (input_stream_V_id_V_0_state_cmp_full & ~input_stream_V_id_V_0_sel_wr);

assign input_stream_V_id_V_0_load_B = (input_stream_V_id_V_0_state_cmp_full & input_stream_V_id_V_0_sel_wr);

assign input_stream_V_id_V_0_sel = input_stream_V_id_V_0_sel_rd;

assign input_stream_V_id_V_0_state_cmp_full = ((input_stream_V_id_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign input_stream_V_id_V_0_vld_in = input_stream_TVALID;

assign input_stream_V_id_V_0_vld_out = input_stream_V_id_V_0_state[1'd0];

assign input_stream_V_keep_V_0_ack_in = input_stream_V_keep_V_0_state[1'd1];

assign input_stream_V_keep_V_0_load_A = (input_stream_V_keep_V_0_state_cmp_full & ~input_stream_V_keep_V_0_sel_wr);

assign input_stream_V_keep_V_0_load_B = (input_stream_V_keep_V_0_state_cmp_full & input_stream_V_keep_V_0_sel_wr);

assign input_stream_V_keep_V_0_sel = input_stream_V_keep_V_0_sel_rd;

assign input_stream_V_keep_V_0_state_cmp_full = ((input_stream_V_keep_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign input_stream_V_keep_V_0_vld_in = input_stream_TVALID;

assign input_stream_V_keep_V_0_vld_out = input_stream_V_keep_V_0_state[1'd0];

assign input_stream_V_last_V_0_ack_in = input_stream_V_last_V_0_state[1'd1];

assign input_stream_V_last_V_0_load_A = (input_stream_V_last_V_0_state_cmp_full & ~input_stream_V_last_V_0_sel_wr);

assign input_stream_V_last_V_0_load_B = (input_stream_V_last_V_0_state_cmp_full & input_stream_V_last_V_0_sel_wr);

assign input_stream_V_last_V_0_sel = input_stream_V_last_V_0_sel_rd;

assign input_stream_V_last_V_0_state_cmp_full = ((input_stream_V_last_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign input_stream_V_last_V_0_vld_in = input_stream_TVALID;

assign input_stream_V_last_V_0_vld_out = input_stream_V_last_V_0_state[1'd0];

assign input_stream_V_strb_V_0_ack_in = input_stream_V_strb_V_0_state[1'd1];

assign input_stream_V_strb_V_0_load_A = (input_stream_V_strb_V_0_state_cmp_full & ~input_stream_V_strb_V_0_sel_wr);

assign input_stream_V_strb_V_0_load_B = (input_stream_V_strb_V_0_state_cmp_full & input_stream_V_strb_V_0_sel_wr);

assign input_stream_V_strb_V_0_sel = input_stream_V_strb_V_0_sel_rd;

assign input_stream_V_strb_V_0_state_cmp_full = ((input_stream_V_strb_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign input_stream_V_strb_V_0_vld_in = input_stream_TVALID;

assign input_stream_V_strb_V_0_vld_out = input_stream_V_strb_V_0_state[1'd0];

assign input_stream_V_user_V_0_ack_in = input_stream_V_user_V_0_state[1'd1];

assign input_stream_V_user_V_0_load_A = (input_stream_V_user_V_0_state_cmp_full & ~input_stream_V_user_V_0_sel_wr);

assign input_stream_V_user_V_0_load_B = (input_stream_V_user_V_0_state_cmp_full & input_stream_V_user_V_0_sel_wr);

assign input_stream_V_user_V_0_sel = input_stream_V_user_V_0_sel_rd;

assign input_stream_V_user_V_0_state_cmp_full = ((input_stream_V_user_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign input_stream_V_user_V_0_vld_in = input_stream_TVALID;

assign input_stream_V_user_V_0_vld_out = input_stream_V_user_V_0_state[1'd0];

assign output_stream_TDATA = output_stream_V_data_V_1_data_out;

assign output_stream_TDEST = output_stream_V_dest_V_1_data_out;

assign output_stream_TID = output_stream_V_id_V_1_data_out;

assign output_stream_TKEEP = output_stream_V_keep_V_1_data_out;

assign output_stream_TLAST = output_stream_V_last_V_1_data_out;

assign output_stream_TSTRB = output_stream_V_strb_V_1_data_out;

assign output_stream_TUSER = output_stream_V_user_V_1_data_out;

assign output_stream_TVALID = output_stream_V_dest_V_1_state[1'd0];

assign output_stream_V_data_V_1_ack_in = output_stream_V_data_V_1_state[1'd1];

assign output_stream_V_data_V_1_ack_out = output_stream_TREADY;

assign output_stream_V_data_V_1_load_A = (output_stream_V_data_V_1_state_cmp_full & ~output_stream_V_data_V_1_sel_wr);

assign output_stream_V_data_V_1_load_B = (output_stream_V_data_V_1_state_cmp_full & output_stream_V_data_V_1_sel_wr);

assign output_stream_V_data_V_1_sel = output_stream_V_data_V_1_sel_rd;

assign output_stream_V_data_V_1_state_cmp_full = ((output_stream_V_data_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_stream_V_data_V_1_vld_in = grp_write_output_fu_462_output_stream_TVALID;

assign output_stream_V_data_V_1_vld_out = output_stream_V_data_V_1_state[1'd0];

assign output_stream_V_dest_V_1_ack_in = output_stream_V_dest_V_1_state[1'd1];

assign output_stream_V_dest_V_1_ack_out = output_stream_TREADY;

assign output_stream_V_dest_V_1_load_A = (output_stream_V_dest_V_1_state_cmp_full & ~output_stream_V_dest_V_1_sel_wr);

assign output_stream_V_dest_V_1_load_B = (output_stream_V_dest_V_1_state_cmp_full & output_stream_V_dest_V_1_sel_wr);

assign output_stream_V_dest_V_1_sel = output_stream_V_dest_V_1_sel_rd;

assign output_stream_V_dest_V_1_state_cmp_full = ((output_stream_V_dest_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_stream_V_dest_V_1_vld_in = grp_write_output_fu_462_output_stream_TVALID;

assign output_stream_V_dest_V_1_vld_out = output_stream_V_dest_V_1_state[1'd0];

assign output_stream_V_id_V_1_ack_in = output_stream_V_id_V_1_state[1'd1];

assign output_stream_V_id_V_1_ack_out = output_stream_TREADY;

assign output_stream_V_id_V_1_load_A = (output_stream_V_id_V_1_state_cmp_full & ~output_stream_V_id_V_1_sel_wr);

assign output_stream_V_id_V_1_load_B = (output_stream_V_id_V_1_state_cmp_full & output_stream_V_id_V_1_sel_wr);

assign output_stream_V_id_V_1_sel = output_stream_V_id_V_1_sel_rd;

assign output_stream_V_id_V_1_state_cmp_full = ((output_stream_V_id_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_stream_V_id_V_1_vld_in = grp_write_output_fu_462_output_stream_TVALID;

assign output_stream_V_id_V_1_vld_out = output_stream_V_id_V_1_state[1'd0];

assign output_stream_V_keep_V_1_ack_in = output_stream_V_keep_V_1_state[1'd1];

assign output_stream_V_keep_V_1_ack_out = output_stream_TREADY;

assign output_stream_V_keep_V_1_load_A = (output_stream_V_keep_V_1_state_cmp_full & ~output_stream_V_keep_V_1_sel_wr);

assign output_stream_V_keep_V_1_load_B = (output_stream_V_keep_V_1_state_cmp_full & output_stream_V_keep_V_1_sel_wr);

assign output_stream_V_keep_V_1_sel = output_stream_V_keep_V_1_sel_rd;

assign output_stream_V_keep_V_1_state_cmp_full = ((output_stream_V_keep_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_stream_V_keep_V_1_vld_in = grp_write_output_fu_462_output_stream_TVALID;

assign output_stream_V_keep_V_1_vld_out = output_stream_V_keep_V_1_state[1'd0];

assign output_stream_V_last_V_1_ack_in = output_stream_V_last_V_1_state[1'd1];

assign output_stream_V_last_V_1_ack_out = output_stream_TREADY;

assign output_stream_V_last_V_1_load_A = (output_stream_V_last_V_1_state_cmp_full & ~output_stream_V_last_V_1_sel_wr);

assign output_stream_V_last_V_1_load_B = (output_stream_V_last_V_1_state_cmp_full & output_stream_V_last_V_1_sel_wr);

assign output_stream_V_last_V_1_sel = output_stream_V_last_V_1_sel_rd;

assign output_stream_V_last_V_1_state_cmp_full = ((output_stream_V_last_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_stream_V_last_V_1_vld_in = grp_write_output_fu_462_output_stream_TVALID;

assign output_stream_V_last_V_1_vld_out = output_stream_V_last_V_1_state[1'd0];

assign output_stream_V_strb_V_1_ack_in = output_stream_V_strb_V_1_state[1'd1];

assign output_stream_V_strb_V_1_ack_out = output_stream_TREADY;

assign output_stream_V_strb_V_1_load_A = (output_stream_V_strb_V_1_state_cmp_full & ~output_stream_V_strb_V_1_sel_wr);

assign output_stream_V_strb_V_1_load_B = (output_stream_V_strb_V_1_state_cmp_full & output_stream_V_strb_V_1_sel_wr);

assign output_stream_V_strb_V_1_sel = output_stream_V_strb_V_1_sel_rd;

assign output_stream_V_strb_V_1_state_cmp_full = ((output_stream_V_strb_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_stream_V_strb_V_1_vld_in = grp_write_output_fu_462_output_stream_TVALID;

assign output_stream_V_strb_V_1_vld_out = output_stream_V_strb_V_1_state[1'd0];

assign output_stream_V_user_V_1_ack_in = output_stream_V_user_V_1_state[1'd1];

assign output_stream_V_user_V_1_ack_out = output_stream_TREADY;

assign output_stream_V_user_V_1_load_A = (output_stream_V_user_V_1_state_cmp_full & ~output_stream_V_user_V_1_sel_wr);

assign output_stream_V_user_V_1_load_B = (output_stream_V_user_V_1_state_cmp_full & output_stream_V_user_V_1_sel_wr);

assign output_stream_V_user_V_1_sel = output_stream_V_user_V_1_sel_rd;

assign output_stream_V_user_V_1_state_cmp_full = ((output_stream_V_user_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_stream_V_user_V_1_vld_in = grp_write_output_fu_462_output_stream_TVALID;

assign output_stream_V_user_V_1_vld_out = output_stream_V_user_V_1_state[1'd0];

assign seq_assign_fu_515_p0 = seq;

assign seq_assign_fu_515_p2 = ($signed(seq_assign_fu_515_p0) + $signed(32'd1));

assign tmp_fu_527_p0 = seq;

assign tmp_fu_527_p1 = tmp_fu_527_p0;

endmodule //BiLSTM_Top
